// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

//go:build !noasm && arm64

package nn

import "github.com/ajroetker/go-highway/hwy"

func initDenseNeonCAsm() {
	DenseFloat32 = denseAsmF32
	DenseFloat64 = denseAsmF64
	if hwy.HasARMFP16() {
		DenseFloat16 = denseAsmF16
	}
	if hwy.HasARMBF16() {
		DenseBFloat16 = denseAsmBF16
	}
}
