//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/gguf/asm/basedequantizeq4_0_c_f32_neon_arm64.c

TEXT ·dequantizeq4_0_c_f32_neon(SB), $0-32
	MOVD data+0(FP), R0
	MOVD output+8(FP), R1
	MOVD plen_data+16(FP), R2
	MOVD plen_output+24(FP), R3
	WORD $0xf9400048            // ldr	x8, [x2]
	WORD $0xf100011f            // cmp	x8, #0
	WORD $0xfa521908            // ccmp	x8, #18, #8, ne
	BGE  BB0_2

BB0_1:
	RET

BB0_2:
	WORD $0xd291c729 // mov	x9, #36409                      ; =0x8e39
	WORD $0xf2a71c69 // movk	x9, #14563, lsl #16
	WORD $0xf2dc71c9 // movk	x9, #58254, lsl #32
	WORD $0xf2e1c709 // movk	x9, #3640, lsl #48
	WORD $0x9b497d08 // smulh	x8, x8, x9
	WORD $0x8b48fd08 // add	x8, x8, x8, lsr #63
	WORD $0x91010029 // add	x9, x1, #64
	WORD $0x9100200a // add	x10, x0, #8
	WORD $0x52a7000b // mov	w11, #939524096                 ; =0x38000000
	B    BB0_4

BB0_3:
	WORD $0x385fa14d // ldurb	w13, [x10, #-6]
	WORD $0x92400dad // and	x13, x13, #0xf
	WORD $0xd10021ad // sub	x13, x13, #8
	WORD $0x9e2201a1 // scvtf	s1, x13
	WORD $0x385fb14d // ldurb	w13, [x10, #-5]
	WORD $0x92400dad // and	x13, x13, #0xf
	WORD $0xd10021ad // sub	x13, x13, #8
	WORD $0x9e2201a0 // scvtf	s0, x13
	WORD $0x385fc14d // ldurb	w13, [x10, #-4]
	WORD $0x92400dad // and	x13, x13, #0xf
	WORD $0xd10021ad // sub	x13, x13, #8
	WORD $0x9e2201a2 // scvtf	s2, x13
	WORD $0x385fd14d // ldurb	w13, [x10, #-3]
	WORD $0x92400dad // and	x13, x13, #0xf
	WORD $0xd10021ad // sub	x13, x13, #8
	WORD $0x9e2201a3 // scvtf	s3, x13
	WORD $0x6e0c0401 // mov.s	v1[1], v0[0]
	WORD $0x1e270180 // fmov	s0, w12
	WORD $0x6e140441 // mov.s	v1[2], v2[0]
	WORD $0x6e1c0461 // mov.s	v1[3], v3[0]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3c9c0121 // stur	q1, [x9, #-64]
	WORD $0x385fe14c // ldurb	w12, [x10, #-2]
	WORD $0x92400d8c // and	x12, x12, #0xf
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220181 // scvtf	s1, x12
	WORD $0x385ff14c // ldurb	w12, [x10, #-1]
	WORD $0x92400d8c // and	x12, x12, #0xf
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220182 // scvtf	s2, x12
	WORD $0x3940014c // ldrb	w12, [x10]
	WORD $0x92400d8c // and	x12, x12, #0xf
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220183 // scvtf	s3, x12
	WORD $0x3940054c // ldrb	w12, [x10, #1]
	WORD $0x92400d8c // and	x12, x12, #0xf
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220184 // scvtf	s4, x12
	WORD $0x6e0c0441 // mov.s	v1[1], v2[0]
	WORD $0x6e140461 // mov.s	v1[2], v3[0]
	WORD $0x6e1c0481 // mov.s	v1[3], v4[0]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3c9d0121 // stur	q1, [x9, #-48]
	WORD $0x3940094c // ldrb	w12, [x10, #2]
	WORD $0x92400d8c // and	x12, x12, #0xf
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220181 // scvtf	s1, x12
	WORD $0x39400d4c // ldrb	w12, [x10, #3]
	WORD $0x92400d8c // and	x12, x12, #0xf
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220182 // scvtf	s2, x12
	WORD $0x3940114c // ldrb	w12, [x10, #4]
	WORD $0x92400d8c // and	x12, x12, #0xf
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220183 // scvtf	s3, x12
	WORD $0x3940154c // ldrb	w12, [x10, #5]
	WORD $0x92400d8c // and	x12, x12, #0xf
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220184 // scvtf	s4, x12
	WORD $0x6e0c0441 // mov.s	v1[1], v2[0]
	WORD $0x6e140461 // mov.s	v1[2], v3[0]
	WORD $0x6e1c0481 // mov.s	v1[3], v4[0]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3c9e0121 // stur	q1, [x9, #-32]
	WORD $0x3940194c // ldrb	w12, [x10, #6]
	WORD $0x92400d8c // and	x12, x12, #0xf
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220181 // scvtf	s1, x12
	WORD $0x39401d4c // ldrb	w12, [x10, #7]
	WORD $0x92400d8c // and	x12, x12, #0xf
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220182 // scvtf	s2, x12
	WORD $0x3940214c // ldrb	w12, [x10, #8]
	WORD $0x92400d8c // and	x12, x12, #0xf
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220183 // scvtf	s3, x12
	WORD $0x3940254c // ldrb	w12, [x10, #9]
	WORD $0x92400d8c // and	x12, x12, #0xf
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220184 // scvtf	s4, x12
	WORD $0x6e0c0441 // mov.s	v1[1], v2[0]
	WORD $0x6e140461 // mov.s	v1[2], v3[0]
	WORD $0x6e1c0481 // mov.s	v1[3], v4[0]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3c9f0121 // stur	q1, [x9, #-16]
	WORD $0x385fa14c // ldurb	w12, [x10, #-6]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220181 // scvtf	s1, x12
	WORD $0x385fb14c // ldurb	w12, [x10, #-5]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220182 // scvtf	s2, x12
	WORD $0x385fc14c // ldurb	w12, [x10, #-4]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220183 // scvtf	s3, x12
	WORD $0x385fd14c // ldurb	w12, [x10, #-3]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220184 // scvtf	s4, x12
	WORD $0x6e0c0441 // mov.s	v1[1], v2[0]
	WORD $0x6e140461 // mov.s	v1[2], v3[0]
	WORD $0x6e1c0481 // mov.s	v1[3], v4[0]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3d800121 // str	q1, [x9]
	WORD $0x385fe14c // ldurb	w12, [x10, #-2]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220181 // scvtf	s1, x12
	WORD $0x385ff14c // ldurb	w12, [x10, #-1]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220182 // scvtf	s2, x12
	WORD $0x3940014c // ldrb	w12, [x10]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220183 // scvtf	s3, x12
	WORD $0x3940054c // ldrb	w12, [x10, #1]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220184 // scvtf	s4, x12
	WORD $0x6e0c0441 // mov.s	v1[1], v2[0]
	WORD $0x6e140461 // mov.s	v1[2], v3[0]
	WORD $0x6e1c0481 // mov.s	v1[3], v4[0]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3d800521 // str	q1, [x9, #16]
	WORD $0x3940094c // ldrb	w12, [x10, #2]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220181 // scvtf	s1, x12
	WORD $0x39400d4c // ldrb	w12, [x10, #3]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220182 // scvtf	s2, x12
	WORD $0x3940114c // ldrb	w12, [x10, #4]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220183 // scvtf	s3, x12
	WORD $0x3940154c // ldrb	w12, [x10, #5]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220184 // scvtf	s4, x12
	WORD $0x6e0c0441 // mov.s	v1[1], v2[0]
	WORD $0x6e140461 // mov.s	v1[2], v3[0]
	WORD $0x6e1c0481 // mov.s	v1[3], v4[0]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3d800921 // str	q1, [x9, #32]
	WORD $0x3940194c // ldrb	w12, [x10, #6]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220181 // scvtf	s1, x12
	WORD $0x39401d4c // ldrb	w12, [x10, #7]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220182 // scvtf	s2, x12
	WORD $0x3940214c // ldrb	w12, [x10, #8]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220183 // scvtf	s3, x12
	WORD $0x3940254c // ldrb	w12, [x10, #9]
	WORD $0xd344fd8c // lsr	x12, x12, #4
	WORD $0xd100218c // sub	x12, x12, #8
	WORD $0x9e220184 // scvtf	s4, x12
	WORD $0x6e0c0441 // mov.s	v1[1], v2[0]
	WORD $0x6e140461 // mov.s	v1[2], v3[0]
	WORD $0x6e1c0481 // mov.s	v1[3], v4[0]
	WORD $0x4f809020 // fmul.4s	v0, v1, v0[0]
	WORD $0x3d800d20 // str	q0, [x9, #48]
	WORD $0x91020129 // add	x9, x9, #128
	WORD $0x9100494a // add	x10, x10, #18
	WORD $0xf1000508 // subs	x8, x8, #1
	BEQ  BB0_1

BB0_4:
	WORD $0x385f914d // ldurb	w13, [x10, #-7]
	WORD $0x53077dac // lsr	w12, w13, #7
	WORD $0x530219ae // ubfx	w14, w13, #2, #5
	WORD $0x5301018c // lsl	w12, w12, #31
	CBZW R14, BB0_3
	WORD $0x385f814f // ldurb	w15, [x10, #-8]
	WORD $0x331805af // bfi	w15, w13, #8, #2
	WORD $0x2a0e5d8c // orr	w12, w12, w14, lsl #23
	WORD $0x2a0f358c // orr	w12, w12, w15, lsl #13
	WORD $0x0b0b018c // add	w12, w12, w11
	B    BB0_3
