//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/gguf/asm/basedequantizeiq4nl_c_f32_neon_arm64.c

#include "textflag.h"

// Constant pool data
DATA CPI0_0<>+0(SB)/4, $0xc2fe0000
DATA CPI0_0<>+4(SB)/4, $0xc2d00000
DATA CPI0_0<>+8(SB)/4, $0xc2a60000
DATA CPI0_0<>+12(SB)/4, $0xc2820000
GLOBL CPI0_0<>(SB), (RODATA|NOPTR), $16
DATA CPI0_1<>+0(SB)/4, $0xc2440000
DATA CPI0_1<>+4(SB)/4, $0xc20c0000
DATA CPI0_1<>+8(SB)/4, $0xc1b00000
DATA CPI0_1<>+12(SB)/4, $0xc1200000
GLOBL CPI0_1<>(SB), (RODATA|NOPTR), $16
DATA CPI0_2<>+0(SB)/4, $0x3f800000
DATA CPI0_2<>+4(SB)/4, $0x41500000
DATA CPI0_2<>+8(SB)/4, $0x41c80000
DATA CPI0_2<>+12(SB)/4, $0x42180000
GLOBL CPI0_2<>(SB), (RODATA|NOPTR), $16
DATA CPI0_3<>+0(SB)/4, $0x42540000
DATA CPI0_3<>+4(SB)/4, $0x428a0000
DATA CPI0_3<>+8(SB)/4, $0x42b20000
DATA CPI0_3<>+12(SB)/4, $0x42e20000
GLOBL CPI0_3<>(SB), (RODATA|NOPTR), $16

TEXT ·dequantizeiq4nl_c_f32_neon(SB), $64-32
	MOVD data+0(FP), R0
	MOVD output+8(FP), R1
	MOVD plen_data+16(FP), R2
	MOVD plen_output+24(FP), R3
	WORD $0xf9400048            // ldr	x8, [x2]
	CBZ  R8, BB0_7
	MOVD $CPI0_0<>(SB), R9
	VLD1 (R9), [V0.B16]
	MOVD $CPI0_1<>(SB), R9
	VLD1 (R9), [V1.B16]
	WORD $0xad0007e0            // stp	q0, q1, [sp]
	MOVD $CPI0_2<>(SB), R9
	VLD1 (R9), [V0.B16]
	MOVD $CPI0_3<>(SB), R9
	VLD1 (R9), [V1.B16]
	WORD $0xad0107e0            // stp	q0, q1, [sp, #32]
	WORD $0xf100491f            // cmp	x8, #18
	BLT  BB0_6
	WORD $0xd291c729            // mov	x9, #36409                      ; =0x8e39
	WORD $0xf2a71c69            // movk	x9, #14563, lsl #16
	WORD $0xf2dc71c9            // movk	x9, #58254, lsl #32
	WORD $0xf2e1c709            // movk	x9, #3640, lsl #48
	WORD $0x9b497d08            // smulh	x8, x8, x9
	WORD $0x8b48fd08            // add	x8, x8, x8, lsr #63
	WORD $0x91010029            // add	x9, x1, #64
	WORD $0x9100200a            // add	x10, x0, #8
	WORD $0x910003eb            // mov	x11, sp
	WORD $0x52a7000c            // mov	w12, #939524096                 ; =0x38000000
	B    BB0_4

BB0_3:
	WORD $0x1e2701a0 // fmov	s0, w13
	WORD $0x385fa14d // ldurb	w13, [x10, #-6]
	WORD $0x92400dad // and	x13, x13, #0xf
	WORD $0x385fb14e // ldurb	w14, [x10, #-5]
	WORD $0x92400dce // and	x14, x14, #0xf
	WORD $0x8b0e096e // add	x14, x11, x14, lsl #2
	WORD $0x385fc14f // ldurb	w15, [x10, #-4]
	WORD $0x92400def // and	x15, x15, #0xf
	WORD $0x8b0f096f // add	x15, x11, x15, lsl #2
	WORD $0x385fd150 // ldurb	w16, [x10, #-3]
	WORD $0x92400e10 // and	x16, x16, #0xf
	WORD $0xbc6d7961 // ldr	s1, [x11, x13, lsl #2]
	WORD $0x0d4091c1 // ld1.s	{ v1 }[1], [x14]
	WORD $0x4d4081e1 // ld1.s	{ v1 }[2], [x15]
	WORD $0x8b10096d // add	x13, x11, x16, lsl #2
	WORD $0x4d4091a1 // ld1.s	{ v1 }[3], [x13]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3c9c0121 // stur	q1, [x9, #-64]
	WORD $0x385fe14d // ldurb	w13, [x10, #-2]
	WORD $0x92400dad // and	x13, x13, #0xf
	WORD $0x385ff14e // ldurb	w14, [x10, #-1]
	WORD $0x92400dce // and	x14, x14, #0xf
	WORD $0x8b0e096e // add	x14, x11, x14, lsl #2
	WORD $0x3940014f // ldrb	w15, [x10]
	WORD $0x92400def // and	x15, x15, #0xf
	WORD $0x8b0f096f // add	x15, x11, x15, lsl #2
	WORD $0x39400550 // ldrb	w16, [x10, #1]
	WORD $0x92400e10 // and	x16, x16, #0xf
	WORD $0x8b100970 // add	x16, x11, x16, lsl #2
	WORD $0xbc6d7961 // ldr	s1, [x11, x13, lsl #2]
	WORD $0x0d4091c1 // ld1.s	{ v1 }[1], [x14]
	WORD $0x4d4081e1 // ld1.s	{ v1 }[2], [x15]
	WORD $0x4d409201 // ld1.s	{ v1 }[3], [x16]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3c9d0121 // stur	q1, [x9, #-48]
	WORD $0x3940094d // ldrb	w13, [x10, #2]
	WORD $0x92400dad // and	x13, x13, #0xf
	WORD $0x39400d4e // ldrb	w14, [x10, #3]
	WORD $0x92400dce // and	x14, x14, #0xf
	WORD $0x8b0e096e // add	x14, x11, x14, lsl #2
	WORD $0x3940114f // ldrb	w15, [x10, #4]
	WORD $0x92400def // and	x15, x15, #0xf
	WORD $0x8b0f096f // add	x15, x11, x15, lsl #2
	WORD $0x39401550 // ldrb	w16, [x10, #5]
	WORD $0x92400e10 // and	x16, x16, #0xf
	WORD $0xbc6d7961 // ldr	s1, [x11, x13, lsl #2]
	WORD $0x0d4091c1 // ld1.s	{ v1 }[1], [x14]
	WORD $0x4d4081e1 // ld1.s	{ v1 }[2], [x15]
	WORD $0x8b10096d // add	x13, x11, x16, lsl #2
	WORD $0x4d4091a1 // ld1.s	{ v1 }[3], [x13]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3c9e0121 // stur	q1, [x9, #-32]
	WORD $0x3940194d // ldrb	w13, [x10, #6]
	WORD $0x92400dad // and	x13, x13, #0xf
	WORD $0x39401d4e // ldrb	w14, [x10, #7]
	WORD $0x92400dce // and	x14, x14, #0xf
	WORD $0x8b0e096e // add	x14, x11, x14, lsl #2
	WORD $0x3940214f // ldrb	w15, [x10, #8]
	WORD $0x92400def // and	x15, x15, #0xf
	WORD $0x8b0f096f // add	x15, x11, x15, lsl #2
	WORD $0x39402550 // ldrb	w16, [x10, #9]
	WORD $0x92400e10 // and	x16, x16, #0xf
	WORD $0x8b100970 // add	x16, x11, x16, lsl #2
	WORD $0xbc6d7961 // ldr	s1, [x11, x13, lsl #2]
	WORD $0x0d4091c1 // ld1.s	{ v1 }[1], [x14]
	WORD $0x4d4081e1 // ld1.s	{ v1 }[2], [x15]
	WORD $0x4d409201 // ld1.s	{ v1 }[3], [x16]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3c9f0121 // stur	q1, [x9, #-16]
	WORD $0x385fa14d // ldurb	w13, [x10, #-6]
	WORD $0xd344fdad // lsr	x13, x13, #4
	WORD $0x385fb14e // ldurb	w14, [x10, #-5]
	WORD $0xd344fdce // lsr	x14, x14, #4
	WORD $0x8b0e096e // add	x14, x11, x14, lsl #2
	WORD $0x385fc14f // ldurb	w15, [x10, #-4]
	WORD $0xd344fdef // lsr	x15, x15, #4
	WORD $0x8b0f096f // add	x15, x11, x15, lsl #2
	WORD $0x385fd150 // ldurb	w16, [x10, #-3]
	WORD $0xd344fe10 // lsr	x16, x16, #4
	WORD $0xbc6d7961 // ldr	s1, [x11, x13, lsl #2]
	WORD $0x0d4091c1 // ld1.s	{ v1 }[1], [x14]
	WORD $0x4d4081e1 // ld1.s	{ v1 }[2], [x15]
	WORD $0x8b10096d // add	x13, x11, x16, lsl #2
	WORD $0x4d4091a1 // ld1.s	{ v1 }[3], [x13]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3d800121 // str	q1, [x9]
	WORD $0x385fe14d // ldurb	w13, [x10, #-2]
	WORD $0xd344fdad // lsr	x13, x13, #4
	WORD $0x385ff14e // ldurb	w14, [x10, #-1]
	WORD $0xd344fdce // lsr	x14, x14, #4
	WORD $0x8b0e096e // add	x14, x11, x14, lsl #2
	WORD $0x3940014f // ldrb	w15, [x10]
	WORD $0xd344fdef // lsr	x15, x15, #4
	WORD $0x8b0f096f // add	x15, x11, x15, lsl #2
	WORD $0x39400550 // ldrb	w16, [x10, #1]
	WORD $0xd344fe10 // lsr	x16, x16, #4
	WORD $0x8b100970 // add	x16, x11, x16, lsl #2
	WORD $0xbc6d7961 // ldr	s1, [x11, x13, lsl #2]
	WORD $0x0d4091c1 // ld1.s	{ v1 }[1], [x14]
	WORD $0x4d4081e1 // ld1.s	{ v1 }[2], [x15]
	WORD $0x4d409201 // ld1.s	{ v1 }[3], [x16]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3d800521 // str	q1, [x9, #16]
	WORD $0x3940094d // ldrb	w13, [x10, #2]
	WORD $0xd344fdad // lsr	x13, x13, #4
	WORD $0x39400d4e // ldrb	w14, [x10, #3]
	WORD $0xd344fdce // lsr	x14, x14, #4
	WORD $0x8b0e096e // add	x14, x11, x14, lsl #2
	WORD $0x3940114f // ldrb	w15, [x10, #4]
	WORD $0xd344fdef // lsr	x15, x15, #4
	WORD $0x8b0f096f // add	x15, x11, x15, lsl #2
	WORD $0x39401550 // ldrb	w16, [x10, #5]
	WORD $0xd344fe10 // lsr	x16, x16, #4
	WORD $0xbc6d7961 // ldr	s1, [x11, x13, lsl #2]
	WORD $0x0d4091c1 // ld1.s	{ v1 }[1], [x14]
	WORD $0x4d4081e1 // ld1.s	{ v1 }[2], [x15]
	WORD $0x8b10096d // add	x13, x11, x16, lsl #2
	WORD $0x4d4091a1 // ld1.s	{ v1 }[3], [x13]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3d800921 // str	q1, [x9, #32]
	WORD $0x3940194d // ldrb	w13, [x10, #6]
	WORD $0xd344fdad // lsr	x13, x13, #4
	WORD $0x39401d4e // ldrb	w14, [x10, #7]
	WORD $0xd344fdce // lsr	x14, x14, #4
	WORD $0x8b0e096e // add	x14, x11, x14, lsl #2
	WORD $0x3940214f // ldrb	w15, [x10, #8]
	WORD $0xd344fdef // lsr	x15, x15, #4
	WORD $0x8b0f096f // add	x15, x11, x15, lsl #2
	WORD $0x39402550 // ldrb	w16, [x10, #9]
	WORD $0xd344fe10 // lsr	x16, x16, #4
	WORD $0x8b100970 // add	x16, x11, x16, lsl #2
	WORD $0xbc6d7961 // ldr	s1, [x11, x13, lsl #2]
	WORD $0x0d4091c1 // ld1.s	{ v1 }[1], [x14]
	WORD $0x4d4081e1 // ld1.s	{ v1 }[2], [x15]
	WORD $0x4d409201 // ld1.s	{ v1 }[3], [x16]
	WORD $0x4f809020 // fmul.4s	v0, v1, v0[0]
	WORD $0x3d800d20 // str	q0, [x9, #48]
	WORD $0x91020129 // add	x9, x9, #128
	WORD $0x9100494a // add	x10, x10, #18
	WORD $0xf1000508 // subs	x8, x8, #1
	BEQ  BB0_6

BB0_4:
	WORD $0x385f914e // ldurb	w14, [x10, #-7]
	WORD $0x53077dcd // lsr	w13, w14, #7
	WORD $0x530219cf // ubfx	w15, w14, #2, #5
	WORD $0x530101ad // lsl	w13, w13, #31
	CBZW R15, BB0_3
	WORD $0x385f8150 // ldurb	w16, [x10, #-8]
	WORD $0x331805d0 // bfi	w16, w14, #8, #2
	WORD $0x2a0f5dad // orr	w13, w13, w15, lsl #23
	WORD $0x2a1035ad // orr	w13, w13, w16, lsl #13
	WORD $0x0b0c01ad // add	w13, w13, w12
	B    BB0_3

BB0_6:
BB0_7:
	RET
