//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   22.1.1
// 	objdump 2.46.0.20260210
// flags: -march=armv8.2-a+dotprod+simd+fp -O3
// source: c/fused_quantize_pack_arm64.c

package asm

import "unsafe"

//go:noescape
func compute_absmax(input unsafe.Pointer, n int64) (result float32)

//go:noescape
func fused_quantize_pack(input unsafe.Pointer, inputStride int64, invScale unsafe.Pointer, subBlockSize, mRows int64, aPanel unsafe.Pointer)

//go:noescape
func fused_quantize_pack_bsum(input unsafe.Pointer, inputStride int64, invScale unsafe.Pointer, subBlockSize, mRows int64, aPanel, bsums unsafe.Pointer)
