//go:build !noasm && arm64
// Code generated by hwygen -c. DO NOT EDIT.

package asm

import "unsafe"

// Public wrapper functions
// MaskedVByteDecodeGroupCU8 computes MaskedVByteDecodeGroup using NEON SIMD assembly.
func MaskedVByteDecodeGroupCU8(src []byte, dst []uint32) (int, int) {
	if len(src) == 0 {
		return 0, 0
	}
	var p_src unsafe.Pointer
	if len(src) > 0 {
		p_src = unsafe.Pointer(&src[0])
	}
	var p_dst unsafe.Pointer
	if len(dst) > 0 {
		p_dst = unsafe.Pointer(&dst[0])
	}
	lenVal := int64(len(src))
	var out_decoded int64
	var out_consumed int64
	maskedvbytedecodegroup_c_u8_neon(
		p_src,
		p_dst,
		unsafe.Pointer(&lenVal),
		unsafe.Pointer(&out_decoded),
		unsafe.Pointer(&out_consumed),
	)
	return int(out_decoded), int(out_consumed)
}

