//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   22.1.1
// 	objdump 2.46.0.20260210
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/nn/asm/basesoftmaxinplace_c_f32_neon_arm64.c

TEXT ·softmaxinplace_c_f32_neon(SB), $0-16
	MOVD x+0(FP), R0
	MOVD plen_x+8(FP), R1
	WORD $0xf9400028      // ldr	x8, [x1]
	CBZ  R8, BB0_22
	WORD $0xbd400000      // ldr	s0, [x0]
	WORD $0x6f00e401      // movi.2d	v1, #0000000000000000
	WORD $0xf100091f      // cmp	x8, #2
	BLT  BB0_5
	WORD $0x52800029      // mov	w9, #1                          ; =0x1

BB0_3:
	WORD $0xbc697802 // ldr	s2, [x0, x9, lsl #2]
	WORD $0x1e202040 // fcmp	s2, s0
	WORD $0x1e20cc40 // fcsel	s0, s2, s0, gt
	WORD $0x91000529 // add	x9, x9, #1
	WORD $0xeb09011f // cmp	x8, x9
	BNE  BB0_3
	WORD $0xf100111f // cmp	x8, #4
	BHS  BB0_6

BB0_5:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0x52800029 // mov	w9, #1                          ; =0x1
	WORD $0x6e21d421 // faddp.4s	v1, v1, v1
	WORD $0x7e30d821 // faddp.2s	s1, v1
	WORD $0xeb0a010b // subs	x11, x8, x10
	BGT  BB0_9
	B    BB0_15

BB0_6:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0x4e040402 // dup.4s	v2, v0[0]
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0x528e4309 // mov	w9, #29208                      ; =0x7218
	WORD $0x72a85629 // movk	w9, #17073, lsl #16
	WORD $0x4e040d23 // dup.4s	v3, w9
	WORD $0x52954769 // mov	w9, #43579                      ; =0xaa3b
	WORD $0x72a7f709 // movk	w9, #16312, lsl #16
	WORD $0x4e040d24 // dup.4s	v4, w9
	WORD $0x52900009 // mov	w9, #32768                      ; =0x8000
	WORD $0x72b7e629 // movk	w9, #48945, lsl #16
	WORD $0x4e040d25 // dup.4s	v5, w9
	WORD $0x52901069 // mov	w9, #32899                      ; =0x8083
	WORD $0x72a72bc9 // movk	w9, #14686, lsl #16
	WORD $0x4e040d26 // dup.4s	v6, w9
	WORD $0x52816c29 // mov	w9, #2913                       ; =0xb61
	WORD $0x72a756c9 // movk	w9, #15030, lsl #16
	WORD $0x4e040d27 // dup.4s	v7, w9
	WORD $0x52911129 // mov	w9, #34953                      ; =0x8889
	WORD $0x72a78109 // movk	w9, #15368, lsl #16
	WORD $0x4e040d30 // dup.4s	v16, w9
	WORD $0x52955569 // mov	w9, #43691                      ; =0xaaab
	WORD $0x72a7a549 // movk	w9, #15658, lsl #16
	WORD $0x4e040d31 // dup.4s	v17, w9
	WORD $0x52955569 // mov	w9, #43691                      ; =0xaaab
	WORD $0x72a7c549 // movk	w9, #15914, lsl #16
	WORD $0x4e040d32 // dup.4s	v18, w9
	WORD $0x4f03f613 // fmov.4s	v19, #1.00000000
	WORD $0x52958a09 // mov	w9, #44112                      ; =0xac50
	WORD $0x72b855c9 // movk	w9, #49838, lsl #16
	WORD $0x4e040d34 // dup.4s	v20, w9
	WORD $0x6f03d7f5 // mvni.4s	v21, #127, msl #16
	WORD $0x6ea0fab5 // fneg.4s	v21, v21
	WORD $0xaa0003e9 // mov	x9, x0

BB0_7:
	WORD $0x3dc00136 // ldr	q22, [x9]
	WORD $0x4ea2d6d6 // fsub.4s	v22, v22, v2
	WORD $0x6ea3e6d7 // fcmgt.4s	v23, v22, v3
	WORD $0x6e24ded8 // fmul.4s	v24, v22, v4
	WORD $0x4e218b18 // frintn.4s	v24, v24
	WORD $0x6e25df19 // fmul.4s	v25, v24, v5
	WORD $0x4e39d6d9 // fadd.4s	v25, v22, v25
	WORD $0x6e26df1a // fmul.4s	v26, v24, v6
	WORD $0x4e39d759 // fadd.4s	v25, v26, v25
	WORD $0x4eb01e1a // mov.16b	v26, v16
	WORD $0x4e39ccfa // fmla.4s	v26, v7, v25
	WORD $0x4eb11e3b // mov.16b	v27, v17
	WORD $0x4e3acf3b // fmla.4s	v27, v25, v26
	WORD $0x4eb21e5a // mov.16b	v26, v18
	WORD $0x4e3bcf3a // fmla.4s	v26, v25, v27
	WORD $0x4f0167fb // movi.4s	v27, #63, lsl #24
	WORD $0x4e3acf3b // fmla.4s	v27, v25, v26
	WORD $0x4f03f61a // fmov.4s	v26, #1.00000000
	WORD $0x4e3bcf3a // fmla.4s	v26, v25, v27
	WORD $0x4f03f61b // fmov.4s	v27, #1.00000000
	WORD $0x4e3acf3b // fmla.4s	v27, v25, v26
	WORD $0x4e21ab18 // fcvtns.4s	v24, v24
	WORD $0x4f375718 // shl.4s	v24, v24, #23
	WORD $0x4eb38718 // add.4s	v24, v24, v19
	WORD $0x6e38df78 // fmul.4s	v24, v27, v24
	WORD $0x6eb6e696 // fcmgt.4s	v22, v20, v22
	WORD $0x6e781eb7 // bsl.16b	v23, v21, v24
	WORD $0x4e761ef6 // bic.16b	v22, v23, v22
	WORD $0x3c810536 // str	q22, [x9], #16
	WORD $0x4e36d421 // fadd.4s	v1, v1, v22
	WORD $0x9100214b // add	x11, x10, #8
	WORD $0x9100114a // add	x10, x10, #4
	WORD $0xeb08017f // cmp	x11, x8
	BLE  BB0_7
	WORD $0x52800009 // mov	w9, #0                          ; =0x0
	WORD $0x6e21d421 // faddp.4s	v1, v1, v1
	WORD $0x7e30d821 // faddp.2s	s1, v1
	WORD $0xeb0a010b // subs	x11, x8, x10
	BLE  BB0_15

BB0_9:
	WORD $0x5288000c // mov	w12, #16384                     ; =0x4000
	WORD $0x72a8862c // movk	w12, #17457, lsl #16
	WORD $0x1e270182 // fmov	s2, w12
	WORD $0x5288000c // mov	w12, #16384                     ; =0x4000
	WORD $0x72b8862c // movk	w12, #50225, lsl #16
	WORD $0x1e270183 // fmov	s3, w12
	WORD $0xd2905fcc // mov	x12, #33534                     ; =0x82fe
	WORD $0xf2aca56c // movk	x12, #25899, lsl #16
	WORD $0xf2c2a8ec // movk	x12, #5447, lsl #32
	WORD $0xf2e7feec // movk	x12, #16375, lsl #48
	WORD $0x9e670184 // fmov	d4, x12
	WORD $0xd2bfdc0c // mov	x12, #4276092928                ; =0xfee00000
	WORD $0xf2c5c84c // movk	x12, #11842, lsl #32
	WORD $0xf2f7fccc // movk	x12, #49126, lsl #48
	WORD $0x9e670185 // fmov	d5, x12
	WORD $0xd2878d8c // mov	x12, #15468                     ; =0x3c6c
	WORD $0xf2a6af2c // movk	x12, #13689, lsl #16
	WORD $0xf2c73dec // movk	x12, #14831, lsl #32
	WORD $0xf2f7bd4c // movk	x12, #48618, lsl #48
	WORD $0x9e670186 // fmov	d6, x12
	WORD $0xd2889c8c // mov	x12, #17636                     ; =0x44e4
	WORD $0xf2acfeac // movk	x12, #26613, lsl #16
	WORD $0xf2dcc8ac // movk	x12, #58949, lsl #32
	WORD $0xf2e7cb4c // movk	x12, #15962, lsl #48
	WORD $0x9e670187 // fmov	d7, x12
	WORD $0xd29b130c // mov	x12, #55448                     ; =0xd898
	WORD $0xf2bdff0c // movk	x12, #61432, lsl #16
	WORD $0xf2dddb0c // movk	x12, #61144, lsl #32
	WORD $0xf2e7c42c // movk	x12, #15905, lsl #48
	WORD $0x9e670190 // fmov	d16, x12
	WORD $0xd293eb8c // mov	x12, #40796                     ; =0x9f5c
	WORD $0xf2b6ef0c // movk	x12, #46968, lsl #16
	WORD $0xf2cfc9ec // movk	x12, #32335, lsl #32
	WORD $0xf2e7d24c // movk	x12, #16018, lsl #48
	WORD $0x9e670191 // fmov	d17, x12
	WORD $0xd298e68c // mov	x12, #50996                     ; =0xc734
	WORD $0xf2b4aacc // movk	x12, #42326, lsl #16
	WORD $0xf2c3bc6c // movk	x12, #7651, lsl #32
	WORD $0xf2e7d8ec // movk	x12, #16071, lsl #48
	WORD $0x9e670192 // fmov	d18, x12
	WORD $0xd294034c // mov	x12, #40986                     ; =0xa01a
	WORD $0xf2a3402c // movk	x12, #6657, lsl #16
	WORD $0xf2c0340c // movk	x12, #416, lsl #32
	WORD $0xf2e7df4c // movk	x12, #16122, lsl #48
	WORD $0x9e670193 // fmov	d19, x12
	WORD $0xd294034c // mov	x12, #40986                     ; =0xa01a
	WORD $0xf2a3402c // movk	x12, #6657, lsl #16
	WORD $0xf2c0340c // movk	x12, #416, lsl #32
	WORD $0xf2e7e54c // movk	x12, #16170, lsl #48
	WORD $0x9e670194 // fmov	d20, x12
	WORD $0xd28d82ec // mov	x12, #27671                     ; =0x6c17
	WORD $0xf2a2d82c // movk	x12, #5825, lsl #16
	WORD $0xf2d82d8c // movk	x12, #49516, lsl #32
	WORD $0xf2e7eacc // movk	x12, #16214, lsl #48
	WORD $0x9e670195 // fmov	d21, x12
	WORD $0xb200e3ec // mov	x12, #1229782938247303441       ; =0x1111111111111111
	WORD $0xf2e7f02c // movk	x12, #16257, lsl #48
	WORD $0x9e670196 // fmov	d22, x12
	WORD $0xb200f3ec // mov	x12, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f4ac // movk	x12, #16293, lsl #48
	WORD $0x9e670197 // fmov	d23, x12
	WORD $0x1e6c1018 // fmov	d24, #0.50000000
	WORD $0x1e6e1019 // fmov	d25, #1.00000000
	WORD $0xb200f3ec // mov	x12, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f8ac // movk	x12, #16325, lsl #48
	WORD $0x9e67019a // fmov	d26, x12
	WORD $0xd2e7fe0c // mov	x12, #4607182418800017408       ; =0x3ff0000000000000
	WORD $0x8b0a080a // add	x10, x0, x10, lsl #2
	B    BB0_12

BB0_10:
	WORD $0x52aff00d // mov	w13, #2139095040                ; =0x7f800000
	WORD $0x1e2701bb // fmov	s27, w13

BB0_11:
	WORD $0xbc00455b // str	s27, [x10], #4
	WORD $0x1e3b2821 // fadd	s1, s1, s27
	WORD $0xf100056b // subs	x11, x11, #1
	BEQ  BB0_15

BB0_12:
	WORD $0xbd40015b // ldr	s27, [x10]
	WORD $0x1e203b7c // fsub	s28, s27, s0
	WORD $0x1e222380 // fcmp	s28, s2
	BGT  BB0_10
	WORD $0x6f00e41b // movi.2d	v27, #0000000000000000
	WORD $0x1e232380 // fcmp	s28, s3
	BMI  BB0_11
	WORD $0x1e22c39b // fcvt	d27, s28
	WORD $0x1e640b7c // fmul	d28, d27, d4
	WORD $0x1e66439d // frinta	d29, d28
	WORD $0x1f456fbb // fmadd	d27, d29, d5, d27
	WORD $0x1f466fbb // fmadd	d27, d29, d6, d27
	WORD $0x1f501f7d // fmadd	d29, d27, d16, d7
	WORD $0x1f5b47bd // fmadd	d29, d29, d27, d17
	WORD $0x1f5b4bbd // fmadd	d29, d29, d27, d18
	WORD $0x1f5b4fbd // fmadd	d29, d29, d27, d19
	WORD $0x1f5b53bd // fmadd	d29, d29, d27, d20
	WORD $0x1f5b57bd // fmadd	d29, d29, d27, d21
	WORD $0x1f5b5bbd // fmadd	d29, d29, d27, d22
	WORD $0x1f5b5fbd // fmadd	d29, d29, d27, d23
	WORD $0x1f5b6bbd // fmadd	d29, d29, d27, d26
	WORD $0x1f5b63bd // fmadd	d29, d29, d27, d24
	WORD $0x1f5b67bd // fmadd	d29, d29, d27, d25
	WORD $0x1f5b67bb // fmadd	d27, d29, d27, d25
	WORD $0x9e64038d // fcvtas	x13, d28
	WORD $0x8b0dd18d // add	x13, x12, x13, lsl #52
	WORD $0x9e6701bc // fmov	d28, x13
	WORD $0x1e7c0b7b // fmul	d27, d27, d28
	WORD $0x1e62437b // fcvt	s27, d27
	B    BB0_11

BB0_15:
	WORD $0x1e2e1000    // fmov	s0, #1.00000000
	WORD $0x1e211800    // fdiv	s0, s0, s1
	TBZ  $0, R9, BB0_17
	WORD $0xd2800009    // mov	x9, #0                          ; =0x0
	B    BB0_19

BB0_17:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0xaa0003ea // mov	x10, x0

BB0_18:
	WORD $0x3dc00141 // ldr	q1, [x10]
	WORD $0x4f809021 // fmul.4s	v1, v1, v0[0]
	WORD $0x3c810541 // str	q1, [x10], #16
	WORD $0x9100212b // add	x11, x9, #8
	WORD $0x91001129 // add	x9, x9, #4
	WORD $0xeb08017f // cmp	x11, x8
	BLE  BB0_18

BB0_19:
	WORD $0xeb090108 // subs	x8, x8, x9
	BLE  BB0_22
	WORD $0x8b090809 // add	x9, x0, x9, lsl #2

BB0_21:
	WORD $0xbd400121 // ldr	s1, [x9]
	WORD $0x1e210801 // fmul	s1, s0, s1
	WORD $0xbc004521 // str	s1, [x9], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_21

BB0_22:
	RET
