//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8.2-a+fp16+simd -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/nn/asm/basesoftmax_c_f16_neon_arm64.c

TEXT ·softmax_c_f16_neon(SB), $32-24
	MOVD input+0(FP), R0
	MOVD output+8(FP), R1
	MOVD plen_input+16(FP), R2
	WORD $0xf9400048           // ldr	x8, [x2]
	WORD $0xb4002208           // cbz	x8, LBB0_24
	WORD $0xa90057f6           // stp	x22, x21, [sp, #-32]!           ; 16-byte Folded Spill [transformed]
	WORD $0xa9014ff4           // stp	x20, x19, [sp, #16]             ; 16-byte Folded Spill
	WORD $0x7d400000           // ldr	h0, [x0]
	WORD $0x6f00e401           // movi.2d	v1, #0000000000000000
	WORD $0xf100091f           // cmp	x8, #2
	BLT  BB0_5
	WORD $0x52800029           // mov	w9, #1                          ; =0x1

BB0_3:
	WORD $0x7c697802 // ldr	h2, [x0, x9, lsl #1]
	WORD $0x1ee02040 // fcmp	h2, h0
	WORD $0x1ee0cc40 // fcsel	h0, h2, h0, gt
	WORD $0x91000529 // add	x9, x9, #1
	WORD $0xeb09011f // cmp	x8, x9
	BNE  BB0_3
	WORD $0xf100211f // cmp	x8, #8
	BHS  BB0_6

BB0_5:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0x5280002a // mov	w10, #1                         ; =0x1
	B    BB0_9

BB0_6:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0x4e020402 // dup.8h	v2, v0[0]
	WORD $0x528e430a // mov	w10, #29208                     ; =0x7218
	WORD $0x72a8562a // movk	w10, #17073, lsl #16
	WORD $0x4e040d43 // dup.4s	v3, w10
	WORD $0x5295476a // mov	w10, #43579                     ; =0xaa3b
	WORD $0x72a7f70a // movk	w10, #16312, lsl #16
	WORD $0x4e040d44 // dup.4s	v4, w10
	WORD $0x5290000a // mov	w10, #32768                     ; =0x8000
	WORD $0x72a7e62a // movk	w10, #16177, lsl #16
	WORD $0x4e040d45 // dup.4s	v5, w10
	WORD $0x5290106a // mov	w10, #32899                     ; =0x8083
	WORD $0x72a72bca // movk	w10, #14686, lsl #16
	WORD $0x4e040d46 // dup.4s	v6, w10
	WORD $0x52816c2a // mov	w10, #2913                      ; =0xb61
	WORD $0x72a756ca // movk	w10, #15030, lsl #16
	WORD $0x4e040d47 // dup.4s	v7, w10
	WORD $0x5291112a // mov	w10, #34953                     ; =0x8889
	WORD $0x72a7810a // movk	w10, #15368, lsl #16
	WORD $0x4e040d50 // dup.4s	v16, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7a54a // movk	w10, #15658, lsl #16
	WORD $0x4e040d51 // dup.4s	v17, w10
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7c54a // movk	w10, #15914, lsl #16
	WORD $0x4e040d52 // dup.4s	v18, w10
	WORD $0x4f03f613 // fmov.4s	v19, #1.00000000
	WORD $0x52958a0a // mov	w10, #44112                     ; =0xac50
	WORD $0x72b855ca // movk	w10, #49838, lsl #16
	WORD $0x4e040d54 // dup.4s	v20, w10
	WORD $0x6f03d7f5 // mvni.4s	v21, #127, msl #16
	WORD $0x6ea0fab5 // fneg.4s	v21, v21
	WORD $0xaa0103ea // mov	x10, x1
	WORD $0xaa0003eb // mov	x11, x0

BB0_7:
	WORD $0x3cc10576 // ldr	q22, [x11], #16
	WORD $0x4ec216d6 // fsub.8h	v22, v22, v2
	WORD $0x0e217ad7 // fcvtl	v23.4s, v22.4h
	WORD $0x6e1642d6 // ext.16b	v22, v22, v22, #8
	WORD $0x0e217ad6 // fcvtl	v22.4s, v22.4h
	WORD $0x6ea3e6f8 // fcmgt.4s	v24, v23, v3
	WORD $0x6e24def9 // fmul.4s	v25, v23, v4
	WORD $0x4e218b39 // frintn.4s	v25, v25
	WORD $0x6e25df3a // fmul.4s	v26, v25, v5
	WORD $0x4ebad6fa // fsub.4s	v26, v23, v26
	WORD $0x6e26df3b // fmul.4s	v27, v25, v6
	WORD $0x4e3ad77a // fadd.4s	v26, v27, v26
	WORD $0x4eb01e1b // mov.16b	v27, v16
	WORD $0x4e3accfb // fmla.4s	v27, v7, v26
	WORD $0x4eb11e3c // mov.16b	v28, v17
	WORD $0x4e3bcf5c // fmla.4s	v28, v26, v27
	WORD $0x4eb21e5b // mov.16b	v27, v18
	WORD $0x4e3ccf5b // fmla.4s	v27, v26, v28
	WORD $0x4f0167fc // movi.4s	v28, #63, lsl #24
	WORD $0x4eb31e7d // mov.16b	v29, v19
	WORD $0x6e24dede // fmul.4s	v30, v22, v4
	WORD $0x4e218bde // frintn.4s	v30, v30
	WORD $0x6e25dfdf // fmul.4s	v31, v30, v5
	WORD $0x4e3bcf5c // fmla.4s	v28, v26, v27
	WORD $0x4ebfd6db // fsub.4s	v27, v22, v31
	WORD $0x6e26dfdf // fmul.4s	v31, v30, v6
	WORD $0x4e3bd7fb // fadd.4s	v27, v31, v27
	WORD $0x4eb01e1f // mov.16b	v31, v16
	WORD $0x4e3bccff // fmla.4s	v31, v7, v27
	WORD $0x4e3ccf5d // fmla.4s	v29, v26, v28
	WORD $0x4eb11e3c // mov.16b	v28, v17
	WORD $0x4e3fcf7c // fmla.4s	v28, v27, v31
	WORD $0x4eb21e5f // mov.16b	v31, v18
	WORD $0x4e3ccf7f // fmla.4s	v31, v27, v28
	WORD $0x4eb31e7c // mov.16b	v28, v19
	WORD $0x4e3dcf5c // fmla.4s	v28, v26, v29
	WORD $0x4f0167fa // movi.4s	v26, #63, lsl #24
	WORD $0x4e3fcf7a // fmla.4s	v26, v27, v31
	WORD $0x4eb31e7d // mov.16b	v29, v19
	WORD $0x4e3acf7d // fmla.4s	v29, v27, v26
	WORD $0x4eb31e7a // mov.16b	v26, v19
	WORD $0x4e3dcf7a // fmla.4s	v26, v27, v29
	WORD $0x4e21ab39 // fcvtns.4s	v25, v25
	WORD $0x4f375739 // shl.4s	v25, v25, #23
	WORD $0x4eb38739 // add.4s	v25, v25, v19
	WORD $0x6e39df99 // fmul.4s	v25, v28, v25
	WORD $0x6eb7e697 // fcmgt.4s	v23, v20, v23
	WORD $0x6e791eb8 // bsl.16b	v24, v21, v25
	WORD $0x6ea3e6d9 // fcmgt.4s	v25, v22, v3
	WORD $0x4e21abdb // fcvtns.4s	v27, v30
	WORD $0x4f37577b // shl.4s	v27, v27, #23
	WORD $0x4eb3877b // add.4s	v27, v27, v19
	WORD $0x6e3bdf5a // fmul.4s	v26, v26, v27
	WORD $0x4e771f17 // bic.16b	v23, v24, v23
	WORD $0x6eb6e696 // fcmgt.4s	v22, v20, v22
	WORD $0x4eb91f38 // mov.16b	v24, v25
	WORD $0x6e7a1eb8 // bsl.16b	v24, v21, v26
	WORD $0x4e761f16 // bic.16b	v22, v24, v22
	WORD $0x0e216af7 // fcvtn	v23.4h, v23.4s
	WORD $0x4e216ad7 // fcvtn2	v23.8h, v22.4s
	WORD $0x3c810557 // str	q23, [x10], #16
	WORD $0x4e571421 // fadd.8h	v1, v1, v23
	WORD $0x9100412c // add	x12, x9, #16
	WORD $0x91002129 // add	x9, x9, #8
	WORD $0xeb08019f // cmp	x12, x8
	BLE  BB0_7
	WORD $0x5280000a // mov	w10, #0                         ; =0x0

BB0_9:
	WORD $0x0e217822 // fcvtl	v2.4s, v1.4h
	WORD $0x4e217821 // fcvtl2	v1.4s, v1.8h
	WORD $0x4e21d441 // fadd.4s	v1, v2, v1
	WORD $0x6e21d421 // faddp.4s	v1, v1, v1
	WORD $0x7e30d821 // faddp.2s	s1, v1
	WORD $0x1e23c021 // fcvt	h1, s1
	WORD $0xeb09010b // subs	x11, x8, x9
	BLE  BB0_16
	WORD $0xd37ff92c // lsl	x12, x9, #1
	WORD $0x8b0c0029 // add	x9, x1, x12
	WORD $0x1ee24000 // fcvt	s0, h0
	WORD $0x8b0c000c // add	x12, x0, x12
	WORD $0x5288000d // mov	w13, #16384                     ; =0x4000
	WORD $0x72a8862d // movk	w13, #17457, lsl #16
	WORD $0x1e2701a2 // fmov	s2, w13
	WORD $0x5288000d // mov	w13, #16384                     ; =0x4000
	WORD $0x72b8862d // movk	w13, #50225, lsl #16
	WORD $0xd2905fce // mov	x14, #33534                     ; =0x82fe
	WORD $0xf2aca56e // movk	x14, #25899, lsl #16
	WORD $0xf2c2a8ee // movk	x14, #5447, lsl #32
	WORD $0xf2e7feee // movk	x14, #16375, lsl #48
	WORD $0xd2bfdc0f // mov	x15, #4276092928                ; =0xfee00000
	WORD $0xf2c5c84f // movk	x15, #11842, lsl #32
	WORD $0xf2f7fccf // movk	x15, #49126, lsl #48
	WORD $0xd2878d90 // mov	x16, #15468                     ; =0x3c6c
	WORD $0xf2a6af30 // movk	x16, #13689, lsl #16
	WORD $0xf2c73df0 // movk	x16, #14831, lsl #32
	WORD $0xf2f7bd50 // movk	x16, #48618, lsl #48
	WORD $0xd2889c91 // mov	x17, #17636                     ; =0x44e4
	WORD $0xf2acfeb1 // movk	x17, #26613, lsl #16
	WORD $0xf2dcc8b1 // movk	x17, #58949, lsl #32
	WORD $0xf2e7cb51 // movk	x17, #15962, lsl #48
	WORD $0xd29b1300 // mov	x0, #55448                      ; =0xd898
	WORD $0xf2bdff00 // movk	x0, #61432, lsl #16
	WORD $0xf2dddb00 // movk	x0, #61144, lsl #32
	WORD $0xf2e7c420 // movk	x0, #15905, lsl #48
	WORD $0xd293eb82 // mov	x2, #40796                      ; =0x9f5c
	WORD $0xf2b6ef02 // movk	x2, #46968, lsl #16
	WORD $0xf2cfc9e2 // movk	x2, #32335, lsl #32
	WORD $0xf2e7d242 // movk	x2, #16018, lsl #48
	WORD $0xd298e683 // mov	x3, #50996                      ; =0xc734
	WORD $0xf2b4aac3 // movk	x3, #42326, lsl #16
	WORD $0xf2c3bc63 // movk	x3, #7651, lsl #32
	WORD $0xf2e7d8e3 // movk	x3, #16071, lsl #48
	WORD $0xd2940344 // mov	x4, #40986                      ; =0xa01a
	WORD $0xf2a34024 // movk	x4, #6657, lsl #16
	WORD $0xf2c03404 // movk	x4, #416, lsl #32
	WORD $0xf2e7df44 // movk	x4, #16122, lsl #48
	WORD $0xd2940345 // mov	x5, #40986                      ; =0xa01a
	WORD $0xf2a34025 // movk	x5, #6657, lsl #16
	WORD $0xf2c03405 // movk	x5, #416, lsl #32
	WORD $0xf2e7e545 // movk	x5, #16170, lsl #48
	WORD $0xd28d82e6 // mov	x6, #27671                      ; =0x6c17
	WORD $0xf2a2d826 // movk	x6, #5825, lsl #16
	WORD $0xf2d82d86 // movk	x6, #49516, lsl #32
	WORD $0xf2e7eac6 // movk	x6, #16214, lsl #48
	WORD $0xb200e3e7 // mov	x7, #1229782938247303441        ; =0x1111111111111111
	WORD $0xf2e7f027 // movk	x7, #16257, lsl #48
	WORD $0xb200f3f3 // mov	x19, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f4b3 // movk	x19, #16293, lsl #48
	WORD $0x1e6c1003 // fmov	d3, #0.50000000
	WORD $0xb200f3f4 // mov	x20, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f8b4 // movk	x20, #16325, lsl #48
	WORD $0x1e6e1004 // fmov	d4, #1.00000000
	WORD $0xd2e7fe15 // mov	x21, #4607182418800017408       ; =0x3ff0000000000000
	B    BB0_13

BB0_11:
	WORD $0x52800016 // mov	w22, #0                         ; =0x0

BB0_12:
	WORD $0x12003ed6 // and	w22, w22, #0xffff
	WORD $0x1ee302c5 // ucvtf	h5, w22
	WORD $0x7c002525 // str	h5, [x9], #2
	WORD $0x1e2302c5 // ucvtf	s5, w22
	WORD $0x1ee24021 // fcvt	s1, h1
	WORD $0x1e252821 // fadd	s1, s1, s5
	WORD $0x1e23c021 // fcvt	h1, s1
	WORD $0xf100056b // subs	x11, x11, #1
	BEQ  BB0_16

BB0_13:
	WORD $0x7c402585 // ldr	h5, [x12], #2
	WORD $0x1ee240a5 // fcvt	s5, h5
	WORD $0x1e2038a5 // fsub	s5, s5, s0
	WORD $0x1e2220a0 // fcmp	s5, s2
	BGT  BB0_12
	WORD $0x1e2701a6 // fmov	s6, w13
	WORD $0x1e2620a0 // fcmp	s5, s6
	BMI  BB0_11
	WORD $0x1e22c0a5 // fcvt	d5, s5
	WORD $0x9e6701c6 // fmov	d6, x14
	WORD $0x1e6608a6 // fmul	d6, d5, d6
	WORD $0x1e6640c7 // frinta	d7, d6
	WORD $0x9e6701f0 // fmov	d16, x15
	WORD $0x1f5014e5 // fmadd	d5, d7, d16, d5
	WORD $0x9e670210 // fmov	d16, x16
	WORD $0x1f5014e5 // fmadd	d5, d7, d16, d5
	WORD $0x9e670227 // fmov	d7, x17
	WORD $0x9e670010 // fmov	d16, x0
	WORD $0x1f501ca7 // fmadd	d7, d5, d16, d7
	WORD $0x9e670050 // fmov	d16, x2
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x9e670070 // fmov	d16, x3
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x9e670090 // fmov	d16, x4
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x9e6700b0 // fmov	d16, x5
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x9e6700d0 // fmov	d16, x6
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x9e6700f0 // fmov	d16, x7
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x9e670270 // fmov	d16, x19
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x9e670290 // fmov	d16, x20
	WORD $0x1f4540e7 // fmadd	d7, d7, d5, d16
	WORD $0x1f450ce7 // fmadd	d7, d7, d5, d3
	WORD $0x1f4510e7 // fmadd	d7, d7, d5, d4
	WORD $0x9e6400d6 // fcvtas	x22, d6
	WORD $0x1f4510e5 // fmadd	d5, d7, d5, d4
	WORD $0x8b16d2b6 // add	x22, x21, x22, lsl #52
	WORD $0x9e6702c6 // fmov	d6, x22
	WORD $0x1e6608a5 // fmul	d5, d5, d6
	WORD $0x1e7800b6 // fcvtzs	w22, d5
	B    BB0_12

BB0_16:
	WORD $0x1ee24020 // fcvt	s0, h1
	WORD $0x1e2e1001 // fmov	s1, #1.00000000
	WORD $0x1e201820 // fdiv	s0, s1, s0
	WORD $0x1e380009 // fcvtzs	w9, s0
	WORD $0x3600006a // tbz	w10, #0, LBB0_18
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	B    BB0_20

BB0_18:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0x1ee30120 // ucvtf	h0, w9
	WORD $0xaa0103ec // mov	x12, x1

BB0_19:
	WORD $0x3dc00181 // ldr	q1, [x12]
	WORD $0x4f009021 // fmul.8h	v1, v1, v0[0]
	WORD $0x3c810581 // str	q1, [x12], #16
	WORD $0x9100214b // add	x11, x10, #8
	WORD $0x9100414d // add	x13, x10, #16
	WORD $0xaa0b03ea // mov	x10, x11
	WORD $0xeb0801bf // cmp	x13, x8
	BLE  BB0_19

BB0_20:
	WORD $0xeb0b0108 // subs	x8, x8, x11
	BLE  BB0_23
	WORD $0x1e230120 // ucvtf	s0, w9
	WORD $0x8b0b0429 // add	x9, x1, x11, lsl #1

BB0_22:
	WORD $0x7d400121 // ldr	h1, [x9]
	WORD $0x1ee24021 // fcvt	s1, h1
	WORD $0x1e210801 // fmul	s1, s0, s1
	WORD $0x1e23c021 // fcvt	h1, s1
	WORD $0x7c002521 // str	h1, [x9], #2
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_22

BB0_23:
	WORD $0xa9414ff4 // ldp	x20, x19, [sp, #16]             ; 16-byte Folded Reload
	WORD $0xa94057f6 // ldp	x22, x21, [sp], #32             ; 16-byte Folded Reload [transformed]

BB0_24:
	RET
