//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   22.1.8
// 	objdump 2.46.1 (llvm-objdump 22.1.8)
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/nn/asm/baseattentionweights_c_f64_neon_arm64.c

package asm

import "unsafe"

//go:noescape
func attentionweights_c_f64_neon(q, k, mask, weights, pseqLen, pkvLen, pheadDim, pscale, plen_q, plen_k, plen_mask, plen_weights unsafe.Pointer)
