//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8.2-a+fp16+simd -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/nn/asm/baselogsoftmax_c_f16_neon_arm64.c

TEXT ·logsoftmax_c_f16_neon(SB), $32-24
	MOVD input+0(FP), R0
	MOVD output+8(FP), R1
	MOVD plen_input+16(FP), R2
	WORD $0xf9400048           // ldr	x8, [x2]
	WORD $0xb40024e8           // cbz	x8, LBB0_25
	WORD $0xa90057f6           // stp	x22, x21, [sp, #-32]!           ; 16-byte Folded Spill [transformed]
	WORD $0xa9014ff4           // stp	x20, x19, [sp, #16]             ; 16-byte Folded Spill
	WORD $0x7d400001           // ldr	h1, [x0]
	WORD $0xf100091f           // cmp	x8, #2
	BLT  BB0_6
	WORD $0x52800029           // mov	w9, #1                          ; =0x1

BB0_3:
	WORD $0x7c697800 // ldr	h0, [x0, x9, lsl #1]
	WORD $0x1ee12000 // fcmp	h0, h1
	WORD $0x1ee1cc01 // fcsel	h1, h0, h1, gt
	WORD $0x91000529 // add	x9, x9, #1
	WORD $0xeb09011f // cmp	x8, x9
	BNE  BB0_3
	WORD $0x4e020420 // dup.8h	v0, v1[0]
	WORD $0xf100211f // cmp	x8, #8
	BHS  BB0_8
	WORD $0xd2800007 // mov	x7, #0                          ; =0x0
	B    BB0_7

BB0_6:
	WORD $0xd2800007 // mov	x7, #0                          ; =0x0
	WORD $0x4e020420 // dup.8h	v0, v1[0]

BB0_7:
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0x52800029 // mov	w9, #1                          ; =0x1
	B    BB0_11

BB0_8:
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0x52800109 // mov	w9, #8                          ; =0x8
	WORD $0x528e430a // mov	w10, #29208                     ; =0x7218
	WORD $0x72a8562a // movk	w10, #17073, lsl #16
	WORD $0x4e040d43 // dup.4s	v3, w10
	WORD $0x5295476a // mov	w10, #43579                     ; =0xaa3b
	WORD $0x72a7f70a // movk	w10, #16312, lsl #16
	WORD $0x4e040d44 // dup.4s	v4, w10
	WORD $0x5290000a // mov	w10, #32768                     ; =0x8000
	WORD $0x72b7e62a // movk	w10, #48945, lsl #16
	WORD $0x4e040d45 // dup.4s	v5, w10
	WORD $0x5290106a // mov	w10, #32899                     ; =0x8083
	WORD $0x72a72bca // movk	w10, #14686, lsl #16
	WORD $0x4e040d46 // dup.4s	v6, w10
	WORD $0x52816c2a // mov	w10, #2913                      ; =0xb61
	WORD $0x72a756ca // movk	w10, #15030, lsl #16
	WORD $0x4e040d47 // dup.4s	v7, w10
	WORD $0x5291112a // mov	w10, #34953                     ; =0x8889
	WORD $0x72a7810a // movk	w10, #15368, lsl #16
	WORD $0x4e040d50 // dup.4s	v16, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7a54a // movk	w10, #15658, lsl #16
	WORD $0x4e040d51 // dup.4s	v17, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7c54a // movk	w10, #15914, lsl #16
	WORD $0x4e040d52 // dup.4s	v18, w10
	WORD $0x4f03f613 // fmov.4s	v19, #1.00000000
	WORD $0x52958a0a // mov	w10, #44112                     ; =0xac50
	WORD $0x72b855ca // movk	w10, #49838, lsl #16
	WORD $0x4e040d54 // dup.4s	v20, w10
	WORD $0x6f03d7f5 // mvni.4s	v21, #127, msl #16
	WORD $0x6ea0fab5 // fneg.4s	v21, v21
	WORD $0xaa0003ea // mov	x10, x0

BB0_9:
	WORD $0x3cc10556 // ldr	q22, [x10], #16
	WORD $0x4ec016d6 // fsub.8h	v22, v22, v0
	WORD $0x6e24ded7 // fmul.4s	v23, v22, v4
	WORD $0x4e218af7 // frintn.4s	v23, v23
	WORD $0x6e25def8 // fmul.4s	v24, v23, v5
	WORD $0x4e38d6d8 // fadd.4s	v24, v22, v24
	WORD $0x6e26def9 // fmul.4s	v25, v23, v6
	WORD $0x4e38d738 // fadd.4s	v24, v25, v24
	WORD $0x4eb01e19 // mov.16b	v25, v16
	WORD $0x4e38ccf9 // fmla.4s	v25, v7, v24
	WORD $0x4eb11e3a // mov.16b	v26, v17
	WORD $0x4e39cf1a // fmla.4s	v26, v24, v25
	WORD $0x4eb21e59 // mov.16b	v25, v18
	WORD $0x4e3acf19 // fmla.4s	v25, v24, v26
	WORD $0x4f0167fa // movi.4s	v26, #63, lsl #24
	WORD $0x4e39cf1a // fmla.4s	v26, v24, v25
	WORD $0x4eb31e79 // mov.16b	v25, v19
	WORD $0x4e3acf19 // fmla.4s	v25, v24, v26
	WORD $0x6ea3e6da // fcmgt.4s	v26, v22, v3
	WORD $0x4eb31e7b // mov.16b	v27, v19
	WORD $0x4e39cf1b // fmla.4s	v27, v24, v25
	WORD $0x4e21aaf7 // fcvtns.4s	v23, v23
	WORD $0x4f3756f7 // shl.4s	v23, v23, #23
	WORD $0x4eb386f7 // add.4s	v23, v23, v19
	WORD $0x6e37df77 // fmul.4s	v23, v27, v23
	WORD $0x6eb6e696 // fcmgt.4s	v22, v20, v22
	WORD $0x6eba1eb7 // bit.16b	v23, v21, v26
	WORD $0x4e761ef6 // bic.16b	v22, v23, v22
	WORD $0x4e561442 // fadd.8h	v2, v2, v22
	WORD $0x91002129 // add	x9, x9, #8
	WORD $0xeb08013f // cmp	x9, x8
	BLE  BB0_9
	WORD $0x52800009 // mov	w9, #0                          ; =0x0
	WORD $0x927ded07 // and	x7, x8, #0x7ffffffffffffff8

BB0_11:
	WORD $0x0e217843 // fcvtl	v3.4s, v2.4h
	WORD $0x4e217842 // fcvtl2	v2.4s, v2.8h
	WORD $0x4e22d462 // fadd.4s	v2, v3, v2
	WORD $0x6e22d442 // faddp.4s	v2, v2, v2
	WORD $0x7e30d842 // faddp.2s	s2, v2
	WORD $0x1e23c042 // fcvt	h2, s2
	WORD $0x1ee24021 // fcvt	s1, h1
	WORD $0xeb07010a // subs	x10, x8, x7
	BLE  BB0_17
	WORD $0x5288000b // mov	w11, #16384                     ; =0x4000
	WORD $0x72a8862b // movk	w11, #17457, lsl #16
	WORD $0x1e270163 // fmov	s3, w11
	WORD $0x5288000b // mov	w11, #16384                     ; =0x4000
	WORD $0x72b8862b // movk	w11, #50225, lsl #16
	WORD $0xd2905fcc // mov	x12, #33534                     ; =0x82fe
	WORD $0xf2aca56c // movk	x12, #25899, lsl #16
	WORD $0xf2c2a8ec // movk	x12, #5447, lsl #32
	WORD $0xf2e7feec // movk	x12, #16375, lsl #48
	WORD $0xd2bfdc0d // mov	x13, #4276092928                ; =0xfee00000
	WORD $0xf2c5c84d // movk	x13, #11842, lsl #32
	WORD $0xf2f7fccd // movk	x13, #49126, lsl #48
	WORD $0xd2878d8e // mov	x14, #15468                     ; =0x3c6c
	WORD $0xf2a6af2e // movk	x14, #13689, lsl #16
	WORD $0xf2c73dee // movk	x14, #14831, lsl #32
	WORD $0xf2f7bd4e // movk	x14, #48618, lsl #48
	WORD $0xd2889c8f // mov	x15, #17636                     ; =0x44e4
	WORD $0xf2acfeaf // movk	x15, #26613, lsl #16
	WORD $0xf2dcc8af // movk	x15, #58949, lsl #32
	WORD $0xf2e7cb4f // movk	x15, #15962, lsl #48
	WORD $0xd29b1310 // mov	x16, #55448                     ; =0xd898
	WORD $0xf2bdff10 // movk	x16, #61432, lsl #16
	WORD $0xf2dddb10 // movk	x16, #61144, lsl #32
	WORD $0xf2e7c430 // movk	x16, #15905, lsl #48
	WORD $0xd293eb91 // mov	x17, #40796                     ; =0x9f5c
	WORD $0xf2b6ef11 // movk	x17, #46968, lsl #16
	WORD $0xf2cfc9f1 // movk	x17, #32335, lsl #32
	WORD $0xf2e7d251 // movk	x17, #16018, lsl #48
	WORD $0xd298e682 // mov	x2, #50996                      ; =0xc734
	WORD $0xf2b4aac2 // movk	x2, #42326, lsl #16
	WORD $0xf2c3bc62 // movk	x2, #7651, lsl #32
	WORD $0xf2e7d8e2 // movk	x2, #16071, lsl #48
	WORD $0xd2940343 // mov	x3, #40986                      ; =0xa01a
	WORD $0xf2a34023 // movk	x3, #6657, lsl #16
	WORD $0xf2c03403 // movk	x3, #416, lsl #32
	WORD $0xf2e7df43 // movk	x3, #16122, lsl #48
	WORD $0xd2940344 // mov	x4, #40986                      ; =0xa01a
	WORD $0xf2a34024 // movk	x4, #6657, lsl #16
	WORD $0xf2c03404 // movk	x4, #416, lsl #32
	WORD $0xf2e7e544 // movk	x4, #16170, lsl #48
	WORD $0xd28d82e5 // mov	x5, #27671                      ; =0x6c17
	WORD $0xf2a2d825 // movk	x5, #5825, lsl #16
	WORD $0xf2d82d85 // movk	x5, #49516, lsl #32
	WORD $0xf2e7eac5 // movk	x5, #16214, lsl #48
	WORD $0xb200e3e6 // mov	x6, #1229782938247303441        ; =0x1111111111111111
	WORD $0xf2e7f026 // movk	x6, #16257, lsl #48
	WORD $0x1e6c1004 // fmov	d4, #0.50000000
	WORD $0x1e6e1005 // fmov	d5, #1.00000000
	WORD $0xb200f3f3 // mov	x19, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f4b3 // movk	x19, #16293, lsl #48
	WORD $0xb200f3f4 // mov	x20, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f8b4 // movk	x20, #16325, lsl #48
	WORD $0xd2e7fe15 // mov	x21, #4607182418800017408       ; =0x3ff0000000000000
	WORD $0x8b070407 // add	x7, x0, x7, lsl #1
	B    BB0_14

BB0_13:
	WORD $0x1ee24042 // fcvt	s2, h2
	WORD $0x1e2228c2 // fadd	s2, s6, s2
	WORD $0x1e23c042 // fcvt	h2, s2
	WORD $0xf100054a // subs	x10, x10, #1
	BEQ  BB0_17

BB0_14:
	WORD $0x7c4024e6 // ldr	h6, [x7], #2
	WORD $0x1ee240c6 // fcvt	s6, h6
	WORD $0x1e2138c7 // fsub	s7, s6, s1
	WORD $0x1e2320e0 // fcmp	s7, s3
	BGT  BB0_13
	WORD $0x2f00e406 // movi	d6, #0000000000000000
	WORD $0x1e270170 // fmov	s16, w11
	WORD $0x1e3020e0 // fcmp	s7, s16
	BMI  BB0_13
	WORD $0x1e22c0e6 // fcvt	d6, s7
	WORD $0x9e670187 // fmov	d7, x12
	WORD $0x1e6708c7 // fmul	d7, d6, d7
	WORD $0x1e6640f0 // frinta	d16, d7
	WORD $0x9e6701b1 // fmov	d17, x13
	WORD $0x1f511a06 // fmadd	d6, d16, d17, d6
	WORD $0x9e6701d1 // fmov	d17, x14
	WORD $0x1f511a06 // fmadd	d6, d16, d17, d6
	WORD $0x9e6701f0 // fmov	d16, x15
	WORD $0x9e670211 // fmov	d17, x16
	WORD $0x1f5140d0 // fmadd	d16, d6, d17, d16
	WORD $0x9e670231 // fmov	d17, x17
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x9e670051 // fmov	d17, x2
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x9e670071 // fmov	d17, x3
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x9e670091 // fmov	d17, x4
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x9e6700b1 // fmov	d17, x5
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x9e6700d1 // fmov	d17, x6
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x9e670271 // fmov	d17, x19
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x9e670291 // fmov	d17, x20
	WORD $0x1f464610 // fmadd	d16, d16, d6, d17
	WORD $0x1f461210 // fmadd	d16, d16, d6, d4
	WORD $0x1f461610 // fmadd	d16, d16, d6, d5
	WORD $0x1f461606 // fmadd	d6, d16, d6, d5
	WORD $0x9e6400f6 // fcvtas	x22, d7
	WORD $0x8b16d2b6 // add	x22, x21, x22, lsl #52
	WORD $0x9e6702c7 // fmov	d7, x22
	WORD $0x1e6708c6 // fmul	d6, d6, d7
	WORD $0x1e7800d6 // fcvtzs	w22, d6
	WORD $0x1e2302c6 // ucvtf	s6, w22
	B    BB0_13

BB0_17:
	WORD $0x1ee2c042 // fcvt	d2, h2
	WORD $0x9e66004a // fmov	x10, d2
	WORD $0xd374f94b // ubfx	x11, x10, #52, #11
	WORD $0xd10ffd6b // sub	x11, x11, #1023
	WORD $0x9e620162 // scvtf	d2, x11
	WORD $0xd2e7fe0b // mov	x11, #4607182418800017408       ; =0x3ff0000000000000
	WORD $0xb340cd4b // bfxil	x11, x10, #0, #52
	WORD $0x9e670163 // fmov	d3, x11
	WORD $0x1e7e1004 // fmov	d4, #-1.00000000
	WORD $0x1e642863 // fadd	d3, d3, d4
	WORD $0xd289634a // mov	x10, #19226                     ; =0x4b1a
	WORD $0xf2a4ce4a // movk	x10, #9842, lsl #16
	WORD $0xf2de290a // movk	x10, #61768, lsl #32
	WORD $0xf2f7f8ca // movk	x10, #49094, lsl #48
	WORD $0x9e670144 // fmov	d4, x10
	WORD $0xd2819faa // mov	x10, #3325                      ; =0xcfd
	WORD $0xf2bd3e4a // movk	x10, #59890, lsl #16
	WORD $0xf2c02bea // movk	x10, #351, lsl #32
	WORD $0xf2e7f86a // movk	x10, #16323, lsl #48
	WORD $0x9e670145 // fmov	d5, x10
	WORD $0x1f451064 // fmadd	d4, d3, d5, d4
	WORD $0xd29ea90a // mov	x10, #62792                     ; =0xf548
	WORD $0xf2b5748a // movk	x10, #43940, lsl #16
	WORD $0xf2c9f6ea // movk	x10, #20407, lsl #32
	WORD $0xf2e7f98a // movk	x10, #16332, lsl #48
	WORD $0x9e670145 // fmov	d5, x10
	WORD $0x1f431484 // fmadd	d4, d4, d3, d5
	WORD $0xd286e9ca // mov	x10, #14158                     ; =0x374e
	WORD $0xf2b248aa // movk	x10, #37445, lsl #16
	WORD $0xf2c9248a // movk	x10, #18724, lsl #32
	WORD $0xf2f7fa4a // movk	x10, #49106, lsl #48
	WORD $0x9e670145 // fmov	d5, x10
	WORD $0x1f431484 // fmadd	d4, d4, d3, d5
	WORD $0xd283974a // mov	x10, #7354                      ; =0x1cba
	WORD $0xf2b32fca // movk	x10, #39294, lsl #16
	WORD $0xf2d3332a // movk	x10, #39321, lsl #32
	WORD $0xf2e7fb2a // movk	x10, #16345, lsl #48
	WORD $0x9e670145 // fmov	d5, x10
	WORD $0x1f431484 // fmadd	d4, d4, d3, d5
	WORD $0x928f9bea // mov	x10, #-31968                    ; =0xffffffffffff8320
	WORD $0xf2bffc8a // movk	x10, #65508, lsl #16
	WORD $0xf2f7fbea // movk	x10, #49119, lsl #48
	WORD $0x9e670145 // fmov	d5, x10
	WORD $0x1f431484 // fmadd	d4, d4, d3, d5
	WORD $0x9297cdea // mov	x10, #-48752                    ; =0xffffffffffff4190
	WORD $0xf2bffe4a // movk	x10, #65522, lsl #16
	WORD $0xf2e7fdea // movk	x10, #16367, lsl #48
	WORD $0x9e670145 // fmov	d5, x10
	WORD $0x1f431484 // fmadd	d4, d4, d3, d5
	WORD $0x1e640863 // fmul	d3, d3, d4
	WORD $0xd2873dea // mov	x10, #14831                     ; =0x39ef
	WORD $0xf2bfdf4a // movk	x10, #65274, lsl #16
	WORD $0xf2c5c84a // movk	x10, #11842, lsl #32
	WORD $0xf2e7fcca // movk	x10, #16358, lsl #48
	WORD $0x9e670144 // fmov	d4, x10
	WORD $0x1f440c42 // fmadd	d2, d2, d4, d3
	WORD $0x1e78004a // fcvtzs	w10, d2
	WORD $0x36000069 // tbz	w9, #0, LBB0_19
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	B    BB0_21

BB0_19:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0x1ee30142 // ucvtf	h2, w10
	WORD $0x4e020442 // dup.8h	v2, v2[0]
	WORD $0xaa0103eb // mov	x11, x1
	WORD $0xaa0003ec // mov	x12, x0

BB0_20:
	WORD $0x3cc10583 // ldr	q3, [x12], #16
	WORD $0x4ec01463 // fsub.8h	v3, v3, v0
	WORD $0x4ec21463 // fsub.8h	v3, v3, v2
	WORD $0x3c810563 // str	q3, [x11], #16
	WORD $0x9100212d // add	x13, x9, #8
	WORD $0x9100412e // add	x14, x9, #16
	WORD $0xaa0d03e9 // mov	x9, x13
	WORD $0xeb0801df // cmp	x14, x8
	BLE  BB0_20

BB0_21:
	WORD $0xeb0d0108 // subs	x8, x8, x13
	BLE  BB0_24
	WORD $0x1e230140 // ucvtf	s0, w10
	WORD $0xd37ff9aa // lsl	x10, x13, #1
	WORD $0x8b0a0029 // add	x9, x1, x10
	WORD $0x8b0a000a // add	x10, x0, x10

BB0_23:
	WORD $0x7c402542 // ldr	h2, [x10], #2
	WORD $0x1ee24042 // fcvt	s2, h2
	WORD $0x1e213842 // fsub	s2, s2, s1
	WORD $0x1e203842 // fsub	s2, s2, s0
	WORD $0x1e23c042 // fcvt	h2, s2
	WORD $0x7c002522 // str	h2, [x9], #2
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_23

BB0_24:
	WORD $0xa9414ff4 // ldp	x20, x19, [sp, #16]             ; 16-byte Folded Reload
	WORD $0xa94057f6 // ldp	x22, x21, [sp], #32             ; 16-byte Folded Reload [transformed]

BB0_25:
	RET
