//go:build !noasm && arm64
// Code generated by hwygen -c. DO NOT EDIT.

package asm

import "unsafe"

// SDPA_F16 calls the NEON SIMD assembly implementation.
func SDPA_F16(q unsafe.Pointer, k unsafe.Pointer, v unsafe.Pointer, mask unsafe.Pointer, scores unsafe.Pointer, output unsafe.Pointer, pseqLen unsafe.Pointer, pkvLen unsafe.Pointer, pheadDim unsafe.Pointer, pscale unsafe.Pointer, plen_q unsafe.Pointer, plen_k unsafe.Pointer, plen_v unsafe.Pointer, plen_mask unsafe.Pointer, plen_scores unsafe.Pointer, plen_output unsafe.Pointer) {
	sdpa_c_f16_neon(q, k, v, mask, scores, output, pseqLen, pkvLen, pheadDim, pscale, plen_q, plen_k, plen_v, plen_mask, plen_scores, plen_output)
}

// SDPA_BF16 calls the NEON SIMD assembly implementation.
func SDPA_BF16(q unsafe.Pointer, k unsafe.Pointer, v unsafe.Pointer, mask unsafe.Pointer, scores unsafe.Pointer, output unsafe.Pointer, pseqLen unsafe.Pointer, pkvLen unsafe.Pointer, pheadDim unsafe.Pointer, pscale unsafe.Pointer, plen_q unsafe.Pointer, plen_k unsafe.Pointer, plen_v unsafe.Pointer, plen_mask unsafe.Pointer, plen_scores unsafe.Pointer, plen_output unsafe.Pointer) {
	sdpa_c_bf16_neon(q, k, v, mask, scores, output, pseqLen, pkvLen, pheadDim, pscale, plen_q, plen_k, plen_v, plen_mask, plen_scores, plen_output)
}

// SDPA_F32 calls the NEON SIMD assembly implementation.
func SDPA_F32(q unsafe.Pointer, k unsafe.Pointer, v unsafe.Pointer, mask unsafe.Pointer, scores unsafe.Pointer, output unsafe.Pointer, pseqLen unsafe.Pointer, pkvLen unsafe.Pointer, pheadDim unsafe.Pointer, pscale unsafe.Pointer, plen_q unsafe.Pointer, plen_k unsafe.Pointer, plen_v unsafe.Pointer, plen_mask unsafe.Pointer, plen_scores unsafe.Pointer, plen_output unsafe.Pointer) {
	sdpa_c_f32_neon(q, k, v, mask, scores, output, pseqLen, pkvLen, pheadDim, pscale, plen_q, plen_k, plen_v, plen_mask, plen_scores, plen_output)
}

// SDPA_F64 calls the NEON SIMD assembly implementation.
func SDPA_F64(q unsafe.Pointer, k unsafe.Pointer, v unsafe.Pointer, mask unsafe.Pointer, scores unsafe.Pointer, output unsafe.Pointer, pseqLen unsafe.Pointer, pkvLen unsafe.Pointer, pheadDim unsafe.Pointer, pscale unsafe.Pointer, plen_q unsafe.Pointer, plen_k unsafe.Pointer, plen_v unsafe.Pointer, plen_mask unsafe.Pointer, plen_scores unsafe.Pointer, plen_output unsafe.Pointer) {
	sdpa_c_f64_neon(q, k, v, mask, scores, output, pseqLen, pkvLen, pheadDim, pscale, plen_q, plen_k, plen_v, plen_mask, plen_scores, plen_output)
}

// SDPACausal_F16 calls the NEON SIMD assembly implementation.
func SDPACausal_F16(q unsafe.Pointer, k unsafe.Pointer, v unsafe.Pointer, scores unsafe.Pointer, output unsafe.Pointer, pseqLen unsafe.Pointer, pkvLen unsafe.Pointer, pheadDim unsafe.Pointer, pscale unsafe.Pointer, plen_q unsafe.Pointer, plen_k unsafe.Pointer, plen_v unsafe.Pointer, plen_scores unsafe.Pointer, plen_output unsafe.Pointer) {
	sdpacausal_c_f16_neon(q, k, v, scores, output, pseqLen, pkvLen, pheadDim, pscale, plen_q, plen_k, plen_v, plen_scores, plen_output)
}

// SDPACausal_BF16 calls the NEON SIMD assembly implementation.
func SDPACausal_BF16(q unsafe.Pointer, k unsafe.Pointer, v unsafe.Pointer, scores unsafe.Pointer, output unsafe.Pointer, pseqLen unsafe.Pointer, pkvLen unsafe.Pointer, pheadDim unsafe.Pointer, pscale unsafe.Pointer, plen_q unsafe.Pointer, plen_k unsafe.Pointer, plen_v unsafe.Pointer, plen_scores unsafe.Pointer, plen_output unsafe.Pointer) {
	sdpacausal_c_bf16_neon(q, k, v, scores, output, pseqLen, pkvLen, pheadDim, pscale, plen_q, plen_k, plen_v, plen_scores, plen_output)
}

// SDPACausal_F32 calls the NEON SIMD assembly implementation.
func SDPACausal_F32(q unsafe.Pointer, k unsafe.Pointer, v unsafe.Pointer, scores unsafe.Pointer, output unsafe.Pointer, pseqLen unsafe.Pointer, pkvLen unsafe.Pointer, pheadDim unsafe.Pointer, pscale unsafe.Pointer, plen_q unsafe.Pointer, plen_k unsafe.Pointer, plen_v unsafe.Pointer, plen_scores unsafe.Pointer, plen_output unsafe.Pointer) {
	sdpacausal_c_f32_neon(q, k, v, scores, output, pseqLen, pkvLen, pheadDim, pscale, plen_q, plen_k, plen_v, plen_scores, plen_output)
}

// SDPACausal_F64 calls the NEON SIMD assembly implementation.
func SDPACausal_F64(q unsafe.Pointer, k unsafe.Pointer, v unsafe.Pointer, scores unsafe.Pointer, output unsafe.Pointer, pseqLen unsafe.Pointer, pkvLen unsafe.Pointer, pheadDim unsafe.Pointer, pscale unsafe.Pointer, plen_q unsafe.Pointer, plen_k unsafe.Pointer, plen_v unsafe.Pointer, plen_scores unsafe.Pointer, plen_output unsafe.Pointer) {
	sdpacausal_c_f64_neon(q, k, v, scores, output, pseqLen, pkvLen, pheadDim, pscale, plen_q, plen_k, plen_v, plen_scores, plen_output)
}

