//go:build !noasm && arm64
// Code generated by hwygen -c. DO NOT EDIT.

package asm

import "unsafe"

// Softmax_F16 calls the NEON SIMD assembly implementation.
func Softmax_F16(input unsafe.Pointer, output unsafe.Pointer, plen unsafe.Pointer) {
	softmax_c_f16_neon(input, output, plen)
}

// Softmax_BF16 calls the NEON SIMD assembly implementation.
func Softmax_BF16(input unsafe.Pointer, output unsafe.Pointer, plen unsafe.Pointer) {
	softmax_c_bf16_neon(input, output, plen)
}

// Softmax_F32 calls the NEON SIMD assembly implementation.
func Softmax_F32(input unsafe.Pointer, output unsafe.Pointer, plen unsafe.Pointer) {
	softmax_c_f32_neon(input, output, plen)
}

// Softmax_F64 calls the NEON SIMD assembly implementation.
func Softmax_F64(input unsafe.Pointer, output unsafe.Pointer, plen unsafe.Pointer) {
	softmax_c_f64_neon(input, output, plen)
}

// LogSoftmax_F16 calls the NEON SIMD assembly implementation.
func LogSoftmax_F16(input unsafe.Pointer, output unsafe.Pointer, plen unsafe.Pointer) {
	logsoftmax_c_f16_neon(input, output, plen)
}

// LogSoftmax_BF16 calls the NEON SIMD assembly implementation.
func LogSoftmax_BF16(input unsafe.Pointer, output unsafe.Pointer, plen unsafe.Pointer) {
	logsoftmax_c_bf16_neon(input, output, plen)
}

// LogSoftmax_F32 calls the NEON SIMD assembly implementation.
func LogSoftmax_F32(input unsafe.Pointer, output unsafe.Pointer, plen unsafe.Pointer) {
	logsoftmax_c_f32_neon(input, output, plen)
}

// LogSoftmax_F64 calls the NEON SIMD assembly implementation.
func LogSoftmax_F64(input unsafe.Pointer, output unsafe.Pointer, plen unsafe.Pointer) {
	logsoftmax_c_f64_neon(input, output, plen)
}

