//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8.2-a+fp16+simd -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/algo/asm/basesigmoidtransform_c_f16_neon_arm64.c

TEXT ·sigmoidtransform_c_f16_neon(SB), $0-24
	MOVD in+0(FP), R0
	MOVD out+8(FP), R1
	MOVD plen_in+16(FP), R2
	WORD $0xf9400048        // ldr	x8, [x2]
	WORD $0xf100211f        // cmp	x8, #8
	BGE  BB0_2
	WORD $0xd280000c        // mov	x12, #0                         ; =0x0
	B    BB0_4

BB0_2:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0x528e430a // mov	w10, #29208                     ; =0x7218
	WORD $0x72b8562a // movk	w10, #49841, lsl #16
	WORD $0x4e040d40 // dup.4s	v0, w10
	WORD $0x5295476a // mov	w10, #43579                     ; =0xaa3b
	WORD $0x72b7f70a // movk	w10, #49080, lsl #16
	WORD $0x4e040d41 // dup.4s	v1, w10
	WORD $0x5290000a // mov	w10, #32768                     ; =0x8000
	WORD $0x72a7e62a // movk	w10, #16177, lsl #16
	WORD $0x4e040d42 // dup.4s	v2, w10
	WORD $0x5290106a // mov	w10, #32899                     ; =0x8083
	WORD $0x72a72bca // movk	w10, #14686, lsl #16
	WORD $0x4e040d43 // dup.4s	v3, w10
	WORD $0x52816c2a // mov	w10, #2913                      ; =0xb61
	WORD $0x72a756ca // movk	w10, #15030, lsl #16
	WORD $0x4e040d44 // dup.4s	v4, w10
	WORD $0x5291112a // mov	w10, #34953                     ; =0x8889
	WORD $0x72a7810a // movk	w10, #15368, lsl #16
	WORD $0x4e040d45 // dup.4s	v5, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7a54a // movk	w10, #15658, lsl #16
	WORD $0x4e040d46 // dup.4s	v6, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7c54a // movk	w10, #15914, lsl #16
	WORD $0x4e040d47 // dup.4s	v7, w10
	WORD $0x4f03f610 // fmov.4s	v16, #1.00000000
	WORD $0x52958a0a // mov	w10, #44112                     ; =0xac50
	WORD $0x72a855ca // movk	w10, #17070, lsl #16
	WORD $0x4e040d51 // dup.4s	v17, w10
	WORD $0xaa0103ea // mov	x10, x1
	WORD $0xaa0003eb // mov	x11, x0

BB0_3:
	WORD $0x3cc10572 // ldr	q18, [x11], #16
	WORD $0x0e217a53 // fcvtl	v19.4s, v18.4h
	WORD $0x4e217a52 // fcvtl2	v18.4s, v18.8h
	WORD $0x6ea0fa74 // fneg.4s	v20, v19
	WORD $0x6e21de75 // fmul.4s	v21, v19, v1
	WORD $0x4e218ab5 // frintn.4s	v21, v21
	WORD $0x6e22deb6 // fmul.4s	v22, v21, v2
	WORD $0x6e23deb7 // fmul.4s	v23, v21, v3
	WORD $0x4eb6d694 // fsub.4s	v20, v20, v22
	WORD $0x4e34d6f4 // fadd.4s	v20, v23, v20
	WORD $0x4ea51cb6 // mov.16b	v22, v5
	WORD $0x4e34cc96 // fmla.4s	v22, v4, v20
	WORD $0x4ea61cd7 // mov.16b	v23, v6
	WORD $0x4ea71cf8 // mov.16b	v24, v7
	WORD $0x4e36ce97 // fmla.4s	v23, v20, v22
	WORD $0x4f0167f6 // movi.4s	v22, #63, lsl #24
	WORD $0x6ea0fa59 // fneg.4s	v25, v18
	WORD $0x6e21de5a // fmul.4s	v26, v18, v1
	WORD $0x4e218b5a // frintn.4s	v26, v26
	WORD $0x6e22df5b // fmul.4s	v27, v26, v2
	WORD $0x4e37ce98 // fmla.4s	v24, v20, v23
	WORD $0x4ebbd737 // fsub.4s	v23, v25, v27
	WORD $0x6e23df59 // fmul.4s	v25, v26, v3
	WORD $0x4e37d737 // fadd.4s	v23, v25, v23
	WORD $0x4ea51cb9 // mov.16b	v25, v5
	WORD $0x4e37cc99 // fmla.4s	v25, v4, v23
	WORD $0x4e38ce96 // fmla.4s	v22, v20, v24
	WORD $0x4ea61cd8 // mov.16b	v24, v6
	WORD $0x4e39cef8 // fmla.4s	v24, v23, v25
	WORD $0x4ea71cf9 // mov.16b	v25, v7
	WORD $0x4e38cef9 // fmla.4s	v25, v23, v24
	WORD $0x4eb01e18 // mov.16b	v24, v16
	WORD $0x4e36ce98 // fmla.4s	v24, v20, v22
	WORD $0x4f0167f6 // movi.4s	v22, #63, lsl #24
	WORD $0x4e39cef6 // fmla.4s	v22, v23, v25
	WORD $0x4eb01e19 // mov.16b	v25, v16
	WORD $0x4e36cef9 // fmla.4s	v25, v23, v22
	WORD $0x4eb01e16 // mov.16b	v22, v16
	WORD $0x4e38ce96 // fmla.4s	v22, v20, v24
	WORD $0x4eb01e14 // mov.16b	v20, v16
	WORD $0x4e39cef4 // fmla.4s	v20, v23, v25
	WORD $0x6eb3e417 // fcmgt.4s	v23, v0, v19
	WORD $0x4e21aab5 // fcvtns.4s	v21, v21
	WORD $0x4f3756b5 // shl.4s	v21, v21, #23
	WORD $0x4eb086b5 // add.4s	v21, v21, v16
	WORD $0x6e35ded5 // fmul.4s	v21, v22, v21
	WORD $0x6eb1e673 // fcmgt.4s	v19, v19, v17
	WORD $0x4e30d6b5 // fadd.4s	v21, v21, v16
	WORD $0x6e35fe15 // fdiv.4s	v21, v16, v21
	WORD $0x6eb2e416 // fcmgt.4s	v22, v0, v18
	WORD $0x4e771eb5 // bic.16b	v21, v21, v23
	WORD $0x4e21ab57 // fcvtns.4s	v23, v26
	WORD $0x4f3756f7 // shl.4s	v23, v23, #23
	WORD $0x4eb086f7 // add.4s	v23, v23, v16
	WORD $0x6e37de94 // fmul.4s	v20, v20, v23
	WORD $0x6eb1e652 // fcmgt.4s	v18, v18, v17
	WORD $0x6e751e13 // bsl.16b	v19, v16, v21
	WORD $0x4e30d694 // fadd.4s	v20, v20, v16
	WORD $0x6e34fe14 // fdiv.4s	v20, v16, v20
	WORD $0x4e761e94 // bic.16b	v20, v20, v22
	WORD $0x6e741e12 // bsl.16b	v18, v16, v20
	WORD $0x0e216a73 // fcvtn	v19.4h, v19.4s
	WORD $0x4e216a53 // fcvtn2	v19.8h, v18.4s
	WORD $0x3c810553 // str	q19, [x10], #16
	WORD $0x9100212c // add	x12, x9, #8
	WORD $0x9100412d // add	x13, x9, #16
	WORD $0xaa0c03e9 // mov	x9, x12
	WORD $0xeb0801bf // cmp	x13, x8
	BLE  BB0_3

BB0_4:
	WORD $0xeb0c0109 // subs	x9, x8, x12
	BLE  BB0_16
	WORD $0xcb00002a // sub	x10, x1, x0
	WORD $0xf100113f // cmp	x9, #4
	WORD $0xfa482940 // ccmp	x10, #8, #0, hs
	BHS  BB0_7
	WORD $0xaa0c03e9 // mov	x9, x12
	B    BB0_10

BB0_7:
	WORD $0x9240050a // and	x10, x8, #0x3
	WORD $0xcb0a0129 // sub	x9, x9, x10
	WORD $0x8b090189 // add	x9, x12, x9
	WORD $0x8b0a018b // add	x11, x12, x10
	WORD $0xcb08016b // sub	x11, x11, x8
	WORD $0x529ab00d // mov	w13, #54656                     ; =0xd580
	WORD $0x0e020da0 // dup.4h	v0, w13
	WORD $0xd37ff98d // lsl	x13, x12, #1
	WORD $0x528ab00c // mov	w12, #21888                     ; =0x5580
	WORD $0x0e020d81 // dup.4h	v1, w12
	WORD $0x8b0d002c // add	x12, x1, x13
	WORD $0x8b0d000d // add	x13, x0, x13
	WORD $0x5295476e // mov	w14, #43579                     ; =0xaa3b
	WORD $0x72b7f70e // movk	w14, #49080, lsl #16
	WORD $0x4e040dc2 // dup.4s	v2, w14
	WORD $0x5290000e // mov	w14, #32768                     ; =0x8000
	WORD $0x72b7e62e // movk	w14, #48945, lsl #16
	WORD $0x4e040dc3 // dup.4s	v3, w14
	WORD $0x5290106e // mov	w14, #32899                     ; =0x8083
	WORD $0x72a72bce // movk	w14, #14686, lsl #16
	WORD $0x4e040dc4 // dup.4s	v4, w14
	WORD $0x52816c2e // mov	w14, #2913                      ; =0xb61
	WORD $0x72a756ce // movk	w14, #15030, lsl #16
	WORD $0x4e040dc5 // dup.4s	v5, w14
	WORD $0x5291112e // mov	w14, #34953                     ; =0x8889
	WORD $0x72a7810e // movk	w14, #15368, lsl #16
	WORD $0x4e040dc6 // dup.4s	v6, w14
	WORD $0x5295556e // mov	w14, #43691                     ; =0xaaab
	WORD $0x72a7a54e // movk	w14, #15658, lsl #16
	WORD $0x4e040dc7 // dup.4s	v7, w14
	WORD $0x5295556e // mov	w14, #43691                     ; =0xaaab
	WORD $0x72a7c54e // movk	w14, #15914, lsl #16
	WORD $0x4e040dd0 // dup.4s	v16, w14
	WORD $0x4f03f611 // fmov.4s	v17, #1.00000000
	WORD $0x6f03d7f2 // mvni.4s	v18, #127, msl #16
	WORD $0x6ea0fa52 // fneg.4s	v18, v18

BB0_8:
	WORD $0xfc4085b3 // ldr	d19, [x13], #8
	WORD $0x0e217a74 // fcvtl	v20.4s, v19.4h
	WORD $0x6ea0fa95 // fneg.4s	v21, v20
	WORD $0x2ed32416 // fcmgt.4h	v22, v0, v19
	WORD $0x6e22de94 // fmul.4s	v20, v20, v2
	WORD $0x6e218a94 // frinta.4s	v20, v20
	WORD $0x4e34cc75 // fmla.4s	v21, v3, v20
	WORD $0x2ec12673 // fcmgt.4h	v19, v19, v1
	WORD $0x4e34cc95 // fmla.4s	v21, v4, v20
	WORD $0x4ea61cd7 // mov.16b	v23, v6
	WORD $0x4e35ccb7 // fmla.4s	v23, v5, v21
	WORD $0x4ea71cf8 // mov.16b	v24, v7
	WORD $0x4e37ceb8 // fmla.4s	v24, v21, v23
	WORD $0x2e205ad7 // mvn.8b	v23, v22
	WORD $0x4eb01e19 // mov.16b	v25, v16
	WORD $0x4e38ceb9 // fmla.4s	v25, v21, v24
	WORD $0x4f0167f8 // movi.4s	v24, #63, lsl #24
	WORD $0x4e39ceb8 // fmla.4s	v24, v21, v25
	WORD $0x4eb11e39 // mov.16b	v25, v17
	WORD $0x0e731ef7 // bic.8b	v23, v23, v19
	WORD $0x4e38ceb9 // fmla.4s	v25, v21, v24
	WORD $0x4eb11e38 // mov.16b	v24, v17
	WORD $0x4e39ceb8 // fmla.4s	v24, v21, v25
	WORD $0x4ea1ba94 // fcvtzs.4s	v20, v20
	WORD $0x4f375694 // shl.4s	v20, v20, #23
	WORD $0x0f10a6f5 // sshll.4s	v21, v23, #0
	WORD $0x4eb18694 // add.4s	v20, v20, v17
	WORD $0x6e34df14 // fmul.4s	v20, v24, v20
	WORD $0x4e31d694 // fadd.4s	v20, v20, v17
	WORD $0x0e761e73 // bic.8b	v19, v19, v22
	WORD $0x0f10a673 // sshll.4s	v19, v19, #0
	WORD $0x6e721e33 // bsl.16b	v19, v17, v18
	WORD $0x6eb51e93 // bit.16b	v19, v20, v21
	WORD $0x6e33fe33 // fdiv.4s	v19, v17, v19
	WORD $0x0e216a73 // fcvtn	v19.4h, v19.4s
	WORD $0xfc008593 // str	d19, [x12], #8
	WORD $0xb100116b // adds	x11, x11, #4
	BNE  BB0_8
	CBZ  R10, BB0_16

BB0_10:
	WORD $0xcb090108 // sub	x8, x8, x9
	WORD $0xd37ff92a // lsl	x10, x9, #1
	WORD $0x8b0a0029 // add	x9, x1, x10
	WORD $0x8b0a000a // add	x10, x0, x10
	WORD $0x529ab00b // mov	w11, #54656                     ; =0xd580
	WORD $0x1ee70160 // fmov	h0, w11
	WORD $0x1e2e1001 // fmov	s1, #1.00000000
	WORD $0x528ab00b // mov	w11, #21888                     ; =0x5580
	WORD $0x1ee70162 // fmov	h2, w11
	WORD $0x5295476b // mov	w11, #43579                     ; =0xaa3b
	WORD $0x72b7f70b // movk	w11, #49080, lsl #16
	WORD $0x5290000c // mov	w12, #32768                     ; =0x8000
	WORD $0x72b7e62c // movk	w12, #48945, lsl #16
	WORD $0x5290106d // mov	w13, #32899                     ; =0x8083
	WORD $0x72a72bcd // movk	w13, #14686, lsl #16
	WORD $0x5291112e // mov	w14, #34953                     ; =0x8889
	WORD $0x72a7810e // movk	w14, #15368, lsl #16
	WORD $0x52816c2f // mov	w15, #2913                      ; =0xb61
	WORD $0x72a756cf // movk	w15, #15030, lsl #16
	WORD $0x52955570 // mov	w16, #43691                     ; =0xaaab
	WORD $0x72a7a550 // movk	w16, #15658, lsl #16
	WORD $0x52955571 // mov	w17, #43691                     ; =0xaaab
	WORD $0x72a7c551 // movk	w17, #15914, lsl #16
	WORD $0x1e2c1003 // fmov	s3, #0.50000000
	WORD $0x52a7f000 // mov	w0, #1065353216                 ; =0x3f800000
	B    BB0_13

BB0_11:
	WORD $0x52aff001 // mov	w1, #2139095040                 ; =0x7f800000
	WORD $0x1e270024 // fmov	s4, w1

BB0_12:
	WORD $0x1e241824 // fdiv	s4, s1, s4
	WORD $0x1e23c084 // fcvt	h4, s4
	WORD $0x7c002524 // str	h4, [x9], #2
	WORD $0xf1000508 // subs	x8, x8, #1
	BEQ  BB0_16

BB0_13:
	WORD $0x7c402545 // ldr	h5, [x10], #2
	WORD $0x1ee020a0 // fcmp	h5, h0
	BMI  BB0_11
	WORD $0x1e2e1004 // fmov	s4, #1.00000000
	WORD $0x1ee220a0 // fcmp	h5, h2
	BGT  BB0_12
	WORD $0x1ee240a4 // fcvt	s4, h5
	WORD $0x1e214085 // fneg	s5, s4
	WORD $0x1e270166 // fmov	s6, w11
	WORD $0x1e260884 // fmul	s4, s4, s6
	WORD $0x1e264086 // frinta	s6, s4
	WORD $0x1e270187 // fmov	s7, w12
	WORD $0x1f0714c5 // fmadd	s5, s6, s7, s5
	WORD $0x1e2701a7 // fmov	s7, w13
	WORD $0x1f0714c5 // fmadd	s5, s6, s7, s5
	WORD $0x1e2701c6 // fmov	s6, w14
	WORD $0x1e2701e7 // fmov	s7, w15
	WORD $0x1f0718a6 // fmadd	s6, s5, s7, s6
	WORD $0x1e270207 // fmov	s7, w16
	WORD $0x1f051cc6 // fmadd	s6, s6, s5, s7
	WORD $0x1e270227 // fmov	s7, w17
	WORD $0x1f051cc6 // fmadd	s6, s6, s5, s7
	WORD $0x1f050cc6 // fmadd	s6, s6, s5, s3
	WORD $0x1f0504c6 // fmadd	s6, s6, s5, s1
	WORD $0x1f0504c5 // fmadd	s5, s6, s5, s1
	WORD $0x1e240081 // fcvtas	w1, s4
	WORD $0x0b015c01 // add	w1, w0, w1, lsl #23
	WORD $0x1e270024 // fmov	s4, w1
	WORD $0x1e2408a4 // fmul	s4, s5, s4
	WORD $0x1e212884 // fadd	s4, s4, s1
	B    BB0_12

BB0_16:
	RET
