//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/algo/asm/basecount_c_u64_neon_arm64.c

TEXT ·count_c_u64_neon(SB), $0-32
	MOVD slice+0(FP), R0
	MOVD pvalue+8(FP), R1
	MOVD plen_slice+16(FP), R2
	MOVD pout_result+24(FP), R3
	WORD $0xf940004a            // ldr	x10, [x2]
	CBZ  R10, BB0_4
	WORD $0xf9400028            // ldr	x8, [x1]
	WORD $0xf100095f            // cmp	x10, #2
	BGE  BB0_5
	WORD $0xd280000b            // mov	x11, #0                         ; =0x0
	WORD $0xd2800009            // mov	x9, #0                          ; =0x0
	WORD $0xeb0b014a            // subs	x10, x10, x11
	BGT  BB0_8

BB0_3:
	WORD $0xf9000069 // str	x9, [x3]
	RET

BB0_4:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0xf9000069 // str	x9, [x3]
	RET

BB0_5:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0x4e080d00 // dup.2d	v0, x8
	WORD $0x5280004b // mov	w11, #2                         ; =0x2
	WORD $0x5280002c // mov	w12, #1                         ; =0x1
	WORD $0xaa0003ed // mov	x13, x0

BB0_6:
	WORD $0x3cc105a1 // ldr	q1, [x13], #16
	WORD $0x6ee08c21 // cmeq.2d	v1, v1, v0
	WORD $0x4e183c2e // mov.d	x14, v1[1]
	WORD $0x9e66002f // fmov	x15, d1
	WORD $0xf10001ff // cmp	x15, #0
	WORD $0x1a9f07ef // cset	w15, ne
	WORD $0x9a8c0590 // cinc	x16, x12, ne
	WORD $0xf10001df // cmp	x14, #0
	WORD $0x9a9001ee // csel	x14, x15, x16, eq
	WORD $0x8b0901c9 // add	x9, x14, x9
	WORD $0x9100096b // add	x11, x11, #2
	WORD $0xeb0a017f // cmp	x11, x10
	BLE  BB0_6
	WORD $0x927ff54b // and	x11, x10, #0x7ffffffffffffffe
	WORD $0xeb0b014a // subs	x10, x10, x11
	BLE  BB0_3

BB0_8:
	WORD $0x8b0b0c0b // add	x11, x0, x11, lsl #3

BB0_9:
	WORD $0xf840856c // ldr	x12, [x11], #8
	WORD $0xeb08019f // cmp	x12, x8
	WORD $0x9a891529 // cinc	x9, x9, eq
	WORD $0xf100054a // subs	x10, x10, #1
	BNE  BB0_9
	B    BB0_3
