//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   22.1.0
// 	objdump 2.46.0.20260210
// flags: -march=armv8.6-a+bf16+simd -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/algo/asm/baseerftransform_c_bf16_neon_arm64.c

TEXT ·erftransform_c_bf16_neon(SB), $64-24
	MOVD in+0(FP), R0
	MOVD out+8(FP), R1
	MOVD plen_in+16(FP), R2
	WORD $0x6d003bef        // stp	d15, d14, [sp, #-64]!           ; 16-byte Folded Spill [transformed]
	WORD $0x6d0133ed        // stp	d13, d12, [sp, #16]             ; 16-byte Folded Spill
	WORD $0x6d022beb        // stp	d11, d10, [sp, #32]             ; 16-byte Folded Spill
	WORD $0x6d0323e9        // stp	d9, d8, [sp, #48]               ; 16-byte Folded Spill
	WORD $0xf9400048        // ldr	x8, [x2]
	WORD $0xf100211f        // cmp	x8, #8
	BGE  BB0_2
	WORD $0xd2800009        // mov	x9, #0                          ; =0x0
	B    BB0_4

BB0_2:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0x529740aa // mov	w10, #47621                     ; =0xba05
	WORD $0x72a7d4ea // movk	w10, #16039, lsl #16
	WORD $0x4e040d40 // dup.4s	v0, w10
	WORD $0x4f03f601 // fmov.4s	v1, #1.00000000
	WORD $0x528f20ca // mov	w10, #30982                     ; =0x7906
	WORD $0x72a7d04a // movk	w10, #16002, lsl #16
	WORD $0x4e040d42 // dup.4s	v2, w10
	WORD $0x529531ca // mov	w10, #43406                     ; =0xa98e
	WORD $0x72b7d22a // movk	w10, #48785, lsl #16
	WORD $0x4e040d43 // dup.4s	v3, w10
	WORD $0x529e1c6a // mov	w10, #61667                     ; =0xf0e3
	WORD $0x72a7f6aa // movk	w10, #16309, lsl #16
	WORD $0x4e040d44 // dup.4s	v4, w10
	WORD $0x52801c6a // mov	w10, #227                       ; =0xe3
	WORD $0x72b7f74a // movk	w10, #49082, lsl #16
	WORD $0x4e040d45 // dup.4s	v5, w10
	WORD $0x529b844a // mov	w10, #56354                     ; =0xdc22
	WORD $0x72a7f0ea // movk	w10, #16263, lsl #16
	WORD $0x4e040d46 // dup.4s	v6, w10
	WORD $0x528e430a // mov	w10, #29208                     ; =0x7218
	WORD $0x72a8562a // movk	w10, #17073, lsl #16
	WORD $0x4e040d47 // dup.4s	v7, w10
	WORD $0x5295476a // mov	w10, #43579                     ; =0xaa3b
	WORD $0x72a7f70a // movk	w10, #16312, lsl #16
	WORD $0x4e040d50 // dup.4s	v16, w10
	WORD $0x5290000a // mov	w10, #32768                     ; =0x8000
	WORD $0x72a7e62a // movk	w10, #16177, lsl #16
	WORD $0x4e040d51 // dup.4s	v17, w10
	WORD $0x5290106a // mov	w10, #32899                     ; =0x8083
	WORD $0x72a72bca // movk	w10, #14686, lsl #16
	WORD $0x4e040d52 // dup.4s	v18, w10
	WORD $0x52816c2a // mov	w10, #2913                      ; =0xb61
	WORD $0x72a756ca // movk	w10, #15030, lsl #16
	WORD $0x4e040d53 // dup.4s	v19, w10
	WORD $0x5291112a // mov	w10, #34953                     ; =0x8889
	WORD $0x72a7810a // movk	w10, #15368, lsl #16
	WORD $0x4e040d54 // dup.4s	v20, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7a54a // movk	w10, #15658, lsl #16
	WORD $0x4e040d55 // dup.4s	v21, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7c54a // movk	w10, #15914, lsl #16
	WORD $0x4e040d56 // dup.4s	v22, w10
	WORD $0x52958a0a // mov	w10, #44112                     ; =0xac50
	WORD $0x72b855ca // movk	w10, #49838, lsl #16
	WORD $0x4e040d57 // dup.4s	v23, w10
	WORD $0x6f03d7f8 // mvni.4s	v24, #127, msl #16
	WORD $0x6ea0fb18 // fneg.4s	v24, v24
	WORD $0x4f000439 // movi.4s	v25, #1
	WORD $0x4f03c7fa // movi.4s	v26, #127, msl #8
	WORD $0xaa0103ea // mov	x10, x1
	WORD $0xaa0003eb // mov	x11, x0

BB0_3:
	WORD $0x3cc1057b // ldr	q27, [x11], #16
	WORD $0x2e613b7e // shll.4s	v30, v27, #16
	WORD $0x6e613b7d // shll2.4s	v29, v27, #16
	WORD $0x4ea0fbdc // fabs.4s	v28, v30
	WORD $0x4ea0ebdb // fcmlt.4s	v27, v30, #0.0
	WORD $0x4f03f61f // fmov.4s	v31, #1.00000000
	WORD $0x4e3ccc1f // fmla.4s	v31, v0, v28
	WORD $0x6e3ffc3f // fdiv.4s	v31, v1, v31
	WORD $0x6e3fdfe8 // fmul.4s	v8, v31, v31
	WORD $0x6e28dfe9 // fmul.4s	v9, v31, v8
	WORD $0x6e29dfea // fmul.4s	v10, v31, v9
	WORD $0x6e22dffc // fmul.4s	v28, v31, v2
	WORD $0x6e2adfff // fmul.4s	v31, v31, v10
	WORD $0x4e28cc7c // fmla.4s	v28, v3, v8
	WORD $0x4e29cc9c // fmla.4s	v28, v4, v9
	WORD $0x6ea0fbc8 // fneg.4s	v8, v30
	WORD $0x6e28dfde // fmul.4s	v30, v30, v8
	WORD $0x6ea7e7c8 // fcmgt.4s	v8, v30, v7
	WORD $0x4e2accbc // fmla.4s	v28, v5, v10
	WORD $0x6e30dfc9 // fmul.4s	v9, v30, v16
	WORD $0x4e218929 // frintn.4s	v9, v9
	WORD $0x6e31dd2a // fmul.4s	v10, v9, v17
	WORD $0x4eaad7ca // fsub.4s	v10, v30, v10
	WORD $0x6e32dd2b // fmul.4s	v11, v9, v18
	WORD $0x4e3fccdc // fmla.4s	v28, v6, v31
	WORD $0x4e2ad57f // fadd.4s	v31, v11, v10
	WORD $0x4eb41e8a // mov.16b	v10, v20
	WORD $0x4e3fce6a // fmla.4s	v10, v19, v31
	WORD $0x4eb51eab // mov.16b	v11, v21
	WORD $0x4eb61ecc // mov.16b	v12, v22
	WORD $0x4e2acfeb // fmla.4s	v11, v31, v10
	WORD $0x4e2bcfec // fmla.4s	v12, v31, v11
	WORD $0x4f0167ea // movi.4s	v10, #63, lsl #24
	WORD $0x4f03f60b // fmov.4s	v11, #1.00000000
	WORD $0x4f03f60d // fmov.4s	v13, #1.00000000
	WORD $0x4e21a929 // fcvtns.4s	v9, v9
	WORD $0x4e2ccfea // fmla.4s	v10, v31, v12
	WORD $0x4f375529 // shl.4s	v9, v9, #23
	WORD $0x4ea18529 // add.4s	v9, v9, v1
	WORD $0x6ebee6fe // fcmgt.4s	v30, v23, v30
	WORD $0x4ea0fbac // fabs.4s	v12, v29
	WORD $0x4ea0ebae // fcmlt.4s	v14, v29, #0.0
	WORD $0x4e2acfeb // fmla.4s	v11, v31, v10
	WORD $0x4f03f60a // fmov.4s	v10, #1.00000000
	WORD $0x4e2ccc0a // fmla.4s	v10, v0, v12
	WORD $0x6e2afc2a // fdiv.4s	v10, v1, v10
	WORD $0x6e2add4c // fmul.4s	v12, v10, v10
	WORD $0x6e22dd4f // fmul.4s	v15, v10, v2
	WORD $0x4e2bcfed // fmla.4s	v13, v31, v11
	WORD $0x4e2ccc6f // fmla.4s	v15, v3, v12
	WORD $0x6e2cdd5f // fmul.4s	v31, v10, v12
	WORD $0x4e3fcc8f // fmla.4s	v15, v4, v31
	WORD $0x6e3fdd5f // fmul.4s	v31, v10, v31
	WORD $0x6e3fdd4a // fmul.4s	v10, v10, v31
	WORD $0x6e29dda9 // fmul.4s	v9, v13, v9
	WORD $0x4e3fccaf // fmla.4s	v15, v5, v31
	WORD $0x4e2acccf // fmla.4s	v15, v6, v10
	WORD $0x6ea0fbbf // fneg.4s	v31, v29
	WORD $0x6e3fdfbd // fmul.4s	v29, v29, v31
	WORD $0x6e30dfbf // fmul.4s	v31, v29, v16
	WORD $0x6e691f08 // bsl.16b	v8, v24, v9
	WORD $0x4e218bff // frintn.4s	v31, v31
	WORD $0x6e31dfe9 // fmul.4s	v9, v31, v17
	WORD $0x4ea9d7a9 // fsub.4s	v9, v29, v9
	WORD $0x6e32dfea // fmul.4s	v10, v31, v18
	WORD $0x4e29d549 // fadd.4s	v9, v10, v9
	WORD $0x4e7e1d1e // bic.16b	v30, v8, v30
	WORD $0x4eb41e88 // mov.16b	v8, v20
	WORD $0x4e29ce68 // fmla.4s	v8, v19, v9
	WORD $0x4eb51eaa // mov.16b	v10, v21
	WORD $0x4e28cd2a // fmla.4s	v10, v9, v8
	WORD $0x4eb61ec8 // mov.16b	v8, v22
	WORD $0x6e3edf9c // fmul.4s	v28, v28, v30
	WORD $0x4e2acd28 // fmla.4s	v8, v9, v10
	WORD $0x4f0167fe // movi.4s	v30, #63, lsl #24
	WORD $0x4e28cd3e // fmla.4s	v30, v9, v8
	WORD $0x4f03f608 // fmov.4s	v8, #1.00000000
	WORD $0x4e3ecd28 // fmla.4s	v8, v9, v30
	WORD $0x4ebcd43c // fsub.4s	v28, v1, v28
	WORD $0x4f03f61e // fmov.4s	v30, #1.00000000
	WORD $0x4e28cd3e // fmla.4s	v30, v9, v8
	WORD $0x6ea7e7a8 // fcmgt.4s	v8, v29, v7
	WORD $0x4e21abff // fcvtns.4s	v31, v31
	WORD $0x4f3757ff // shl.4s	v31, v31, #23
	WORD $0x6ea0fb89 // fneg.4s	v9, v28
	WORD $0x4ea187ff // add.4s	v31, v31, v1
	WORD $0x6e3fdfde // fmul.4s	v30, v30, v31
	WORD $0x6ebde6fd // fcmgt.4s	v29, v23, v29
	WORD $0x6ea81f1e // bit.16b	v30, v24, v8
	WORD $0x4e7d1fdd // bic.16b	v29, v30, v29
	WORD $0x6e7c1d3b // bsl.16b	v27, v9, v28
	WORD $0x6e3dddfc // fmul.4s	v28, v15, v29
	WORD $0x4ebcd43c // fsub.4s	v28, v1, v28
	WORD $0x6ea0fb9d // fneg.4s	v29, v28
	WORD $0x6eae1fbc // bit.16b	v28, v29, v14
	WORD $0x6f30079d // ushr.4s	v29, v28, #16
	WORD $0x4e391fbd // and.16b	v29, v29, v25
	WORD $0x4ebd879c // add.4s	v28, v28, v29
	WORD $0x6f30077d // ushr.4s	v29, v27, #16
	WORD $0x4e391fbd // and.16b	v29, v29, v25
	WORD $0x4ebd877b // add.4s	v27, v27, v29
	WORD $0x0e7a437b // addhn.4h	v27, v27, v26
	WORD $0x4e7a439b // addhn2.8h	v27, v28, v26
	WORD $0x3c81055b // str	q27, [x10], #16
	WORD $0x9100412c // add	x12, x9, #16
	WORD $0x91002129 // add	x9, x9, #8
	WORD $0xeb08019f // cmp	x12, x8
	BLE  BB0_3

BB0_4:
	WORD $0xeb09010a // subs	x10, x8, x9
	BLE  BB0_16
	WORD $0xcb00002b // sub	x11, x1, x0
	WORD $0xf100115f // cmp	x10, #4
	WORD $0xfa482960 // ccmp	x11, #8, #0, hs
	BHS  BB0_7
	WORD $0xaa0903ea // mov	x10, x9
	B    BB0_10

BB0_7:
	WORD $0x9240050b // and	x11, x8, #0x3
	WORD $0xcb0b014a // sub	x10, x10, x11
	WORD $0x8b0a012a // add	x10, x9, x10
	WORD $0x8b0b012c // add	x12, x9, x11
	WORD $0xcb08018c // sub	x12, x12, x8
	WORD $0xd37ff92d // lsl	x13, x9, #1
	WORD $0x52a85609 // mov	w9, #1118830592                 ; =0x42b00000
	WORD $0x4e040d20 // dup.4s	v0, w9
	WORD $0x52b85609 // mov	w9, #-1028653056                ; =0xc2b00000
	WORD $0x4e040d21 // dup.4s	v1, w9
	WORD $0x8b0d0029 // add	x9, x1, x13
	WORD $0x5295476e // mov	w14, #43579                     ; =0xaa3b
	WORD $0x72a7f70e // movk	w14, #16312, lsl #16
	WORD $0x4e040dc2 // dup.4s	v2, w14
	WORD $0x5290000e // mov	w14, #32768                     ; =0x8000
	WORD $0x72b7e62e // movk	w14, #48945, lsl #16
	WORD $0x4e040dc3 // dup.4s	v3, w14
	WORD $0x5290106e // mov	w14, #32899                     ; =0x8083
	WORD $0x72a72bce // movk	w14, #14686, lsl #16
	WORD $0x4e040dc4 // dup.4s	v4, w14
	WORD $0x52816c2e // mov	w14, #2913                      ; =0xb61
	WORD $0x72a756ce // movk	w14, #15030, lsl #16
	WORD $0x4e040dc5 // dup.4s	v5, w14
	WORD $0x5291112e // mov	w14, #34953                     ; =0x8889
	WORD $0x72a7810e // movk	w14, #15368, lsl #16
	WORD $0x4e040dc6 // dup.4s	v6, w14
	WORD $0x5295556e // mov	w14, #43691                     ; =0xaaab
	WORD $0x72a7a54e // movk	w14, #15658, lsl #16
	WORD $0x4e040dc7 // dup.4s	v7, w14
	WORD $0x5295556e // mov	w14, #43691                     ; =0xaaab
	WORD $0x72a7c54e // movk	w14, #15914, lsl #16
	WORD $0x4e040dd0 // dup.4s	v16, w14
	WORD $0x8b0d000d // add	x13, x0, x13
	WORD $0x4f03f611 // fmov.4s	v17, #1.00000000
	WORD $0x6f03d7f7 // mvni.4s	v23, #127, msl #16
	WORD $0x529740ae // mov	w14, #47621                     ; =0xba05
	WORD $0x72a7d4ee // movk	w14, #16039, lsl #16
	WORD $0x4e040dd2 // dup.4s	v18, w14
	WORD $0x529531ce // mov	w14, #43406                     ; =0xa98e
	WORD $0x72b7d22e // movk	w14, #48785, lsl #16
	WORD $0x4e040dd3 // dup.4s	v19, w14
	WORD $0x528f20ce // mov	w14, #30982                     ; =0x7906
	WORD $0x72a7d04e // movk	w14, #16002, lsl #16
	WORD $0x4e040dd4 // dup.4s	v20, w14
	WORD $0x529e1c6e // mov	w14, #61667                     ; =0xf0e3
	WORD $0x72a7f6ae // movk	w14, #16309, lsl #16
	WORD $0x4e040dd5 // dup.4s	v21, w14
	WORD $0x52801c6e // mov	w14, #227                       ; =0xe3
	WORD $0x72b7f74e // movk	w14, #49082, lsl #16
	WORD $0x4e040dd6 // dup.4s	v22, w14
	WORD $0x6ea0faf7 // fneg.4s	v23, v23
	WORD $0x529b844e // mov	w14, #56354                     ; =0xdc22
	WORD $0x72a7f0ee // movk	w14, #16263, lsl #16
	WORD $0x4e040dd8 // dup.4s	v24, w14
	WORD $0x4f000439 // movi.4s	v25, #1
	WORD $0x4f03c7fa // movi.4s	v26, #127, msl #8

BB0_8:
	WORD $0xfc4085bb // ldr	d27, [x13], #8
	WORD $0x2e613b7b // shll.4s	v27, v27, #16
	WORD $0x4ea0eb7c // fcmlt.4s	v28, v27, #0.0
	WORD $0x6ea0fb7d // fneg.4s	v29, v27
	WORD $0x6ebc1fbb // bit.16b	v27, v29, v28
	WORD $0x6ea0fb7d // fneg.4s	v29, v27
	WORD $0x6e3ddf7d // fmul.4s	v29, v27, v29
	WORD $0x6ea0e7be // fcmgt.4s	v30, v29, v0
	WORD $0x6ebde43f // fcmgt.4s	v31, v1, v29
	WORD $0x6e22dfa8 // fmul.4s	v8, v29, v2
	WORD $0x6e218908 // frinta.4s	v8, v8
	WORD $0x4e28cc7d // fmla.4s	v29, v3, v8
	WORD $0x4e28cc9d // fmla.4s	v29, v4, v8
	WORD $0x4ea61cc9 // mov.16b	v9, v6
	WORD $0x4e3dcca9 // fmla.4s	v9, v5, v29
	WORD $0x4ea71cea // mov.16b	v10, v7
	WORD $0x4e29cfaa // fmla.4s	v10, v29, v9
	WORD $0x4eb01e09 // mov.16b	v9, v16
	WORD $0x4e2acfa9 // fmla.4s	v9, v29, v10
	WORD $0x4f0167ea // movi.4s	v10, #63, lsl #24
	WORD $0x4e29cfaa // fmla.4s	v10, v29, v9
	WORD $0x4f03f609 // fmov.4s	v9, #1.00000000
	WORD $0x4f03f60b // fmov.4s	v11, #1.00000000
	WORD $0x4e2acfa9 // fmla.4s	v9, v29, v10
	WORD $0x4e29cfab // fmla.4s	v11, v29, v9
	WORD $0x4ea1b91d // fcvtzs.4s	v29, v8
	WORD $0x4f3757bd // shl.4s	v29, v29, #23
	WORD $0x4eb187bd // add.4s	v29, v29, v17
	WORD $0x4f03f608 // fmov.4s	v8, #1.00000000
	WORD $0x6e3ddd7d // fmul.4s	v29, v11, v29
	WORD $0x4e3bce48 // fmla.4s	v8, v18, v27
	WORD $0x6e28fe3b // fdiv.4s	v27, v17, v8
	WORD $0x6e3bdf68 // fmul.4s	v8, v27, v27
	WORD $0x6e28df69 // fmul.4s	v9, v27, v8
	WORD $0x6e29df6a // fmul.4s	v10, v27, v9
	WORD $0x4e7f1fbd // bic.16b	v29, v29, v31
	WORD $0x6e2adf7f // fmul.4s	v31, v27, v10
	WORD $0x6e33dd08 // fmul.4s	v8, v8, v19
	WORD $0x4e3bce88 // fmla.4s	v8, v20, v27
	WORD $0x4e29cea8 // fmla.4s	v8, v21, v9
	WORD $0x4e2acec8 // fmla.4s	v8, v22, v10
	WORD $0x4ebe1fdb // mov.16b	v27, v30
	WORD $0x6e7d1efb // bsl.16b	v27, v23, v29
	WORD $0x4e3fcf08 // fmla.4s	v8, v24, v31
	WORD $0x4f03f61d // fmov.4s	v29, #1.00000000
	WORD $0x4ea8cf7d // fmls.4s	v29, v27, v8
	WORD $0x6ea0fbbb // fneg.4s	v27, v29
	WORD $0x6efc1fbb // bif.16b	v27, v29, v28
	WORD $0x6f30077c // ushr.4s	v28, v27, #16
	WORD $0x4e391f9c // and.16b	v28, v28, v25
	WORD $0x4ebc877b // add.4s	v27, v27, v28
	WORD $0x0e7a437b // addhn.4h	v27, v27, v26
	WORD $0xfc00853b // str	d27, [x9], #8
	WORD $0xb100118c // adds	x12, x12, #4
	BNE  BB0_8
	CBZ  R11, BB0_16

BB0_10:
	WORD $0xcb0a0108 // sub	x8, x8, x10
	WORD $0xd37ff94a // lsl	x10, x10, #1
	WORD $0x8b0a0029 // add	x9, x1, x10
	WORD $0x8b0a000a // add	x10, x0, x10
	WORD $0x52a8560b // mov	w11, #1118830592                ; =0x42b00000
	WORD $0x1e270160 // fmov	s0, w11
	WORD $0x529740ab // mov	w11, #47621                     ; =0xba05
	WORD $0x72a7d4eb // movk	w11, #16039, lsl #16
	WORD $0x1e270161 // fmov	s1, w11
	WORD $0x1e2e1002 // fmov	s2, #1.00000000
	WORD $0x529531cb // mov	w11, #43406                     ; =0xa98e
	WORD $0x72b7d22b // movk	w11, #48785, lsl #16
	WORD $0x1e270163 // fmov	s3, w11
	WORD $0x528f20cb // mov	w11, #30982                     ; =0x7906
	WORD $0x72a7d04b // movk	w11, #16002, lsl #16
	WORD $0x1e270164 // fmov	s4, w11
	WORD $0x529e1c6b // mov	w11, #61667                     ; =0xf0e3
	WORD $0x72a7f6ab // movk	w11, #16309, lsl #16
	WORD $0x1e270165 // fmov	s5, w11
	WORD $0x52801c6b // mov	w11, #227                       ; =0xe3
	WORD $0x72b7f74b // movk	w11, #49082, lsl #16
	WORD $0x1e270166 // fmov	s6, w11
	WORD $0x529b844b // mov	w11, #56354                     ; =0xdc22
	WORD $0x72a7f0eb // movk	w11, #16263, lsl #16
	WORD $0x1e270167 // fmov	s7, w11
	WORD $0x528fffeb // mov	w11, #32767                     ; =0x7fff
	WORD $0x52b8560c // mov	w12, #-1028653056               ; =0xc2b00000
	WORD $0x1e270190 // fmov	s16, w12
	WORD $0x5295476c // mov	w12, #43579                     ; =0xaa3b
	WORD $0x72a7f70c // movk	w12, #16312, lsl #16
	WORD $0x1e270191 // fmov	s17, w12
	WORD $0x5290000c // mov	w12, #32768                     ; =0x8000
	WORD $0x72b7e62c // movk	w12, #48945, lsl #16
	WORD $0x1e270192 // fmov	s18, w12
	WORD $0x5290106c // mov	w12, #32899                     ; =0x8083
	WORD $0x72a72bcc // movk	w12, #14686, lsl #16
	WORD $0x1e270193 // fmov	s19, w12
	WORD $0x5291112c // mov	w12, #34953                     ; =0x8889
	WORD $0x72a7810c // movk	w12, #15368, lsl #16
	WORD $0x1e270194 // fmov	s20, w12
	WORD $0x52816c2c // mov	w12, #2913                      ; =0xb61
	WORD $0x72a756cc // movk	w12, #15030, lsl #16
	WORD $0x1e270195 // fmov	s21, w12
	WORD $0x5295556c // mov	w12, #43691                     ; =0xaaab
	WORD $0x72a7a54c // movk	w12, #15658, lsl #16
	WORD $0x1e270196 // fmov	s22, w12
	WORD $0x5295556c // mov	w12, #43691                     ; =0xaaab
	WORD $0x72a7c54c // movk	w12, #15914, lsl #16
	WORD $0x1e270197 // fmov	s23, w12
	WORD $0x1e2c1018 // fmov	s24, #0.50000000
	WORD $0x52a7f00c // mov	w12, #1065353216                ; =0x3f800000
	B    BB0_13

BB0_11:
	WORD $0x52aff00d // mov	w13, #2139095040                ; =0x7f800000
	WORD $0x1e2701bb // fmov	s27, w13

BB0_12:
	WORD $0x1f010b5a // fmadd	s26, s26, s1, s2
	WORD $0x1e3a185a // fdiv	s26, s2, s26
	WORD $0x1e3a0b5c // fmul	s28, s26, s26
	WORD $0x1e3c0b5d // fmul	s29, s26, s28
	WORD $0x1e3d0b5e // fmul	s30, s26, s29
	WORD $0x1e3e0b5f // fmul	s31, s26, s30
	WORD $0x1e230b9c // fmul	s28, s28, s3
	WORD $0x1f04735a // fmadd	s26, s26, s4, s28
	WORD $0x1f056bba // fmadd	s26, s29, s5, s26
	WORD $0x1f066bda // fmadd	s26, s30, s6, s26
	WORD $0x1f076bfc // fmadd	s28, s31, s7, s26
	WORD $0x1f276bfa // fnmadd	s26, s31, s7, s26
	WORD $0x1f1b8b9c // fmsub	s28, s28, s27, s2
	WORD $0x1f3b0b5a // fnmadd	s26, s26, s27, s2
	WORD $0x1e202328 // fcmp	s25, #0.0
	WORD $0x1e3c4f59 // fcsel	s25, s26, s28, mi
	WORD $0x1e26032d // fmov	w13, s25
	WORD $0x531041ae // ubfx	w14, w13, #16, #1
	WORD $0x0b0e01ad // add	w13, w13, w14
	WORD $0x0b0b01ad // add	w13, w13, w11
	WORD $0x53107dad // lsr	w13, w13, #16
	WORD $0x7800252d // strh	w13, [x9], #2
	WORD $0xf1000508 // subs	x8, x8, #1
	BEQ  BB0_16

BB0_13:
	WORD $0x7840254d // ldrh	w13, [x10], #2
	WORD $0x53103dad // lsl	w13, w13, #16
	WORD $0x1e2701b9 // fmov	s25, w13
	WORD $0x1e21433a // fneg	s26, s25
	WORD $0x1e202328 // fcmp	s25, #0.0
	WORD $0x1e394f5a // fcsel	s26, s26, s25, mi
	WORD $0x1e3a8b5c // fnmul	s28, s26, s26
	WORD $0x1e202380 // fcmp	s28, s0
	BGT  BB0_11
	WORD $0x6f00e41b // movi.2d	v27, #0000000000000000
	WORD $0x1e302380 // fcmp	s28, s16
	BMI  BB0_12
	WORD $0x1e310b9b // fmul	s27, s28, s17
	WORD $0x1e26437d // frinta	s29, s27
	WORD $0x1f1273bc // fmadd	s28, s29, s18, s28
	WORD $0x1f1373bc // fmadd	s28, s29, s19, s28
	WORD $0x1f15539d // fmadd	s29, s28, s21, s20
	WORD $0x1f1c5bbd // fmadd	s29, s29, s28, s22
	WORD $0x1f1c5fbd // fmadd	s29, s29, s28, s23
	WORD $0x1f1c63bd // fmadd	s29, s29, s28, s24
	WORD $0x1f1c0bbd // fmadd	s29, s29, s28, s2
	WORD $0x1f1c0bbc // fmadd	s28, s29, s28, s2
	WORD $0x1e24036d // fcvtas	w13, s27
	WORD $0x0b0d5d8d // add	w13, w12, w13, lsl #23
	WORD $0x1e2701bb // fmov	s27, w13
	WORD $0x1e3b0b9b // fmul	s27, s28, s27
	B    BB0_12

BB0_16:
	WORD $0x6d4323e9 // ldp	d9, d8, [sp, #48]               ; 16-byte Folded Reload
	WORD $0x6d422beb // ldp	d11, d10, [sp, #32]             ; 16-byte Folded Reload
	WORD $0x6d4133ed // ldp	d13, d12, [sp, #16]             ; 16-byte Folded Reload
	WORD $0x6d403bef // ldp	d15, d14, [sp], #64             ; 16-byte Folded Reload [transformed]
	RET
