//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   22.1.0
// 	objdump 2.46.0.20260210
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/algo/asm/basesintransform_c_f64_neon_arm64.c

TEXT ·sintransform_c_f64_neon(SB), $0-24
	MOVD in+0(FP), R0
	MOVD out+8(FP), R1
	MOVD plen_in+16(FP), R2
	WORD $0xf9400048        // ldr	x8, [x2]
	WORD $0xf100091f        // cmp	x8, #2
	BGE  BB0_2
	WORD $0xd2800009        // mov	x9, #0                          ; =0x0
	B    BB0_4

BB0_2:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0xd299106a // mov	x10, #51331                     ; =0xc883
	WORD $0xf2adb92a // movk	x10, #28105, lsl #16
	WORD $0xf2cbe60a // movk	x10, #24368, lsl #32
	WORD $0xf2e7fc8a // movk	x10, #16356, lsl #48
	WORD $0x4e080d40 // dup.2d	v0, x10
	WORD $0xd285a30a // mov	x10, #11544                     ; =0x2d18
	WORD $0xf2aa888a // movk	x10, #21572, lsl #16
	WORD $0xf2c43f6a // movk	x10, #8699, lsl #32
	WORD $0xf2f7ff2a // movk	x10, #49145, lsl #48
	WORD $0x4e080d41 // dup.2d	v1, x10
	WORD $0xd28b80ea // mov	x10, #23559                     ; =0x5c07
	WORD $0xf2a6628a // movk	x10, #13076, lsl #16
	WORD $0xf2d4c4ca // movk	x10, #42534, lsl #32
	WORD $0xf2f7922a // movk	x10, #48273, lsl #48
	WORD $0x4e080d42 // dup.2d	v2, x10
	WORD $0xd29bc02a // mov	x10, #56833                     ; =0xde01
	WORD $0xf2af2d8a // movk	x10, #31084, lsl #16
	WORD $0xf2c3bc6a // movk	x10, #7651, lsl #32
	WORD $0xf2e7d8ea // movk	x10, #16071, lsl #48
	WORD $0x4e080d43 // dup.2d	v3, x10
	WORD $0xd28ed0ea // mov	x10, #30343                     ; =0x7687
	WORD $0xf2a33fea // movk	x10, #6655, lsl #16
	WORD $0xf2c0340a // movk	x10, #416, lsl #32
	WORD $0xf2f7e54a // movk	x10, #48938, lsl #48
	WORD $0x4e080d44 // dup.2d	v4, x10
	WORD $0xb200e3ea // mov	x10, #1229782938247303441       ; =0x1111111111111111
	WORD $0xf281d40a // movk	x10, #3744
	WORD $0xf2e7f02a // movk	x10, #16257, lsl #48
	WORD $0x4e080d45 // dup.2d	v5, x10
	WORD $0xb200f3ea // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf28aa92a // movk	x10, #21833
	WORD $0xf2f7f8aa // movk	x10, #49093, lsl #48
	WORD $0x4e080d46 // dup.2d	v6, x10
	WORD $0xd2889eaa // mov	x10, #17653                     ; =0x44f5
	WORD $0xf2a3390a // movk	x10, #6600, lsl #16
	WORD $0xf2c0340a // movk	x10, #416, lsl #32
	WORD $0xf2e7df4a // movk	x10, #16122, lsl #48
	WORD $0x4e080d47 // dup.2d	v7, x10
	WORD $0xd28a2eea // mov	x10, #20855                     ; =0x5177
	WORD $0xf2a2d82a // movk	x10, #5825, lsl #16
	WORD $0xf2d82d8a // movk	x10, #49516, lsl #32
	WORD $0xf2f7eaca // movk	x10, #48982, lsl #48
	WORD $0x4e080d50 // dup.2d	v16, x10
	WORD $0xb200f3ea // mov	x10, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf28aa28a // movk	x10, #21780
	WORD $0xf2e7f4aa // movk	x10, #16293, lsl #48
	WORD $0x4e080d51 // dup.2d	v17, x10
	WORD $0x5280002a // mov	w10, #1                         ; =0x1
	WORD $0x4e080d52 // dup.2d	v18, x10
	WORD $0x5280004a // mov	w10, #2                         ; =0x2
	WORD $0x4e080d53 // dup.2d	v19, x10
	WORD $0xaa0103ea // mov	x10, x1
	WORD $0xaa0003eb // mov	x11, x0

BB0_3:
	WORD $0x3cc10574 // ldr	q20, [x11], #16
	WORD $0x6e60de95 // fmul.2d	v21, v20, v0
	WORD $0x4e618ab5 // frintn.2d	v21, v21
	WORD $0x6e61deb6 // fmul.2d	v22, v21, v1
	WORD $0x4e76d694 // fadd.2d	v20, v20, v22
	WORD $0x6e62deb6 // fmul.2d	v22, v21, v2
	WORD $0x4e76d694 // fadd.2d	v20, v20, v22
	WORD $0x4e61aab5 // fcvtns.2d	v21, v21
	WORD $0x6e74de96 // fmul.2d	v22, v20, v20
	WORD $0x4ea41c97 // mov.16b	v23, v4
	WORD $0x4e76cc77 // fmla.2d	v23, v3, v22
	WORD $0x4ea51cb8 // mov.16b	v24, v5
	WORD $0x4ea61cd9 // mov.16b	v25, v6
	WORD $0x4e77ced8 // fmla.2d	v24, v22, v23
	WORD $0x4e78ced9 // fmla.2d	v25, v22, v24
	WORD $0x6e76de97 // fmul.2d	v23, v20, v22
	WORD $0x4eb01e18 // mov.16b	v24, v16
	WORD $0x4e76ccf8 // fmla.2d	v24, v7, v22
	WORD $0x4eb11e3a // mov.16b	v26, v17
	WORD $0x4e77cf34 // fmla.2d	v20, v25, v23
	WORD $0x4e78ceda // fmla.2d	v26, v22, v24
	WORD $0x6f07f417 // fmov.2d	v23, #-0.50000000
	WORD $0x4e7aced7 // fmla.2d	v23, v22, v26
	WORD $0x6f03f618 // fmov.2d	v24, #1.00000000
	WORD $0x4e76cef8 // fmla.2d	v24, v23, v22
	WORD $0x4e321eb6 // and.16b	v22, v21, v18
	WORD $0x4e331eb5 // and.16b	v21, v21, v19
	WORD $0x4ee09ab5 // cmeq.2d	v21, v21, #0
	WORD $0x4ee09ad6 // cmeq.2d	v22, v22, #0
	WORD $0x6ef61f14 // bif.16b	v20, v24, v22
	WORD $0x6ee0fa96 // fneg.2d	v22, v20
	WORD $0x6ef51ed4 // bif.16b	v20, v22, v21
	WORD $0x3c810554 // str	q20, [x10], #16
	WORD $0x9100112c // add	x12, x9, #4
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08019f // cmp	x12, x8
	BLE  BB0_3

BB0_4:
	WORD $0xeb09010a // subs	x10, x8, x9
	BLE  BB0_12
	WORD $0xcb00002b // sub	x11, x1, x0
	WORD $0xf100095f // cmp	x10, #2
	WORD $0xfa502960 // ccmp	x11, #16, #0, hs
	BHS  BB0_7
	WORD $0xaa0903ea // mov	x10, x9
	B    BB0_10

BB0_7:
	WORD $0x9240010b // and	x11, x8, #0x1
	WORD $0xcb0b014a // sub	x10, x10, x11
	WORD $0x8b0a012a // add	x10, x9, x10
	WORD $0x8b0b012c // add	x12, x9, x11
	WORD $0xcb08018c // sub	x12, x12, x8
	WORD $0xd299106d // mov	x13, #51331                     ; =0xc883
	WORD $0xf2adb92d // movk	x13, #28105, lsl #16
	WORD $0xf2cbe60d // movk	x13, #24368, lsl #32
	WORD $0xf2e7fc8d // movk	x13, #16356, lsl #48
	WORD $0x4e080da0 // dup.2d	v0, x13
	WORD $0xd37df12d // lsl	x13, x9, #3
	WORD $0xd285a309 // mov	x9, #11544                      ; =0x2d18
	WORD $0xf2aa8889 // movk	x9, #21572, lsl #16
	WORD $0xf2c43f69 // movk	x9, #8699, lsl #32
	WORD $0xf2f7ff29 // movk	x9, #49145, lsl #48
	WORD $0x4e080d21 // dup.2d	v1, x9
	WORD $0x8b0d0029 // add	x9, x1, x13
	WORD $0x8b0d000d // add	x13, x0, x13
	WORD $0xd28b80ee // mov	x14, #23559                     ; =0x5c07
	WORD $0xf2a6628e // movk	x14, #13076, lsl #16
	WORD $0xf2d4c4ce // movk	x14, #42534, lsl #32
	WORD $0xf2f7922e // movk	x14, #48273, lsl #48
	WORD $0x4e080dc2 // dup.2d	v2, x14
	WORD $0xd29bc02e // mov	x14, #56833                     ; =0xde01
	WORD $0xf2af2d8e // movk	x14, #31084, lsl #16
	WORD $0xf2c3bc6e // movk	x14, #7651, lsl #32
	WORD $0xf2e7d8ee // movk	x14, #16071, lsl #48
	WORD $0x4e080dc3 // dup.2d	v3, x14
	WORD $0xd28ed0ee // mov	x14, #30343                     ; =0x7687
	WORD $0xf2a33fee // movk	x14, #6655, lsl #16
	WORD $0xf2c0340e // movk	x14, #416, lsl #32
	WORD $0xf2f7e54e // movk	x14, #48938, lsl #48
	WORD $0x4e080dc4 // dup.2d	v4, x14
	WORD $0xb200e3ee // mov	x14, #1229782938247303441       ; =0x1111111111111111
	WORD $0xf281d40e // movk	x14, #3744
	WORD $0xf2e7f02e // movk	x14, #16257, lsl #48
	WORD $0x4e080dc5 // dup.2d	v5, x14
	WORD $0xb200f3ee // mov	x14, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf28aa92e // movk	x14, #21833
	WORD $0xf2f7f8ae // movk	x14, #49093, lsl #48
	WORD $0x4e080dc6 // dup.2d	v6, x14
	WORD $0xd2889eae // mov	x14, #17653                     ; =0x44f5
	WORD $0xf2a3390e // movk	x14, #6600, lsl #16
	WORD $0xf2c0340e // movk	x14, #416, lsl #32
	WORD $0xf2e7df4e // movk	x14, #16122, lsl #48
	WORD $0x4e080dc7 // dup.2d	v7, x14
	WORD $0xd28a2eee // mov	x14, #20855                     ; =0x5177
	WORD $0xf2a2d82e // movk	x14, #5825, lsl #16
	WORD $0xf2d82d8e // movk	x14, #49516, lsl #32
	WORD $0xf2f7eace // movk	x14, #48982, lsl #48
	WORD $0x4e080dd0 // dup.2d	v16, x14
	WORD $0xb200f3ee // mov	x14, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf28aa28e // movk	x14, #21780
	WORD $0xf2e7f4ae // movk	x14, #16293, lsl #48
	WORD $0x4e080dd1 // dup.2d	v17, x14
	WORD $0x5280002e // mov	w14, #1                         ; =0x1
	WORD $0x4e080dd2 // dup.2d	v18, x14
	WORD $0x5280004e // mov	w14, #2                         ; =0x2
	WORD $0x4e080dd3 // dup.2d	v19, x14

BB0_8:
	WORD $0x3cc105b4 // ldr	q20, [x13], #16
	WORD $0x6e60de95 // fmul.2d	v21, v20, v0
	WORD $0x6e618ab5 // frinta.2d	v21, v21
	WORD $0x4ee1bab6 // fcvtzs.2d	v22, v21
	WORD $0x4e75cc34 // fmla.2d	v20, v1, v21
	WORD $0x4e75cc54 // fmla.2d	v20, v2, v21
	WORD $0x6e74de95 // fmul.2d	v21, v20, v20
	WORD $0x4ea41c97 // mov.16b	v23, v4
	WORD $0x4e75cc77 // fmla.2d	v23, v3, v21
	WORD $0x4ea51cb8 // mov.16b	v24, v5
	WORD $0x4e77ceb8 // fmla.2d	v24, v21, v23
	WORD $0x4ea61cd7 // mov.16b	v23, v6
	WORD $0x4eb01e19 // mov.16b	v25, v16
	WORD $0x4e75ccf9 // fmla.2d	v25, v7, v21
	WORD $0x4e78ceb7 // fmla.2d	v23, v21, v24
	WORD $0x4eb11e38 // mov.16b	v24, v17
	WORD $0x4e79ceb8 // fmla.2d	v24, v21, v25
	WORD $0x6f07f419 // fmov.2d	v25, #-0.50000000
	WORD $0x4e78ceb9 // fmla.2d	v25, v21, v24
	WORD $0x6e75de98 // fmul.2d	v24, v20, v21
	WORD $0x4e78cef4 // fmla.2d	v20, v23, v24
	WORD $0x6f03f617 // fmov.2d	v23, #1.00000000
	WORD $0x4e75cf37 // fmla.2d	v23, v25, v21
	WORD $0x4e321ed5 // and.16b	v21, v22, v18
	WORD $0x4ee09ab5 // cmeq.2d	v21, v21, #0
	WORD $0x4e331ed6 // and.16b	v22, v22, v19
	WORD $0x6ef51ef4 // bif.16b	v20, v23, v21
	WORD $0x4ee09ad5 // cmeq.2d	v21, v22, #0
	WORD $0x6ee0fa96 // fneg.2d	v22, v20
	WORD $0x6ef51ed4 // bif.16b	v20, v22, v21
	WORD $0x3c810534 // str	q20, [x9], #16
	WORD $0xb100098c // adds	x12, x12, #2
	BNE  BB0_8
	CBZ  R11, BB0_12

BB0_10:
	WORD $0xcb0a0108 // sub	x8, x8, x10
	WORD $0xd37df14a // lsl	x10, x10, #3
	WORD $0x8b0a0029 // add	x9, x1, x10
	WORD $0x8b0a000a // add	x10, x0, x10
	WORD $0xd299106b // mov	x11, #51331                     ; =0xc883
	WORD $0xf2adb92b // movk	x11, #28105, lsl #16
	WORD $0xf2cbe60b // movk	x11, #24368, lsl #32
	WORD $0xf2e7fc8b // movk	x11, #16356, lsl #48
	WORD $0x9e670160 // fmov	d0, x11
	WORD $0xd285a30b // mov	x11, #11544                     ; =0x2d18
	WORD $0xf2aa888b // movk	x11, #21572, lsl #16
	WORD $0xf2c43f6b // movk	x11, #8699, lsl #32
	WORD $0xf2f7ff2b // movk	x11, #49145, lsl #48
	WORD $0x9e670161 // fmov	d1, x11
	WORD $0xd28b80eb // mov	x11, #23559                     ; =0x5c07
	WORD $0xf2a6628b // movk	x11, #13076, lsl #16
	WORD $0xf2d4c4cb // movk	x11, #42534, lsl #32
	WORD $0xf2f7922b // movk	x11, #48273, lsl #48
	WORD $0x9e670162 // fmov	d2, x11
	WORD $0xd28ed0eb // mov	x11, #30343                     ; =0x7687
	WORD $0xf2a33feb // movk	x11, #6655, lsl #16
	WORD $0xf2c0340b // movk	x11, #416, lsl #32
	WORD $0xf2f7e54b // movk	x11, #48938, lsl #48
	WORD $0x9e670163 // fmov	d3, x11
	WORD $0xd29bc02b // mov	x11, #56833                     ; =0xde01
	WORD $0xf2af2d8b // movk	x11, #31084, lsl #16
	WORD $0xf2c3bc6b // movk	x11, #7651, lsl #32
	WORD $0xf2e7d8eb // movk	x11, #16071, lsl #48
	WORD $0x9e670164 // fmov	d4, x11
	WORD $0xb200e3eb // mov	x11, #1229782938247303441       ; =0x1111111111111111
	WORD $0xf281d40b // movk	x11, #3744
	WORD $0xf2e7f02b // movk	x11, #16257, lsl #48
	WORD $0x9e670165 // fmov	d5, x11
	WORD $0xb200f3eb // mov	x11, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf28aa92b // movk	x11, #21833
	WORD $0xf2f7f8ab // movk	x11, #49093, lsl #48
	WORD $0x9e670166 // fmov	d6, x11
	WORD $0xd28a2eeb // mov	x11, #20855                     ; =0x5177
	WORD $0xf2a2d82b // movk	x11, #5825, lsl #16
	WORD $0xf2d82d8b // movk	x11, #49516, lsl #32
	WORD $0xf2f7eacb // movk	x11, #48982, lsl #48
	WORD $0x9e670167 // fmov	d7, x11
	WORD $0xd2889eab // mov	x11, #17653                     ; =0x44f5
	WORD $0xf2a3390b // movk	x11, #6600, lsl #16
	WORD $0xf2c0340b // movk	x11, #416, lsl #32
	WORD $0xf2e7df4b // movk	x11, #16122, lsl #48
	WORD $0x9e670170 // fmov	d16, x11
	WORD $0x1e7c1011 // fmov	d17, #-0.50000000
	WORD $0xb200f3eb // mov	x11, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf28aa28b // movk	x11, #21780
	WORD $0xf2e7f4ab // movk	x11, #16293, lsl #48
	WORD $0x1e6e1012 // fmov	d18, #1.00000000
	WORD $0x9e670173 // fmov	d19, x11

BB0_11:
	WORD $0xfc408554 // ldr	d20, [x10], #8
	WORD $0x1e600a95 // fmul	d21, d20, d0
	WORD $0x1e6642b6 // frinta	d22, d21
	WORD $0x1f4152d4 // fmadd	d20, d22, d1, d20
	WORD $0x1f4252d4 // fmadd	d20, d22, d2, d20
	WORD $0x9e6402ab // fcvtas	x11, d21
	WORD $0x1e740a95 // fmul	d21, d20, d20
	WORD $0x1f440eb6 // fmadd	d22, d21, d4, d3
	WORD $0x1f5516d6 // fmadd	d22, d22, d21, d5
	WORD $0x1f551ad6 // fmadd	d22, d22, d21, d6
	WORD $0x1e750a97 // fmul	d23, d20, d21
	WORD $0x1f5652f4 // fmadd	d20, d23, d22, d20
	WORD $0x1f501eb6 // fmadd	d22, d21, d16, d7
	WORD $0x1f554ed6 // fmadd	d22, d22, d21, d19
	WORD $0x1f5546d6 // fmadd	d22, d22, d21, d17
	WORD $0x1f564ab5 // fmadd	d21, d21, d22, d18
	WORD $0xf240017f // tst	x11, #0x1
	WORD $0x1e750e94 // fcsel	d20, d20, d21, eq
	WORD $0x1e614295 // fneg	d21, d20
	WORD $0xf27f017f // tst	x11, #0x2
	WORD $0x1e750e94 // fcsel	d20, d20, d21, eq
	WORD $0xfc008534 // str	d20, [x9], #8
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_11

BB0_12:
	RET
