//go:build !noasm && arm64
// Code generated by hwygen -c. DO NOT EDIT.

package asm

import "unsafe"

// Find_F32 calls the NEON SIMD assembly implementation.
func Find_F32(slice unsafe.Pointer, pvalue unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	find_c_f32_neon(slice, pvalue, plen, pout_result)
}

// Find_F64 calls the NEON SIMD assembly implementation.
func Find_F64(slice unsafe.Pointer, pvalue unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	find_c_f64_neon(slice, pvalue, plen, pout_result)
}

// Find_S32 calls the NEON SIMD assembly implementation.
func Find_S32(slice unsafe.Pointer, pvalue unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	find_c_s32_neon(slice, pvalue, plen, pout_result)
}

// Find_S64 calls the NEON SIMD assembly implementation.
func Find_S64(slice unsafe.Pointer, pvalue unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	find_c_s64_neon(slice, pvalue, plen, pout_result)
}

// Find_U32 calls the NEON SIMD assembly implementation.
func Find_U32(slice unsafe.Pointer, pvalue unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	find_c_u32_neon(slice, pvalue, plen, pout_result)
}

// Find_U64 calls the NEON SIMD assembly implementation.
func Find_U64(slice unsafe.Pointer, pvalue unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	find_c_u64_neon(slice, pvalue, plen, pout_result)
}

// Count_F32 calls the NEON SIMD assembly implementation.
func Count_F32(slice unsafe.Pointer, pvalue unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	count_c_f32_neon(slice, pvalue, plen, pout_result)
}

// Count_F64 calls the NEON SIMD assembly implementation.
func Count_F64(slice unsafe.Pointer, pvalue unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	count_c_f64_neon(slice, pvalue, plen, pout_result)
}

// Count_S32 calls the NEON SIMD assembly implementation.
func Count_S32(slice unsafe.Pointer, pvalue unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	count_c_s32_neon(slice, pvalue, plen, pout_result)
}

// Count_S64 calls the NEON SIMD assembly implementation.
func Count_S64(slice unsafe.Pointer, pvalue unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	count_c_s64_neon(slice, pvalue, plen, pout_result)
}

// Count_U32 calls the NEON SIMD assembly implementation.
func Count_U32(slice unsafe.Pointer, pvalue unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	count_c_u32_neon(slice, pvalue, plen, pout_result)
}

// Count_U64 calls the NEON SIMD assembly implementation.
func Count_U64(slice unsafe.Pointer, pvalue unsafe.Pointer, plen unsafe.Pointer, pout_result unsafe.Pointer) {
	count_c_u64_neon(slice, pvalue, plen, pout_result)
}

