//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   22.1.1
// 	objdump 2.46.0.20260210
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/matmul/asm/baseblockmuladd4_c_f32_neon_arm64.c

TEXT ·blockmuladd4_c_f32_neon(SB), $16-56
	MOVD aT+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD pblockDim+24(FP), R3
	MOVD plen_aT+32(FP), R4
	MOVD plen_b+40(FP), R5
	MOVD plen_c+48(FP), R6
	WORD $0xa9004ff4          // stp	x20, x19, [sp, #-16]!           ; 16-byte Folded Spill [transformed]
	WORD $0xf9400068          // ldr	x8, [x3]
	WORD $0xd37ef509          // lsl	x9, x8, #2
	WORD $0xf100111f          // cmp	x8, #4
	BLT  BB0_20
	WORD $0xd280000c          // mov	x12, #0                         ; =0x0
	WORD $0x9100200a          // add	x10, x0, #8
	WORD $0xaa0003eb          // mov	x11, x0
	B    BB0_3

BB0_2:
	WORD $0x9100118d // add	x13, x12, #4
	WORD $0x91001d8e // add	x14, x12, #7
	WORD $0x9100414a // add	x10, x10, #16
	WORD $0x9100416b // add	x11, x11, #16
	WORD $0xaa0d03ec // mov	x12, x13
	WORD $0xeb0801df // cmp	x14, x8
	BGE  BB0_21

BB0_3:
	WORD $0xb240058f // orr	x15, x12, #0x3
	WORD $0x9b087d8d // mul	x13, x12, x8
	WORD $0xb240018e // orr	x14, x12, #0x1
	WORD $0x9b087dce // mul	x14, x14, x8
	WORD $0xb27f0190 // orr	x16, x12, #0x2
	WORD $0x9b087e10 // mul	x16, x16, x8
	WORD $0x8b0d084d // add	x13, x2, x13, lsl #2
	WORD $0x8b0e084e // add	x14, x2, x14, lsl #2
	WORD $0x9b087df1 // mul	x17, x15, x8
	WORD $0x8b10084f // add	x15, x2, x16, lsl #2
	WORD $0x8b110850 // add	x16, x2, x17, lsl #2
	WORD $0xf100411f // cmp	x8, #16
	BHS  BB0_5
	WORD $0xd2800011 // mov	x17, #0                         ; =0x0
	B    BB0_9

BB0_5:
	WORD $0xd2800004 // mov	x4, #0                          ; =0x0
	WORD $0x91008023 // add	x3, x1, #32
	WORD $0x52800205 // mov	w5, #16                         ; =0x10

BB0_6:
	WORD $0x6f00e414 // movi.2d	v20, #0000000000000000
	WORD $0xaa0503f1 // mov	x17, x5
	WORD $0x6f00e417 // movi.2d	v23, #0000000000000000
	WORD $0xaa0303e5 // mov	x5, x3
	WORD $0x6f00e415 // movi.2d	v21, #0000000000000000
	WORD $0xaa0a03f3 // mov	x19, x10
	WORD $0x6f00e416 // movi.2d	v22, #0000000000000000
	WORD $0xaa0803e6 // mov	x6, x8
	WORD $0x6f00e412 // movi.2d	v18, #0000000000000000
	WORD $0x6f00e413 // movi.2d	v19, #0000000000000000
	WORD $0x6f00e410 // movi.2d	v16, #0000000000000000
	WORD $0x6f00e411 // movi.2d	v17, #0000000000000000
	WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
	WORD $0x6f00e407 // movi.2d	v7, #0000000000000000
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0xaa0a03e7 // mov	x7, x10
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000

BB0_7:
	WORD $0x2d7f6678 // ldp	s24, s25, [x19, #-8]
	WORD $0x4dc9c8fa // ld1r.4s	{ v26 }, [x7], x9
	WORD $0xbd40067b // ldr	s27, [x19, #4]
	WORD $0xad7f74bc // ldp	q28, q29, [x5, #-32]
	WORD $0xad407cbe // ldp	q30, q31, [x5]
	WORD $0x4f981394 // fmla.4s	v20, v28, v24[0]
	WORD $0x4f9813b7 // fmla.4s	v23, v29, v24[0]
	WORD $0x4f9813d5 // fmla.4s	v21, v30, v24[0]
	WORD $0x4f9813f6 // fmla.4s	v22, v31, v24[0]
	WORD $0x4f991392 // fmla.4s	v18, v28, v25[0]
	WORD $0x4f9913b3 // fmla.4s	v19, v29, v25[0]
	WORD $0x4f9913d0 // fmla.4s	v16, v30, v25[0]
	WORD $0x4f9913f1 // fmla.4s	v17, v31, v25[0]
	WORD $0x4e3acf86 // fmla.4s	v6, v28, v26
	WORD $0x4e3acfa7 // fmla.4s	v7, v29, v26
	WORD $0x4e3acfc4 // fmla.4s	v4, v30, v26
	WORD $0x4e3acfe5 // fmla.4s	v5, v31, v26
	WORD $0x4f9b1382 // fmla.4s	v2, v28, v27[0]
	WORD $0x4f9b13a3 // fmla.4s	v3, v29, v27[0]
	WORD $0x4f9b13c0 // fmla.4s	v0, v30, v27[0]
	WORD $0x4f9b13e1 // fmla.4s	v1, v31, v27[0]
	WORD $0x8b0900a5 // add	x5, x5, x9
	WORD $0xaa0703f3 // mov	x19, x7
	WORD $0xf10004c6 // subs	x6, x6, #1
	BNE  BB0_7
	WORD $0xd37ef484 // lsl	x4, x4, #2
	WORD $0x8b0401a5 // add	x5, x13, x4
	WORD $0xad4064b8 // ldp	q24, q25, [x5]
	WORD $0x4e38d694 // fadd.4s	v20, v20, v24
	WORD $0x4e39d6f7 // fadd.4s	v23, v23, v25
	WORD $0xad005cb4 // stp	q20, q23, [x5]
	WORD $0xad415cb4 // ldp	q20, q23, [x5, #32]
	WORD $0x4e34d6b4 // fadd.4s	v20, v21, v20
	WORD $0x4e37d6d5 // fadd.4s	v21, v22, v23
	WORD $0xad0154b4 // stp	q20, q21, [x5, #32]
	WORD $0x8b0401c5 // add	x5, x14, x4
	WORD $0xad4054b4 // ldp	q20, q21, [x5]
	WORD $0x4e34d652 // fadd.4s	v18, v18, v20
	WORD $0x4e35d673 // fadd.4s	v19, v19, v21
	WORD $0xad004cb2 // stp	q18, q19, [x5]
	WORD $0xad414cb2 // ldp	q18, q19, [x5, #32]
	WORD $0x4e32d610 // fadd.4s	v16, v16, v18
	WORD $0x4e33d631 // fadd.4s	v17, v17, v19
	WORD $0xad0144b0 // stp	q16, q17, [x5, #32]
	WORD $0x8b0401e5 // add	x5, x15, x4
	WORD $0xad4044b0 // ldp	q16, q17, [x5]
	WORD $0x4e30d4c6 // fadd.4s	v6, v6, v16
	WORD $0x4e31d4e7 // fadd.4s	v7, v7, v17
	WORD $0xad001ca6 // stp	q6, q7, [x5]
	WORD $0xad411ca6 // ldp	q6, q7, [x5, #32]
	WORD $0x4e26d484 // fadd.4s	v4, v4, v6
	WORD $0x4e27d4a5 // fadd.4s	v5, v5, v7
	WORD $0xad0114a4 // stp	q4, q5, [x5, #32]
	WORD $0x8b040204 // add	x4, x16, x4
	WORD $0xad401484 // ldp	q4, q5, [x4]
	WORD $0x4e24d442 // fadd.4s	v2, v2, v4
	WORD $0x4e25d463 // fadd.4s	v3, v3, v5
	WORD $0xad000c82 // stp	q2, q3, [x4]
	WORD $0xad410c82 // ldp	q2, q3, [x4, #32]
	WORD $0x4e22d400 // fadd.4s	v0, v0, v2
	WORD $0x4e23d421 // fadd.4s	v1, v1, v3
	WORD $0xad010480 // stp	q0, q1, [x4, #32]
	WORD $0x91004225 // add	x5, x17, #16
	WORD $0x91010063 // add	x3, x3, #64
	WORD $0xaa1103e4 // mov	x4, x17
	WORD $0xeb0800bf // cmp	x5, x8
	BLE  BB0_6

BB0_9:
	WORD $0xb27e0225 // orr	x5, x17, #0x4
	WORD $0xeb0800bf // cmp	x5, x8
	BLE  BB0_11
	WORD $0xaa1103e3 // mov	x3, x17
	B    BB0_15

BB0_11:
	WORD $0x8b110824 // add	x4, x1, x17, lsl #2

BB0_12:
	WORD $0xaa0503e3 // mov	x3, x5
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0xaa0a03e5 // mov	x5, x10
	WORD $0xaa0403e6 // mov	x6, x4
	WORD $0xaa0803e7 // mov	x7, x8
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000

BB0_13:
	WORD $0x2d7f14a4 // ldp	s4, s5, [x5, #-8]
	WORD $0x2d401ca6 // ldp	s6, s7, [x5]
	WORD $0x3dc000d0 // ldr	q16, [x6]
	WORD $0x4f841201 // fmla.4s	v1, v16, v4[0]
	WORD $0x4f851203 // fmla.4s	v3, v16, v5[0]
	WORD $0x4f861202 // fmla.4s	v2, v16, v6[0]
	WORD $0x4f871200 // fmla.4s	v0, v16, v7[0]
	WORD $0x8b0900c6 // add	x6, x6, x9
	WORD $0x8b0900a5 // add	x5, x5, x9
	WORD $0xf10004e7 // subs	x7, x7, #1
	BNE  BB0_13
	WORD $0xd37ef631 // lsl	x17, x17, #2
	WORD $0x3cf169a4 // ldr	q4, [x13, x17]
	WORD $0x4e24d421 // fadd.4s	v1, v1, v4
	WORD $0x3cb169a1 // str	q1, [x13, x17]
	WORD $0x3cf169c1 // ldr	q1, [x14, x17]
	WORD $0x4e21d461 // fadd.4s	v1, v3, v1
	WORD $0x3cb169c1 // str	q1, [x14, x17]
	WORD $0x3cf169e1 // ldr	q1, [x15, x17]
	WORD $0x4e21d441 // fadd.4s	v1, v2, v1
	WORD $0x3cb169e1 // str	q1, [x15, x17]
	WORD $0x3cf16a01 // ldr	q1, [x16, x17]
	WORD $0x4e21d400 // fadd.4s	v0, v0, v1
	WORD $0x3cb16a00 // str	q0, [x16, x17]
	WORD $0x91001065 // add	x5, x3, #4
	WORD $0x91004084 // add	x4, x4, #16
	WORD $0xaa0303f1 // mov	x17, x3
	WORD $0xeb0800bf // cmp	x5, x8
	BLE  BB0_12

BB0_15:
	WORD $0xeb08007f // cmp	x3, x8
	BGE  BB0_2
	WORD $0x8b030831 // add	x17, x1, x3, lsl #2

BB0_17:
	WORD $0xd2800004 // mov	x4, #0                          ; =0x0
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0xaa0803e5 // mov	x5, x8

BB0_18:
	WORD $0xbc646a21 // ldr	s1, [x17, x4]
	WORD $0x3ce46962 // ldr	q2, [x11, x4]
	WORD $0x4f811040 // fmla.4s	v0, v2, v1[0]
	WORD $0x8b090084 // add	x4, x4, x9
	WORD $0xf10004a5 // subs	x5, x5, #1
	BNE  BB0_18
	WORD $0xbc6379a1 // ldr	s1, [x13, x3, lsl #2]
	WORD $0x1e212801 // fadd	s1, s0, s1
	WORD $0xbc2379a1 // str	s1, [x13, x3, lsl #2]
	WORD $0xbc6379c1 // ldr	s1, [x14, x3, lsl #2]
	WORD $0x5e0c0402 // mov	s2, v0[1]
	WORD $0x1e212841 // fadd	s1, s2, s1
	WORD $0xbc2379c1 // str	s1, [x14, x3, lsl #2]
	WORD $0xbc6379e1 // ldr	s1, [x15, x3, lsl #2]
	WORD $0x5e140402 // mov	s2, v0[2]
	WORD $0x1e212841 // fadd	s1, s2, s1
	WORD $0xbc2379e1 // str	s1, [x15, x3, lsl #2]
	WORD $0xbc637a01 // ldr	s1, [x16, x3, lsl #2]
	WORD $0x5e1c0400 // mov	s0, v0[3]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0xbc237a00 // str	s0, [x16, x3, lsl #2]
	WORD $0x91000463 // add	x3, x3, #1
	WORD $0x91001231 // add	x17, x17, #4
	WORD $0xeb08007f // cmp	x3, x8
	BNE  BB0_17
	B    BB0_2

BB0_20:
	WORD $0xd280000d // mov	x13, #0                         ; =0x0

BB0_21:
	WORD $0xeb0801bf // cmp	x13, x8
	BGE  BB0_47
	WORD $0x8b0d080a // add	x10, x0, x13, lsl #2
	WORD $0x9b087dab // mul	x11, x13, x8
	WORD $0x8b0b084b // add	x11, x2, x11, lsl #2
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	B    BB0_24

BB0_23:
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0x9100114a // add	x10, x10, #4
	WORD $0x8b09016b // add	x11, x11, x9
	WORD $0xeb0801bf // cmp	x13, x8
	BEQ  BB0_47

BB0_24:
	WORD $0x9b087dac // mul	x12, x13, x8
	WORD $0x8b0c084c // add	x12, x2, x12, lsl #2
	WORD $0xf100411f // cmp	x8, #16
	BGE  BB0_26
	WORD $0xd280000e // mov	x14, #0                         ; =0x0
	B    BB0_30

BB0_26:
	WORD $0xd2800010 // mov	x16, #0                         ; =0x0
	WORD $0x9100802f // add	x15, x1, #32
	WORD $0x52800211 // mov	w17, #16                        ; =0x10

BB0_27:
	WORD $0xaa1103ee // mov	x14, x17
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0xaa0f03f1 // mov	x17, x15
	WORD $0xaa0a03e0 // mov	x0, x10
	WORD $0xaa0803e3 // mov	x3, x8
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000

BB0_28:
	WORD $0x4dc9c806 // ld1r.4s	{ v6 }, [x0], x9
	WORD $0xad7f4227 // ldp	q7, q16, [x17, #-32]
	WORD $0x4e26cce5 // fmla.4s	v5, v7, v6
	WORD $0x4e26ce04 // fmla.4s	v4, v16, v6
	WORD $0xad404227 // ldp	q7, q16, [x17]
	WORD $0x4e26cce3 // fmla.4s	v3, v7, v6
	WORD $0x4e26ce02 // fmla.4s	v2, v16, v6
	WORD $0x8b090231 // add	x17, x17, x9
	WORD $0xf1000463 // subs	x3, x3, #1
	BNE  BB0_28
	WORD $0x8b100990 // add	x16, x12, x16, lsl #2
	WORD $0xad401e06 // ldp	q6, q7, [x16]
	WORD $0x4e26d4a5 // fadd.4s	v5, v5, v6
	WORD $0x4e27d484 // fadd.4s	v4, v4, v7
	WORD $0xad001205 // stp	q5, q4, [x16]
	WORD $0xad411604 // ldp	q4, q5, [x16, #32]
	WORD $0x4e24d463 // fadd.4s	v3, v3, v4
	WORD $0x4e25d442 // fadd.4s	v2, v2, v5
	WORD $0xad010a03 // stp	q3, q2, [x16, #32]
	WORD $0x910041d1 // add	x17, x14, #16
	WORD $0x910101ef // add	x15, x15, #64
	WORD $0xaa0e03f0 // mov	x16, x14
	WORD $0xeb08023f // cmp	x17, x8
	BLE  BB0_27

BB0_30:
	WORD $0xb27e01d1 // orr	x17, x14, #0x4
	WORD $0xeb08023f // cmp	x17, x8
	BLE  BB0_32
	WORD $0xaa0e03ef // mov	x15, x14
	B    BB0_37

BB0_32:
	WORD $0xf100051f // cmp	x8, #1
	BLT  BB0_43
	WORD $0x8b0e0830 // add	x16, x1, x14, lsl #2

BB0_34:
	WORD $0xd2800000 // mov	x0, #0                          ; =0x0
	WORD $0xaa1103ef // mov	x15, x17
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0xaa0803f1 // mov	x17, x8

BB0_35:
	WORD $0xbc606943 // ldr	s3, [x10, x0]
	WORD $0x3ce06a04 // ldr	q4, [x16, x0]
	WORD $0x4f831082 // fmla.4s	v2, v4, v3[0]
	WORD $0x8b090000 // add	x0, x0, x9
	WORD $0xf1000631 // subs	x17, x17, #1
	BNE  BB0_35
	WORD $0xd37ef5ce // lsl	x14, x14, #2
	WORD $0x3cee6983 // ldr	q3, [x12, x14]
	WORD $0x4e23d442 // fadd.4s	v2, v2, v3
	WORD $0x3cae6982 // str	q2, [x12, x14]
	WORD $0x910011f1 // add	x17, x15, #4
	WORD $0x91004210 // add	x16, x16, #16
	WORD $0xaa0f03ee // mov	x14, x15
	WORD $0xeb08023f // cmp	x17, x8
	BLE  BB0_34

BB0_37:
	WORD $0xeb0801ff // cmp	x15, x8
	BGE  BB0_23
	WORD $0xf100051f // cmp	x8, #1
	BLT  BB0_44
	WORD $0x8b0f082e // add	x14, x1, x15, lsl #2

BB0_40:
	WORD $0xd2800010 // mov	x16, #0                         ; =0x0
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0xaa0803f1 // mov	x17, x8

BB0_41:
	WORD $0xbc706943 // ldr	s3, [x10, x16]
	WORD $0xbc7069c4 // ldr	s4, [x14, x16]
	WORD $0x1f040862 // fmadd	s2, s3, s4, s2
	WORD $0x8b090210 // add	x16, x16, x9
	WORD $0xf1000631 // subs	x17, x17, #1
	BNE  BB0_41
	WORD $0xbc6f7983 // ldr	s3, [x12, x15, lsl #2]
	WORD $0x1e232842 // fadd	s2, s2, s3
	WORD $0xbc2f7982 // str	s2, [x12, x15, lsl #2]
	WORD $0x910005ef // add	x15, x15, #1
	WORD $0x910011ce // add	x14, x14, #4
	WORD $0xeb0801ff // cmp	x15, x8
	BNE  BB0_40
	B    BB0_23

BB0_43:
	WORD $0xd37ef5ce // lsl	x14, x14, #2
	WORD $0x3cee6982 // ldr	q2, [x12, x14]
	WORD $0x4e21d442 // fadd.4s	v2, v2, v1
	WORD $0x3cae6982 // str	q2, [x12, x14]
	WORD $0xeb08023f // cmp	x17, x8
	BGE  BB0_23
	B    BB0_45

BB0_44:
	WORD $0xaa0f03f1 // mov	x17, x15

BB0_45:
	WORD $0xcb11010c // sub	x12, x8, x17
	WORD $0x8b11096e // add	x14, x11, x17, lsl #2

BB0_46:
	WORD $0xbd4001c2 // ldr	s2, [x14]
	WORD $0x1e202842 // fadd	s2, s2, s0
	WORD $0xbc0045c2 // str	s2, [x14], #4
	WORD $0xf100058c // subs	x12, x12, #1
	BNE  BB0_46
	B    BB0_23

BB0_47:
	WORD $0xa9404ff4 // ldp	x20, x19, [sp], #16             ; 16-byte Folded Reload [transformed]
	RET
