//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   22.1.0
// 	objdump 2.46.0.20260210
// flags: -march=armv8.6-a+bf16+simd -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/matmul/asm/baseblockmuladd2_c_bf16_neon_arm64.c

TEXT ·blockmuladd2_c_bf16_neon(SB), $32-56
	MOVD aT+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD pblockDim+24(FP), R3
	MOVD plen_aT+32(FP), R4
	MOVD plen_b+40(FP), R5
	MOVD plen_c+48(FP), R6
	WORD $0x6d002beb          // stp	d11, d10, [sp, #-32]!           ; 16-byte Folded Spill [transformed]
	WORD $0x6d0123e9          // stp	d9, d8, [sp, #16]               ; 16-byte Folded Spill
	WORD $0xf9400068          // ldr	x8, [x3]
	WORD $0xd37ff909          // lsl	x9, x8, #1
	WORD $0xf100091f          // cmp	x8, #2
	BLT  BB0_20
	WORD $0xd280000c          // mov	x12, #0                         ; =0x0
	WORD $0x9100080a          // add	x10, x0, #2
	WORD $0x528fffeb          // mov	w11, #32767                     ; =0x7fff
	WORD $0x4f000420          // movi.4s	v0, #1
	WORD $0x4f03c7e1          // movi.4s	v1, #127, msl #8
	WORD $0xaa0003ed          // mov	x13, x0
	B    BB0_3

BB0_2:
	WORD $0x9100098e // add	x14, x12, #2
	WORD $0x91000d8f // add	x15, x12, #3
	WORD $0x9100114a // add	x10, x10, #4
	WORD $0x910011ad // add	x13, x13, #4
	WORD $0xaa0e03ec // mov	x12, x14
	WORD $0xeb0801ff // cmp	x15, x8
	BGE  BB0_21

BB0_3:
	WORD $0xb240018e // orr	x14, x12, #0x1
	WORD $0x9b087d8f // mul	x15, x12, x8
	WORD $0x9b087dd0 // mul	x16, x14, x8
	WORD $0x8b0f044e // add	x14, x2, x15, lsl #1
	WORD $0x8b10044f // add	x15, x2, x16, lsl #1
	WORD $0xf100811f // cmp	x8, #32
	BHS  BB0_5
	WORD $0xd2800010 // mov	x16, #0                         ; =0x0
	B    BB0_9

BB0_5:
	WORD $0xd2800003 // mov	x3, #0                          ; =0x0
	WORD $0x91008031 // add	x17, x1, #32
	WORD $0x52800404 // mov	w4, #32                         ; =0x20

BB0_6:
	WORD $0x6f00e418 // movi.2d	v24, #0000000000000000
	WORD $0xaa0403f0 // mov	x16, x4
	WORD $0x6f00e419 // movi.2d	v25, #0000000000000000
	WORD $0xaa1103e4 // mov	x4, x17
	WORD $0x6f00e416 // movi.2d	v22, #0000000000000000
	WORD $0xaa0a03e5 // mov	x5, x10
	WORD $0x6f00e417 // movi.2d	v23, #0000000000000000
	WORD $0xaa0803e6 // mov	x6, x8
	WORD $0x6f00e415 // movi.2d	v21, #0000000000000000
	WORD $0x6f00e414 // movi.2d	v20, #0000000000000000
	WORD $0x6f00e413 // movi.2d	v19, #0000000000000000
	WORD $0x6f00e412 // movi.2d	v18, #0000000000000000
	WORD $0x6f00e411 // movi.2d	v17, #0000000000000000
	WORD $0x6f00e410 // movi.2d	v16, #0000000000000000
	WORD $0x6f00e407 // movi.2d	v7, #0000000000000000
	WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000

BB0_7:
	WORD $0xd10008a7 // sub	x7, x5, #2
	WORD $0xad7f6c9a // ldp	q26, q27, [x4, #-32]
	WORD $0xad40749c // ldp	q28, q29, [x4]
	WORD $0x0d40c4fe // ld1r.4h	{ v30 }, [x7]
	WORD $0x2e613bde // shll.4s	v30, v30, #16
	WORD $0x2e613b5f // shll.4s	v31, v26, #16
	WORD $0x4e3ecff8 // fmla.4s	v24, v31, v30
	WORD $0x6e613b5a // shll2.4s	v26, v26, #16
	WORD $0x4e3ecf59 // fmla.4s	v25, v26, v30
	WORD $0x2e613b68 // shll.4s	v8, v27, #16
	WORD $0x4e3ecd16 // fmla.4s	v22, v8, v30
	WORD $0x6e613b7b // shll2.4s	v27, v27, #16
	WORD $0x4e3ecf77 // fmla.4s	v23, v27, v30
	WORD $0x2e613b89 // shll.4s	v9, v28, #16
	WORD $0x4e3ecd35 // fmla.4s	v21, v9, v30
	WORD $0x6e613b9c // shll2.4s	v28, v28, #16
	WORD $0x4e3ecf94 // fmla.4s	v20, v28, v30
	WORD $0x2e613baa // shll.4s	v10, v29, #16
	WORD $0x4e3ecd53 // fmla.4s	v19, v10, v30
	WORD $0x6e613bbd // shll2.4s	v29, v29, #16
	WORD $0x0dc9c4ab // ld1r.4h	{ v11 }, [x5], x9
	WORD $0x4e3ecfb2 // fmla.4s	v18, v29, v30
	WORD $0x2e61397e // shll.4s	v30, v11, #16
	WORD $0x4e3ecff1 // fmla.4s	v17, v31, v30
	WORD $0x4e3ecf50 // fmla.4s	v16, v26, v30
	WORD $0x4e3ecd07 // fmla.4s	v7, v8, v30
	WORD $0x4e3ecf66 // fmla.4s	v6, v27, v30
	WORD $0x4e3ecd25 // fmla.4s	v5, v9, v30
	WORD $0x4e3ecf84 // fmla.4s	v4, v28, v30
	WORD $0x4e3ecd43 // fmla.4s	v3, v10, v30
	WORD $0x4e3ecfa2 // fmla.4s	v2, v29, v30
	WORD $0x8b090084 // add	x4, x4, x9
	WORD $0xf10004c6 // subs	x6, x6, #1
	BNE  BB0_7
	WORD $0xd37ff863 // lsl	x3, x3, #1
	WORD $0x8b0301c4 // add	x4, x14, x3
	WORD $0xad406c9a // ldp	q26, q27, [x4]
	WORD $0x2e613b5c // shll.4s	v28, v26, #16
	WORD $0x4e3cd718 // fadd.4s	v24, v24, v28
	WORD $0x6e613b5a // shll2.4s	v26, v26, #16
	WORD $0x4e3ad739 // fadd.4s	v25, v25, v26
	WORD $0x6f30073a // ushr.4s	v26, v25, #16
	WORD $0x4e201f5a // and.16b	v26, v26, v0
	WORD $0x4eba8739 // add.4s	v25, v25, v26
	WORD $0x6f30071a // ushr.4s	v26, v24, #16
	WORD $0x4e201f5a // and.16b	v26, v26, v0
	WORD $0x4eba8718 // add.4s	v24, v24, v26
	WORD $0x0e614318 // addhn.4h	v24, v24, v1
	WORD $0x4e614338 // addhn2.8h	v24, v25, v1
	WORD $0x2e613b79 // shll.4s	v25, v27, #16
	WORD $0x4e39d6d6 // fadd.4s	v22, v22, v25
	WORD $0x6e613b79 // shll2.4s	v25, v27, #16
	WORD $0x4e39d6f7 // fadd.4s	v23, v23, v25
	WORD $0x6f3006f9 // ushr.4s	v25, v23, #16
	WORD $0x4e201f39 // and.16b	v25, v25, v0
	WORD $0x4eb986f7 // add.4s	v23, v23, v25
	WORD $0x6f3006d9 // ushr.4s	v25, v22, #16
	WORD $0x4e201f39 // and.16b	v25, v25, v0
	WORD $0x4eb986d6 // add.4s	v22, v22, v25
	WORD $0x0e6142d6 // addhn.4h	v22, v22, v1
	WORD $0x4e6142f6 // addhn2.8h	v22, v23, v1
	WORD $0xad005898 // stp	q24, q22, [x4]
	WORD $0xad415c96 // ldp	q22, q23, [x4, #32]
	WORD $0x2e613ad8 // shll.4s	v24, v22, #16
	WORD $0x4e38d6b5 // fadd.4s	v21, v21, v24
	WORD $0x6e613ad6 // shll2.4s	v22, v22, #16
	WORD $0x4e36d694 // fadd.4s	v20, v20, v22
	WORD $0x6f300696 // ushr.4s	v22, v20, #16
	WORD $0x4e201ed6 // and.16b	v22, v22, v0
	WORD $0x4eb68694 // add.4s	v20, v20, v22
	WORD $0x6f3006b6 // ushr.4s	v22, v21, #16
	WORD $0x4e201ed6 // and.16b	v22, v22, v0
	WORD $0x4eb686b5 // add.4s	v21, v21, v22
	WORD $0x0e6142b5 // addhn.4h	v21, v21, v1
	WORD $0x4e614295 // addhn2.8h	v21, v20, v1
	WORD $0x2e613af4 // shll.4s	v20, v23, #16
	WORD $0x4e34d673 // fadd.4s	v19, v19, v20
	WORD $0x6e613af4 // shll2.4s	v20, v23, #16
	WORD $0x4e34d652 // fadd.4s	v18, v18, v20
	WORD $0x6f300654 // ushr.4s	v20, v18, #16
	WORD $0x4e201e94 // and.16b	v20, v20, v0
	WORD $0x4eb48652 // add.4s	v18, v18, v20
	WORD $0x6f300674 // ushr.4s	v20, v19, #16
	WORD $0x4e201e94 // and.16b	v20, v20, v0
	WORD $0x4eb48673 // add.4s	v19, v19, v20
	WORD $0x0e614273 // addhn.4h	v19, v19, v1
	WORD $0x4e614253 // addhn2.8h	v19, v18, v1
	WORD $0xad014c95 // stp	q21, q19, [x4, #32]
	WORD $0x8b0301e3 // add	x3, x15, x3
	WORD $0xad404c72 // ldp	q18, q19, [x3]
	WORD $0x2e613a54 // shll.4s	v20, v18, #16
	WORD $0x4e34d631 // fadd.4s	v17, v17, v20
	WORD $0x6e613a52 // shll2.4s	v18, v18, #16
	WORD $0x4e32d610 // fadd.4s	v16, v16, v18
	WORD $0x6f300612 // ushr.4s	v18, v16, #16
	WORD $0x4e201e52 // and.16b	v18, v18, v0
	WORD $0x4eb28610 // add.4s	v16, v16, v18
	WORD $0x6f300632 // ushr.4s	v18, v17, #16
	WORD $0x4e201e52 // and.16b	v18, v18, v0
	WORD $0x4eb28631 // add.4s	v17, v17, v18
	WORD $0x0e614231 // addhn.4h	v17, v17, v1
	WORD $0x4e614211 // addhn2.8h	v17, v16, v1
	WORD $0x2e613a70 // shll.4s	v16, v19, #16
	WORD $0x4e30d4e7 // fadd.4s	v7, v7, v16
	WORD $0x6e613a70 // shll2.4s	v16, v19, #16
	WORD $0x4e30d4c6 // fadd.4s	v6, v6, v16
	WORD $0x6f3004d0 // ushr.4s	v16, v6, #16
	WORD $0x4e201e10 // and.16b	v16, v16, v0
	WORD $0x4eb084c6 // add.4s	v6, v6, v16
	WORD $0x6f3004f0 // ushr.4s	v16, v7, #16
	WORD $0x4e201e10 // and.16b	v16, v16, v0
	WORD $0x4eb084e7 // add.4s	v7, v7, v16
	WORD $0x0e6140e7 // addhn.4h	v7, v7, v1
	WORD $0x4e6140c7 // addhn2.8h	v7, v6, v1
	WORD $0xad001c71 // stp	q17, q7, [x3]
	WORD $0xad411c66 // ldp	q6, q7, [x3, #32]
	WORD $0x2e6138d0 // shll.4s	v16, v6, #16
	WORD $0x4e30d4a5 // fadd.4s	v5, v5, v16
	WORD $0x6e6138c6 // shll2.4s	v6, v6, #16
	WORD $0x4e26d484 // fadd.4s	v4, v4, v6
	WORD $0x6f300486 // ushr.4s	v6, v4, #16
	WORD $0x4e201cc6 // and.16b	v6, v6, v0
	WORD $0x4ea68484 // add.4s	v4, v4, v6
	WORD $0x6f3004a6 // ushr.4s	v6, v5, #16
	WORD $0x4e201cc6 // and.16b	v6, v6, v0
	WORD $0x4ea684a5 // add.4s	v5, v5, v6
	WORD $0x0e6140a5 // addhn.4h	v5, v5, v1
	WORD $0x4e614085 // addhn2.8h	v5, v4, v1
	WORD $0x2e6138e4 // shll.4s	v4, v7, #16
	WORD $0x4e24d463 // fadd.4s	v3, v3, v4
	WORD $0x6e6138e4 // shll2.4s	v4, v7, #16
	WORD $0x4e24d442 // fadd.4s	v2, v2, v4
	WORD $0x6f300444 // ushr.4s	v4, v2, #16
	WORD $0x4e201c84 // and.16b	v4, v4, v0
	WORD $0x4ea48442 // add.4s	v2, v2, v4
	WORD $0x6f300464 // ushr.4s	v4, v3, #16
	WORD $0x4e201c84 // and.16b	v4, v4, v0
	WORD $0x4ea48463 // add.4s	v3, v3, v4
	WORD $0x0e614063 // addhn.4h	v3, v3, v1
	WORD $0x4e614043 // addhn2.8h	v3, v2, v1
	WORD $0xad010c65 // stp	q5, q3, [x3, #32]
	WORD $0x91008204 // add	x4, x16, #32
	WORD $0x91010231 // add	x17, x17, #64
	WORD $0xaa1003e3 // mov	x3, x16
	WORD $0xeb08009f // cmp	x4, x8
	BLE  BB0_6

BB0_9:
	WORD $0xb27d0205 // orr	x5, x16, #0x8
	WORD $0xeb0800bf // cmp	x5, x8
	BLE  BB0_11
	WORD $0xaa1003f1 // mov	x17, x16
	B    BB0_15

BB0_11:
	WORD $0x8b100423 // add	x3, x1, x16, lsl #1

BB0_12:
	WORD $0xd2800004 // mov	x4, #0                          ; =0x0
	WORD $0xaa0503f1 // mov	x17, x5
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0xaa0803e5 // mov	x5, x8
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000

BB0_13:
	WORD $0x8b0401a6 // add	x6, x13, x4
	WORD $0x8b040147 // add	x7, x10, x4
	WORD $0x3ce46866 // ldr	q6, [x3, x4]
	WORD $0x0d40c4c7 // ld1r.4h	{ v7 }, [x6]
	WORD $0x2e6138e7 // shll.4s	v7, v7, #16
	WORD $0x2e6138d0 // shll.4s	v16, v6, #16
	WORD $0x4e27ce04 // fmla.4s	v4, v16, v7
	WORD $0x6e6138c6 // shll2.4s	v6, v6, #16
	WORD $0x0d40c4f1 // ld1r.4h	{ v17 }, [x7]
	WORD $0x4e27ccc5 // fmla.4s	v5, v6, v7
	WORD $0x2e613a27 // shll.4s	v7, v17, #16
	WORD $0x4e27ce03 // fmla.4s	v3, v16, v7
	WORD $0x4e27ccc2 // fmla.4s	v2, v6, v7
	WORD $0x8b090084 // add	x4, x4, x9
	WORD $0xf10004a5 // subs	x5, x5, #1
	BNE  BB0_13
	WORD $0xd37ffa10 // lsl	x16, x16, #1
	WORD $0x3cf069c6 // ldr	q6, [x14, x16]
	WORD $0x2e6138c7 // shll.4s	v7, v6, #16
	WORD $0x4e27d484 // fadd.4s	v4, v4, v7
	WORD $0x6e6138c6 // shll2.4s	v6, v6, #16
	WORD $0x4e26d4a5 // fadd.4s	v5, v5, v6
	WORD $0x6f3004a6 // ushr.4s	v6, v5, #16
	WORD $0x4e201cc6 // and.16b	v6, v6, v0
	WORD $0x4ea684a5 // add.4s	v5, v5, v6
	WORD $0x6f300486 // ushr.4s	v6, v4, #16
	WORD $0x4e201cc6 // and.16b	v6, v6, v0
	WORD $0x4ea68484 // add.4s	v4, v4, v6
	WORD $0x0e614084 // addhn.4h	v4, v4, v1
	WORD $0x4e6140a4 // addhn2.8h	v4, v5, v1
	WORD $0x3cb069c4 // str	q4, [x14, x16]
	WORD $0x3cf069e4 // ldr	q4, [x15, x16]
	WORD $0x2e613885 // shll.4s	v5, v4, #16
	WORD $0x4e25d463 // fadd.4s	v3, v3, v5
	WORD $0x6e613884 // shll2.4s	v4, v4, #16
	WORD $0x4e24d442 // fadd.4s	v2, v2, v4
	WORD $0x6f300444 // ushr.4s	v4, v2, #16
	WORD $0x4e201c84 // and.16b	v4, v4, v0
	WORD $0x4ea48442 // add.4s	v2, v2, v4
	WORD $0x6f300464 // ushr.4s	v4, v3, #16
	WORD $0x4e201c84 // and.16b	v4, v4, v0
	WORD $0x4ea48463 // add.4s	v3, v3, v4
	WORD $0x0e614063 // addhn.4h	v3, v3, v1
	WORD $0x4e614043 // addhn2.8h	v3, v2, v1
	WORD $0x3cb069e3 // str	q3, [x15, x16]
	WORD $0x91002225 // add	x5, x17, #8
	WORD $0x91004063 // add	x3, x3, #16
	WORD $0xaa1103f0 // mov	x16, x17
	WORD $0xeb0800bf // cmp	x5, x8
	BLE  BB0_12

BB0_15:
	WORD $0xeb08023f // cmp	x17, x8
	BGE  BB0_2
	WORD $0x8b110430 // add	x16, x1, x17, lsl #1

BB0_17:
	WORD $0xd2800003 // mov	x3, #0                          ; =0x0
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0xaa0803e4 // mov	x4, x8
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000

BB0_18:
	WORD $0x78636a05 // ldrh	w5, [x16, x3]
	WORD $0x786369a6 // ldrh	w6, [x13, x3]
	WORD $0x1b057cc6 // mul	w6, w6, w5
	WORD $0x1e2300c4 // ucvtf	s4, w6
	WORD $0x1e242863 // fadd	s3, s3, s4
	WORD $0x78636946 // ldrh	w6, [x10, x3]
	WORD $0x1b057cc5 // mul	w5, w6, w5
	WORD $0x1e2300a4 // ucvtf	s4, w5
	WORD $0x1e242842 // fadd	s2, s2, s4
	WORD $0x8b090063 // add	x3, x3, x9
	WORD $0xf1000484 // subs	x4, x4, #1
	BNE  BB0_18
	WORD $0x787179c3 // ldrh	w3, [x14, x17, lsl #1]
	WORD $0x53103c63 // lsl	w3, w3, #16
	WORD $0x1e270064 // fmov	s4, w3
	WORD $0x1e242863 // fadd	s3, s3, s4
	WORD $0x1e260063 // fmov	w3, s3
	WORD $0x53104064 // ubfx	w4, w3, #16, #1
	WORD $0x0b040063 // add	w3, w3, w4
	WORD $0x0b0b0063 // add	w3, w3, w11
	WORD $0x53107c63 // lsr	w3, w3, #16
	WORD $0x783179c3 // strh	w3, [x14, x17, lsl #1]
	WORD $0x787179e3 // ldrh	w3, [x15, x17, lsl #1]
	WORD $0x53103c63 // lsl	w3, w3, #16
	WORD $0x1e270063 // fmov	s3, w3
	WORD $0x1e232842 // fadd	s2, s2, s3
	WORD $0x1e260043 // fmov	w3, s2
	WORD $0x53104064 // ubfx	w4, w3, #16, #1
	WORD $0x0b040063 // add	w3, w3, w4
	WORD $0x0b0b0063 // add	w3, w3, w11
	WORD $0x53107c63 // lsr	w3, w3, #16
	WORD $0x783179e3 // strh	w3, [x15, x17, lsl #1]
	WORD $0x91000631 // add	x17, x17, #1
	WORD $0x91000a10 // add	x16, x16, #2
	WORD $0xeb08023f // cmp	x17, x8
	BNE  BB0_17
	B    BB0_2

BB0_20:
	WORD $0xd280000e // mov	x14, #0                         ; =0x0

BB0_21:
	WORD $0xeb0801df // cmp	x14, x8
	BGE  BB0_44
	WORD $0x9b087dcc // mul	x12, x14, x8
	WORD $0x8b0e040a // add	x10, x0, x14, lsl #1
	WORD $0x8b0c044b // add	x11, x2, x12, lsl #1
	WORD $0xf100811f // cmp	x8, #32
	BGE  BB0_24
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	B    BB0_28

BB0_24:
	WORD $0xd280000f // mov	x15, #0                         ; =0x0
	WORD $0x9100802e // add	x14, x1, #32
	WORD $0x52800410 // mov	w16, #32                        ; =0x20
	WORD $0x4f000420 // movi.4s	v0, #1
	WORD $0x4f03c7e1 // movi.4s	v1, #127, msl #8

BB0_25:
	WORD $0x6f00e410 // movi.2d	v16, #0000000000000000
	WORD $0xaa1003ed // mov	x13, x16
	WORD $0x6f00e411 // movi.2d	v17, #0000000000000000
	WORD $0xaa0e03f0 // mov	x16, x14
	WORD $0xaa0a03f1 // mov	x17, x10
	WORD $0xaa0803e0 // mov	x0, x8
	WORD $0x6f00e407 // movi.2d	v7, #0000000000000000
	WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000

BB0_26:
	WORD $0x0dc9c632 // ld1r.4h	{ v18 }, [x17], x9
	WORD $0x2e613a52 // shll.4s	v18, v18, #16
	WORD $0xad7f5213 // ldp	q19, q20, [x16, #-32]
	WORD $0x2e613a75 // shll.4s	v21, v19, #16
	WORD $0x4e32ceb0 // fmla.4s	v16, v21, v18
	WORD $0x6e613a73 // shll2.4s	v19, v19, #16
	WORD $0x4e32ce71 // fmla.4s	v17, v19, v18
	WORD $0x2e613a93 // shll.4s	v19, v20, #16
	WORD $0x4e32ce67 // fmla.4s	v7, v19, v18
	WORD $0x6e613a93 // shll2.4s	v19, v20, #16
	WORD $0x4e32ce66 // fmla.4s	v6, v19, v18
	WORD $0xad405213 // ldp	q19, q20, [x16]
	WORD $0x2e613a75 // shll.4s	v21, v19, #16
	WORD $0x4e32cea5 // fmla.4s	v5, v21, v18
	WORD $0x6e613a73 // shll2.4s	v19, v19, #16
	WORD $0x4e32ce64 // fmla.4s	v4, v19, v18
	WORD $0x2e613a93 // shll.4s	v19, v20, #16
	WORD $0x4e32ce63 // fmla.4s	v3, v19, v18
	WORD $0x6e613a93 // shll2.4s	v19, v20, #16
	WORD $0x4e32ce62 // fmla.4s	v2, v19, v18
	WORD $0x8b090210 // add	x16, x16, x9
	WORD $0xf1000400 // subs	x0, x0, #1
	BNE  BB0_26
	WORD $0x8b0f056f // add	x15, x11, x15, lsl #1
	WORD $0xad404df2 // ldp	q18, q19, [x15]
	WORD $0x2e613a54 // shll.4s	v20, v18, #16
	WORD $0x4e34d610 // fadd.4s	v16, v16, v20
	WORD $0x6e613a52 // shll2.4s	v18, v18, #16
	WORD $0x4e32d631 // fadd.4s	v17, v17, v18
	WORD $0x6f300632 // ushr.4s	v18, v17, #16
	WORD $0x4e201e52 // and.16b	v18, v18, v0
	WORD $0x4eb28631 // add.4s	v17, v17, v18
	WORD $0x6f300612 // ushr.4s	v18, v16, #16
	WORD $0x4e201e52 // and.16b	v18, v18, v0
	WORD $0x4eb28610 // add.4s	v16, v16, v18
	WORD $0x0e614210 // addhn.4h	v16, v16, v1
	WORD $0x4e614230 // addhn2.8h	v16, v17, v1
	WORD $0x2e613a71 // shll.4s	v17, v19, #16
	WORD $0x4e31d4e7 // fadd.4s	v7, v7, v17
	WORD $0x6e613a71 // shll2.4s	v17, v19, #16
	WORD $0x4e31d4c6 // fadd.4s	v6, v6, v17
	WORD $0x6f3004d1 // ushr.4s	v17, v6, #16
	WORD $0x4e201e31 // and.16b	v17, v17, v0
	WORD $0x4eb184c6 // add.4s	v6, v6, v17
	WORD $0x6f3004f1 // ushr.4s	v17, v7, #16
	WORD $0x4e201e31 // and.16b	v17, v17, v0
	WORD $0x4eb184e7 // add.4s	v7, v7, v17
	WORD $0x0e6140e7 // addhn.4h	v7, v7, v1
	WORD $0x4e6140c7 // addhn2.8h	v7, v6, v1
	WORD $0xad001df0 // stp	q16, q7, [x15]
	WORD $0xad411de6 // ldp	q6, q7, [x15, #32]
	WORD $0x2e6138d0 // shll.4s	v16, v6, #16
	WORD $0x4e30d4a5 // fadd.4s	v5, v5, v16
	WORD $0x6e6138c6 // shll2.4s	v6, v6, #16
	WORD $0x4e26d484 // fadd.4s	v4, v4, v6
	WORD $0x6f300486 // ushr.4s	v6, v4, #16
	WORD $0x4e201cc6 // and.16b	v6, v6, v0
	WORD $0x4ea68484 // add.4s	v4, v4, v6
	WORD $0x6f3004a6 // ushr.4s	v6, v5, #16
	WORD $0x4e201cc6 // and.16b	v6, v6, v0
	WORD $0x4ea684a5 // add.4s	v5, v5, v6
	WORD $0x0e6140a5 // addhn.4h	v5, v5, v1
	WORD $0x4e614085 // addhn2.8h	v5, v4, v1
	WORD $0x2e6138e4 // shll.4s	v4, v7, #16
	WORD $0x4e24d463 // fadd.4s	v3, v3, v4
	WORD $0x6e6138e4 // shll2.4s	v4, v7, #16
	WORD $0x4e24d442 // fadd.4s	v2, v2, v4
	WORD $0x6f300444 // ushr.4s	v4, v2, #16
	WORD $0x4e201c84 // and.16b	v4, v4, v0
	WORD $0x4ea48442 // add.4s	v2, v2, v4
	WORD $0x6f300464 // ushr.4s	v4, v3, #16
	WORD $0x4e201c84 // and.16b	v4, v4, v0
	WORD $0x4ea48463 // add.4s	v3, v3, v4
	WORD $0x0e614063 // addhn.4h	v3, v3, v1
	WORD $0x4e614043 // addhn2.8h	v3, v2, v1
	WORD $0xad010de5 // stp	q5, q3, [x15, #32]
	WORD $0x910081b0 // add	x16, x13, #32
	WORD $0x910101ce // add	x14, x14, #64
	WORD $0xaa0d03ef // mov	x15, x13
	WORD $0xeb08021f // cmp	x16, x8
	BLE  BB0_25

BB0_28:
	WORD $0xb27d01b0 // orr	x16, x13, #0x8
	WORD $0xeb08021f // cmp	x16, x8
	BLE  BB0_36
	WORD $0xaa0d03ee // mov	x14, x13

BB0_30:
	WORD $0xeb0e010d // subs	x13, x8, x14
	BLE  BB0_44
	WORD $0xf100011f // cmp	x8, #0
	BLE  BB0_42
	WORD $0x8b0e042c // add	x12, x1, x14, lsl #1
	WORD $0x528fffed // mov	w13, #32767                     ; =0x7fff

BB0_33:
	WORD $0xd280000f // mov	x15, #0                         ; =0x0
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0xaa0803f0 // mov	x16, x8

BB0_34:
	WORD $0x786f6951 // ldrh	w17, [x10, x15]
	WORD $0x786f6980 // ldrh	w0, [x12, x15]
	WORD $0x1b117c11 // mul	w17, w0, w17
	WORD $0x1e230221 // ucvtf	s1, w17
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x8b0901ef // add	x15, x15, x9
	WORD $0xf1000610 // subs	x16, x16, #1
	BNE  BB0_34
	WORD $0x786e796f // ldrh	w15, [x11, x14, lsl #1]
	WORD $0x53103def // lsl	w15, w15, #16
	WORD $0x1e2701e1 // fmov	s1, w15
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x1e26000f // fmov	w15, s0
	WORD $0x531041f0 // ubfx	w16, w15, #16, #1
	WORD $0x0b1001ef // add	w15, w15, w16
	WORD $0x0b0d01ef // add	w15, w15, w13
	WORD $0x53107def // lsr	w15, w15, #16
	WORD $0x782e796f // strh	w15, [x11, x14, lsl #1]
	WORD $0x910005ce // add	x14, x14, #1
	WORD $0x9100098c // add	x12, x12, #2
	WORD $0xeb0801df // cmp	x14, x8
	BNE  BB0_33
	B    BB0_44

BB0_36:
	WORD $0x8b0d042f // add	x15, x1, x13, lsl #1
	WORD $0x4f000420 // movi.4s	v0, #1
	WORD $0x4f03c7e1 // movi.4s	v1, #127, msl #8
	B    BB0_39

BB0_37:
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000

BB0_38:
	WORD $0xd37ff9ad // lsl	x13, x13, #1
	WORD $0x3ced6964 // ldr	q4, [x11, x13]
	WORD $0x2e613885 // shll.4s	v5, v4, #16
	WORD $0x4e25d463 // fadd.4s	v3, v3, v5
	WORD $0x6e613884 // shll2.4s	v4, v4, #16
	WORD $0x4e24d442 // fadd.4s	v2, v2, v4
	WORD $0x6f300444 // ushr.4s	v4, v2, #16
	WORD $0x4e201c84 // and.16b	v4, v4, v0
	WORD $0x4ea48442 // add.4s	v2, v2, v4
	WORD $0x6f300464 // ushr.4s	v4, v3, #16
	WORD $0x4e201c84 // and.16b	v4, v4, v0
	WORD $0x4ea48463 // add.4s	v3, v3, v4
	WORD $0x0e614063 // addhn.4h	v3, v3, v1
	WORD $0x4e614043 // addhn2.8h	v3, v2, v1
	WORD $0x3cad6963 // str	q3, [x11, x13]
	WORD $0x910021d0 // add	x16, x14, #8
	WORD $0x910041ef // add	x15, x15, #16
	WORD $0xaa0e03ed // mov	x13, x14
	WORD $0xeb08021f // cmp	x16, x8
	BGT  BB0_30

BB0_39:
	WORD $0xaa1003ee // mov	x14, x16
	WORD $0xf100051f // cmp	x8, #1
	BLT  BB0_37
	WORD $0xd2800010 // mov	x16, #0                         ; =0x0
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0xaa0803f1 // mov	x17, x8
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000

BB0_41:
	WORD $0x8b100140 // add	x0, x10, x16
	WORD $0x0d40c404 // ld1r.4h	{ v4 }, [x0]
	WORD $0x2e613884 // shll.4s	v4, v4, #16
	WORD $0x3cf069e5 // ldr	q5, [x15, x16]
	WORD $0x2e6138a6 // shll.4s	v6, v5, #16
	WORD $0x4e24ccc3 // fmla.4s	v3, v6, v4
	WORD $0x6e6138a5 // shll2.4s	v5, v5, #16
	WORD $0x4e24cca2 // fmla.4s	v2, v5, v4
	WORD $0x8b090210 // add	x16, x16, x9
	WORD $0xf1000631 // subs	x17, x17, #1
	BNE  BB0_41
	B    BB0_38

BB0_42:
	WORD $0xd37ff988 // lsl	x8, x12, #1
	WORD $0x8b0e0508 // add	x8, x8, x14, lsl #1
	WORD $0x8b080048 // add	x8, x2, x8
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0x528fffe9 // mov	w9, #32767                      ; =0x7fff

BB0_43:
	WORD $0x7940010a // ldrh	w10, [x8]
	WORD $0x53103d4a // lsl	w10, w10, #16
	WORD $0x1e270141 // fmov	s1, w10
	WORD $0x1e202821 // fadd	s1, s1, s0
	WORD $0x1e26002a // fmov	w10, s1
	WORD $0x5310414b // ubfx	w11, w10, #16, #1
	WORD $0x0b0b014a // add	w10, w10, w11
	WORD $0x0b09014a // add	w10, w10, w9
	WORD $0x53107d4a // lsr	w10, w10, #16
	WORD $0x7800250a // strh	w10, [x8], #2
	WORD $0xf10005ad // subs	x13, x13, #1
	BNE  BB0_43

BB0_44:
	WORD $0x6d4123e9 // ldp	d9, d8, [sp, #16]               ; 16-byte Folded Reload
	WORD $0x6d402beb // ldp	d11, d10, [sp], #32             ; 16-byte Folded Reload [transformed]
	RET
