//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8.6-a+bf16+simd -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/matmul/asm/basetranspose2dstrided_c_bf16_neon_arm64.c

TEXT ·transpose2dstrided_c_bf16_neon(SB), $32-64
	MOVD src+0(FP), R0
	MOVD prowStart+8(FP), R1
	MOVD prowEnd+16(FP), R2
	MOVD pk+24(FP), R3
	MOVD pdstM+32(FP), R4
	MOVD dst+40(FP), R5
	MOVD plen_src+48(FP), R6
	MOVD plen_dst+56(FP), R7
	WORD $0xf9400048         // ldr	x8, [x2]
	WORD $0xf940002b         // ldr	x11, [x1]
	WORD $0xeb08017f         // cmp	x11, x8
	BGE  BB0_25
	WORD $0xa90057f6         // stp	x22, x21, [sp, #-32]!           ; 16-byte Folded Spill [transformed]
	WORD $0xa9014ff4         // stp	x20, x19, [sp, #16]             ; 16-byte Folded Spill
	WORD $0xf940008a         // ldr	x10, [x4]
	WORD $0xf9400069         // ldr	x9, [x3]
	WORD $0xd100210c         // sub	x12, x8, #8
	WORD $0xeb0c017f         // cmp	x11, x12
	BGT  BB0_7
	WORD $0xf100212d         // subs	x13, x9, #8
	BLT  BB0_7
	WORD $0x9b0b7d2e         // mul	x14, x9, x11
	WORD $0x8b0e040e         // add	x14, x0, x14, lsl #1
	WORD $0xd37ced2f         // lsl	x15, x9, #4
	WORD $0x8b0b04b0         // add	x16, x5, x11, lsl #1
	WORD $0xd37ced51         // lsl	x17, x10, #4
	WORD $0xd37ff921         // lsl	x1, x9, #1
	WORD $0xd37ff942         // lsl	x2, x10, #1
	WORD $0xaa0b03e3         // mov	x3, x11

BB0_4:
	WORD $0xd2800004 // mov	x4, #0                          ; =0x0
	WORD $0xaa1003e6 // mov	x6, x16
	WORD $0xaa0e03e7 // mov	x7, x14

BB0_5:
	WORD $0x3dc000e0 // ldr	q0, [x7]
	WORD $0x8b0100f3 // add	x19, x7, x1
	WORD $0x8b010274 // add	x20, x19, x1
	WORD $0x3dc00261 // ldr	q1, [x19]
	WORD $0x3dc00282 // ldr	q2, [x20]
	WORD $0x8b010293 // add	x19, x20, x1
	WORD $0x8b010274 // add	x20, x19, x1
	WORD $0x3dc00263 // ldr	q3, [x19]
	WORD $0x3dc00284 // ldr	q4, [x20]
	WORD $0x8b010293 // add	x19, x20, x1
	WORD $0x8b010274 // add	x20, x19, x1
	WORD $0x3dc00265 // ldr	q5, [x19]
	WORD $0x3dc00286 // ldr	q6, [x20]
	WORD $0x3ce16a87 // ldr	q7, [x20, x1]
	WORD $0x6e613890 // shll2.4s	v16, v4, #16
	WORD $0x6e613811 // shll2.4s	v17, v0, #16
	WORD $0x6e30de30 // fmul.4s	v16, v17, v16
	WORD $0x2e613884 // shll.4s	v4, v4, #16
	WORD $0x2e613800 // shll.4s	v0, v0, #16
	WORD $0x6e24dc00 // fmul.4s	v0, v0, v4
	WORD $0x0ea16800 // bfcvtn.4h	v0, v0
	WORD $0x4ea16a00 // bfcvtn2.8h	v0, v16
	WORD $0x6e613824 // shll2.4s	v4, v1, #16
	WORD $0x6e6138b0 // shll2.4s	v16, v5, #16
	WORD $0x6e30dc84 // fmul.4s	v4, v4, v16
	WORD $0x2e613821 // shll.4s	v1, v1, #16
	WORD $0x2e6138a5 // shll.4s	v5, v5, #16
	WORD $0x6e25dc21 // fmul.4s	v1, v1, v5
	WORD $0x0ea16821 // bfcvtn.4h	v1, v1
	WORD $0x4ea16881 // bfcvtn2.8h	v1, v4
	WORD $0x6e613844 // shll2.4s	v4, v2, #16
	WORD $0x6e6138c5 // shll2.4s	v5, v6, #16
	WORD $0x6e25dc84 // fmul.4s	v4, v4, v5
	WORD $0x2e613842 // shll.4s	v2, v2, #16
	WORD $0x2e6138c5 // shll.4s	v5, v6, #16
	WORD $0x6e25dc42 // fmul.4s	v2, v2, v5
	WORD $0x0ea16842 // bfcvtn.4h	v2, v2
	WORD $0x4ea16882 // bfcvtn2.8h	v2, v4
	WORD $0x6e613864 // shll2.4s	v4, v3, #16
	WORD $0x6e6138e5 // shll2.4s	v5, v7, #16
	WORD $0x6e25dc84 // fmul.4s	v4, v4, v5
	WORD $0x2e613863 // shll.4s	v3, v3, #16
	WORD $0x2e6138e5 // shll.4s	v5, v7, #16
	WORD $0x6e25dc63 // fmul.4s	v3, v3, v5
	WORD $0x0ea16863 // bfcvtn.4h	v3, v3
	WORD $0x4ea16883 // bfcvtn2.8h	v3, v4
	WORD $0x6e613844 // shll2.4s	v4, v2, #16
	WORD $0x6e613805 // shll2.4s	v5, v0, #16
	WORD $0x6e24dca4 // fmul.4s	v4, v5, v4
	WORD $0x2e613842 // shll.4s	v2, v2, #16
	WORD $0x2e613800 // shll.4s	v0, v0, #16
	WORD $0x6e22dc00 // fmul.4s	v0, v0, v2
	WORD $0x0ea16800 // bfcvtn.4h	v0, v0
	WORD $0x4ea16880 // bfcvtn2.8h	v0, v4
	WORD $0x6e613822 // shll2.4s	v2, v1, #16
	WORD $0x6e613864 // shll2.4s	v4, v3, #16
	WORD $0x6e24dc42 // fmul.4s	v2, v2, v4
	WORD $0x2e613821 // shll.4s	v1, v1, #16
	WORD $0x2e613863 // shll.4s	v3, v3, #16
	WORD $0x6e23dc21 // fmul.4s	v1, v1, v3
	WORD $0x0ea16821 // bfcvtn.4h	v1, v1
	WORD $0x4ea16841 // bfcvtn2.8h	v1, v2
	WORD $0x6e613822 // shll2.4s	v2, v1, #16
	WORD $0x6e613803 // shll2.4s	v3, v0, #16
	WORD $0x6e22dc62 // fmul.4s	v2, v3, v2
	WORD $0x2e613821 // shll.4s	v1, v1, #16
	WORD $0x2e613800 // shll.4s	v0, v0, #16
	WORD $0x6e21dc00 // fmul.4s	v0, v0, v1
	WORD $0x0ea16800 // bfcvtn.4h	v0, v0
	WORD $0x4ea16840 // bfcvtn2.8h	v0, v2
	WORD $0x3d8000c0 // str	q0, [x6]
	WORD $0x8b0200d3 // add	x19, x6, x2
	WORD $0x8b020274 // add	x20, x19, x2
	WORD $0x3d800260 // str	q0, [x19]
	WORD $0x3d800280 // str	q0, [x20]
	WORD $0x8b020293 // add	x19, x20, x2
	WORD $0x8b020274 // add	x20, x19, x2
	WORD $0x3d800260 // str	q0, [x19]
	WORD $0x3d800280 // str	q0, [x20]
	WORD $0x8b020293 // add	x19, x20, x2
	WORD $0x8b020274 // add	x20, x19, x2
	WORD $0x3d800260 // str	q0, [x19]
	WORD $0x3d800280 // str	q0, [x20]
	WORD $0x3ca26a80 // str	q0, [x20, x2]
	WORD $0x91002084 // add	x4, x4, #8
	WORD $0x910040e7 // add	x7, x7, #16
	WORD $0x8b1100c6 // add	x6, x6, x17
	WORD $0xeb0d009f // cmp	x4, x13
	BLE  BB0_5
	WORD $0x91002063 // add	x3, x3, #8
	WORD $0x8b0f01ce // add	x14, x14, x15
	WORD $0x91004210 // add	x16, x16, #16
	WORD $0xeb0c007f // cmp	x3, x12
	BLE  BB0_4

BB0_7:
	WORD $0xb1001d6c // adds	x12, x11, #7
	WORD $0x9100396d // add	x13, x11, #14
	WORD $0x9a8cb1ac // csel	x12, x13, x12, lt
	WORD $0x927df18d // and	x13, x12, #0xfffffffffffffff8
	WORD $0x91001d0c // add	x12, x8, #7
	WORD $0xf100011f // cmp	x8, #0
	WORD $0x9a88b18e // csel	x14, x12, x8, lt
	WORD $0x91001d2c // add	x12, x9, #7
	WORD $0xf100013f // cmp	x9, #0
	WORD $0x9a89b190 // csel	x16, x12, x9, lt
	WORD $0x927df20c // and	x12, x16, #0xfffffffffffffff8
	WORD $0xeb0c012f // subs	x15, x9, x12
	BLE  BB0_12
	WORD $0x9343fe10 // asr	x16, x16, #3
	WORD $0x9b107d51 // mul	x17, x10, x16
	WORD $0xd37cee31 // lsl	x17, x17, #4
	WORD $0x8b0b0631 // add	x17, x17, x11, lsl #1
	WORD $0x9b0b7d21 // mul	x1, x9, x11
	WORD $0xd37ff821 // lsl	x1, x1, #1
	WORD $0x8b101021 // add	x1, x1, x16, lsl #4
	WORD $0x8b1100b0 // add	x16, x5, x17
	WORD $0xd37ff951 // lsl	x17, x10, #1
	WORD $0x8b010001 // add	x1, x0, x1
	WORD $0xd37ff922 // lsl	x2, x9, #1
	WORD $0x528fffe3 // mov	w3, #32767                      ; =0x7fff
	WORD $0xaa0b03e4 // mov	x4, x11

BB0_9:
	WORD $0xaa0103e6 // mov	x6, x1
	WORD $0xaa1003e7 // mov	x7, x16
	WORD $0xaa0f03f3 // mov	x19, x15

BB0_10:
	WORD $0x784024d4 // ldrh	w20, [x6], #2
	WORD $0x1e230280 // ucvtf	s0, w20
	WORD $0x1e260014 // fmov	w20, s0
	WORD $0x53104295 // ubfx	w21, w20, #16, #1
	WORD $0x0b150294 // add	w20, w20, w21
	WORD $0x0b030294 // add	w20, w20, w3
	WORD $0x53107e94 // lsr	w20, w20, #16
	WORD $0x790000f4 // strh	w20, [x7]
	WORD $0x8b1100e7 // add	x7, x7, x17
	WORD $0xf1000673 // subs	x19, x19, #1
	BNE  BB0_10
	WORD $0x91000484 // add	x4, x4, #1
	WORD $0x91000a10 // add	x16, x16, #2
	WORD $0x8b020021 // add	x1, x1, x2
	WORD $0xeb08009f // cmp	x4, x8
	BNE  BB0_9

BB0_12:
	WORD $0x927df1ce // and	x14, x14, #0xfffffffffffffff8
	WORD $0xeb0801bf // cmp	x13, x8
	WORD $0x9a88b1ad // csel	x13, x13, x8, lt
	WORD $0xf100213f // cmp	x9, #8
	BLT  BB0_18
	WORD $0xeb0d017f // cmp	x11, x13
	BGE  BB0_18
	WORD $0xf100059f // cmp	x12, #1
	WORD $0x9a9fc58f // csinc	x15, x12, xzr, gt
	WORD $0x8b0b04b0 // add	x16, x5, x11, lsl #1
	WORD $0xd37ff951 // lsl	x17, x10, #1
	WORD $0x9b0b7d21 // mul	x1, x9, x11
	WORD $0x8b010401 // add	x1, x0, x1, lsl #1
	WORD $0xd37ff922 // lsl	x2, x9, #1
	WORD $0x528fffe3 // mov	w3, #32767                      ; =0x7fff
	WORD $0xaa0b03e4 // mov	x4, x11

BB0_15:
	WORD $0xaa0103e6 // mov	x6, x1
	WORD $0xaa1003e7 // mov	x7, x16
	WORD $0xaa0f03f3 // mov	x19, x15

BB0_16:
	WORD $0x784024d4 // ldrh	w20, [x6], #2
	WORD $0x1e230280 // ucvtf	s0, w20
	WORD $0x1e260014 // fmov	w20, s0
	WORD $0x53104295 // ubfx	w21, w20, #16, #1
	WORD $0x0b150294 // add	w20, w20, w21
	WORD $0x0b030294 // add	w20, w20, w3
	WORD $0x53107e94 // lsr	w20, w20, #16
	WORD $0x790000f4 // strh	w20, [x7]
	WORD $0x8b1100e7 // add	x7, x7, x17
	WORD $0xf1000673 // subs	x19, x19, #1
	BNE  BB0_16
	WORD $0x91000484 // add	x4, x4, #1
	WORD $0x91000a10 // add	x16, x16, #2
	WORD $0x8b020021 // add	x1, x1, x2
	WORD $0xeb0d009f // cmp	x4, x13
	BNE  BB0_15

BB0_18:
	WORD $0xeb0b01df // cmp	x14, x11
	WORD $0x9a8bc1cb // csel	x11, x14, x11, gt
	WORD $0xf100213f // cmp	x9, #8
	BLT  BB0_24
	WORD $0xeb08017f // cmp	x11, x8
	BGE  BB0_24
	WORD $0xf100059f // cmp	x12, #1
	WORD $0x9a9fc58c // csinc	x12, x12, xzr, gt
	WORD $0x8b0b04ad // add	x13, x5, x11, lsl #1
	WORD $0xd37ff94a // lsl	x10, x10, #1
	WORD $0x9b0b7d2e // mul	x14, x9, x11
	WORD $0x8b0e040e // add	x14, x0, x14, lsl #1
	WORD $0xd37ff929 // lsl	x9, x9, #1
	WORD $0x528fffef // mov	w15, #32767                     ; =0x7fff

BB0_21:
	WORD $0xaa0e03f0 // mov	x16, x14
	WORD $0xaa0d03f1 // mov	x17, x13
	WORD $0xaa0c03e0 // mov	x0, x12

BB0_22:
	WORD $0x78402601 // ldrh	w1, [x16], #2
	WORD $0x1e230020 // ucvtf	s0, w1
	WORD $0x1e260001 // fmov	w1, s0
	WORD $0x53104022 // ubfx	w2, w1, #16, #1
	WORD $0x0b020021 // add	w1, w1, w2
	WORD $0x0b0f0021 // add	w1, w1, w15
	WORD $0x53107c21 // lsr	w1, w1, #16
	WORD $0x79000221 // strh	w1, [x17]
	WORD $0x8b0a0231 // add	x17, x17, x10
	WORD $0xf1000400 // subs	x0, x0, #1
	BNE  BB0_22
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0x910009ad // add	x13, x13, #2
	WORD $0x8b0901ce // add	x14, x14, x9
	WORD $0xeb08017f // cmp	x11, x8
	BNE  BB0_21

BB0_24:
	WORD $0xa9414ff4 // ldp	x20, x19, [sp, #16]             ; 16-byte Folded Reload
	WORD $0xa94057f6 // ldp	x22, x21, [sp], #32             ; 16-byte Folded Reload [transformed]

BB0_25:
	RET
