//go:build !noasm && arm64

// Code generated by hwygen -c. DO NOT EDIT.

package asm

import (
	"unsafe"

	"github.com/ajroetker/go-highway/hwy"
)

// Public wrapper functions
// SoftmaxCF16 computes Softmax using NEON SIMD assembly.
func SoftmaxCF16(input, output []hwy.Float16) {
	lenVal := int64(min(len(input), len(output)))
	if lenVal == 0 {
		return
	}
	var p_input unsafe.Pointer
	if len(input) > 0 {
		p_input = unsafe.Pointer(&input[0])
	}
	var p_output unsafe.Pointer
	if len(output) > 0 {
		p_output = unsafe.Pointer(&output[0])
	}
	softmax_c_f16_neon(
		p_input,
		p_output,
		unsafe.Pointer(&lenVal),
	)
}

// SoftmaxCBF16 computes Softmax using NEON SIMD assembly.
func SoftmaxCBF16(input, output []hwy.BFloat16) {
	lenVal := int64(min(len(input), len(output)))
	if lenVal == 0 {
		return
	}
	var p_input unsafe.Pointer
	if len(input) > 0 {
		p_input = unsafe.Pointer(&input[0])
	}
	var p_output unsafe.Pointer
	if len(output) > 0 {
		p_output = unsafe.Pointer(&output[0])
	}
	softmax_c_bf16_neon(
		p_input,
		p_output,
		unsafe.Pointer(&lenVal),
	)
}

// SoftmaxCF32 computes Softmax using NEON SIMD assembly.
func SoftmaxCF32(input, output []float32) {
	lenVal := int64(min(len(input), len(output)))
	if lenVal == 0 {
		return
	}
	var p_input unsafe.Pointer
	if len(input) > 0 {
		p_input = unsafe.Pointer(&input[0])
	}
	var p_output unsafe.Pointer
	if len(output) > 0 {
		p_output = unsafe.Pointer(&output[0])
	}
	softmax_c_f32_neon(
		p_input,
		p_output,
		unsafe.Pointer(&lenVal),
	)
}

// SoftmaxCF64 computes Softmax using NEON SIMD assembly.
func SoftmaxCF64(input, output []float64) {
	lenVal := int64(min(len(input), len(output)))
	if lenVal == 0 {
		return
	}
	var p_input unsafe.Pointer
	if len(input) > 0 {
		p_input = unsafe.Pointer(&input[0])
	}
	var p_output unsafe.Pointer
	if len(output) > 0 {
		p_output = unsafe.Pointer(&output[0])
	}
	softmax_c_f64_neon(
		p_input,
		p_output,
		unsafe.Pointer(&lenVal),
	)
}
