//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/vec/asm/basenormalize_c_f64_neon_arm64.c

TEXT ·normalize_c_f64_neon(SB), $0-16
	MOVD dst+0(FP), R0
	MOVD plen_dst+8(FP), R1
	WORD $0xf9400028        // ldr	x8, [x1]
	CBZ  R8, BB0_20
	WORD $0xf100211f        // cmp	x8, #8
	BGE  BB0_6
	WORD $0xd2800009        // mov	x9, #0                          ; =0x0
	WORD $0x6f00e400        // movi.2d	v0, #0000000000000000
	WORD $0x6f00e402        // movi.2d	v2, #0000000000000000
	WORD $0x6f00e403        // movi.2d	v3, #0000000000000000
	WORD $0x6f00e401        // movi.2d	v1, #0000000000000000
	WORD $0xb27f012a        // orr	x10, x9, #0x2
	WORD $0xeb08015f        // cmp	x10, x8
	BGT  BB0_9

BB0_3:
	WORD $0x8b090c0a // add	x10, x0, x9, lsl #3

BB0_4:
	WORD $0x3cc10544 // ldr	q4, [x10], #16
	WORD $0x4e64cc81 // fmla.2d	v1, v4, v4
	WORD $0x9100092b // add	x11, x9, #2
	WORD $0x9100112c // add	x12, x9, #4
	WORD $0xaa0b03e9 // mov	x9, x11
	WORD $0xeb08019f // cmp	x12, x8
	BLE  BB0_4
	WORD $0x4e61d461 // fadd.2d	v1, v3, v1
	WORD $0x4e62d400 // fadd.2d	v0, v0, v2
	WORD $0x4e61d400 // fadd.2d	v0, v0, v1
	WORD $0x7e70d800 // faddp.2d	d0, v0
	WORD $0xeb0b0109 // subs	x9, x8, x11
	BGT  BB0_10
	B    BB0_12

BB0_6:
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0x52800109 // mov	w9, #8                          ; =0x8
	WORD $0xaa0003ea // mov	x10, x0
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000

BB0_7:
	WORD $0x4cdf2d44 // ld1.2d	{ v4, v5, v6, v7 }, [x10], #64
	WORD $0x4e64cc81 // fmla.2d	v1, v4, v4
	WORD $0x4e65cca3 // fmla.2d	v3, v5, v5
	WORD $0x4e66ccc2 // fmla.2d	v2, v6, v6
	WORD $0x4e67cce0 // fmla.2d	v0, v7, v7
	WORD $0x91002129 // add	x9, x9, #8
	WORD $0xeb08013f // cmp	x9, x8
	BLE  BB0_7
	WORD $0x927ded09 // and	x9, x8, #0x7ffffffffffffff8
	WORD $0xb27f012a // orr	x10, x9, #0x2
	WORD $0xeb08015f // cmp	x10, x8
	BLE  BB0_3

BB0_9:
	WORD $0xaa0903eb // mov	x11, x9
	WORD $0x4e61d461 // fadd.2d	v1, v3, v1
	WORD $0x4e62d400 // fadd.2d	v0, v0, v2
	WORD $0x4e61d400 // fadd.2d	v0, v0, v1
	WORD $0x7e70d800 // faddp.2d	d0, v0
	WORD $0xeb090109 // subs	x9, x8, x9
	BLE  BB0_12

BB0_10:
	WORD $0x8b0b0c0a // add	x10, x0, x11, lsl #3

BB0_11:
	WORD $0xfc408541 // ldr	d1, [x10], #8
	WORD $0x1f410020 // fmadd	d0, d1, d1, d0
	WORD $0xf1000529 // subs	x9, x9, #1
	BNE  BB0_11

BB0_12:
	WORD $0x9e780009 // fcvtzs	x9, d0
	CBZ  R9, BB0_20
	WORD $0x9e620120 // scvtf	d0, x9
	WORD $0x1e61c000 // fsqrt	d0, d0
	WORD $0x1e6e1001 // fmov	d1, #1.00000000
	WORD $0x1e601820 // fdiv	d0, d1, d0
	WORD $0xf100091f // cmp	x8, #2
	BGE  BB0_15
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	B    BB0_17

BB0_15:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0xaa0003e9 // mov	x9, x0

BB0_16:
	WORD $0x3dc00121 // ldr	q1, [x9]
	WORD $0x4fc09021 // fmul.2d	v1, v1, v0[0]
	WORD $0x3c810521 // str	q1, [x9], #16
	WORD $0x9100094b // add	x11, x10, #2
	WORD $0x9100114c // add	x12, x10, #4
	WORD $0xaa0b03ea // mov	x10, x11
	WORD $0xeb08019f // cmp	x12, x8
	BLE  BB0_16

BB0_17:
	WORD $0xeb0b0108 // subs	x8, x8, x11
	BLE  BB0_20
	WORD $0x8b0b0c09 // add	x9, x0, x11, lsl #3

BB0_19:
	WORD $0xfd400121 // ldr	d1, [x9]
	WORD $0x1e610801 // fmul	d1, d0, d1
	WORD $0xfc008521 // str	d1, [x9], #8
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_19

BB0_20:
	RET
