//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   22.1.0
// 	objdump 2.46.0.20260210
// flags: -march=armv8.6-a+bf16+simd -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/vec/asm/basecopy_c_bf16_neon_arm64.c

TEXT ·copy_c_bf16_neon(SB), $0-24
	MOVD dst+0(FP), R0
	MOVD src+8(FP), R1
	MOVD plen_dst+16(FP), R2
	WORD $0xf9400048         // ldr	x8, [x2]
	CBZ  R8, BB0_8
	WORD $0xf100211f         // cmp	x8, #8
	BGE  BB0_3
	WORD $0xd2800009         // mov	x9, #0                          ; =0x0
	B    BB0_5

BB0_3:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0xaa0003ea // mov	x10, x0
	WORD $0xaa0103eb // mov	x11, x1

BB0_4:
	WORD $0x3cc10560 // ldr	q0, [x11], #16
	WORD $0x3c810540 // str	q0, [x10], #16
	WORD $0x9100412c // add	x12, x9, #16
	WORD $0x91002129 // add	x9, x9, #8
	WORD $0xeb08019f // cmp	x12, x8
	BLE  BB0_4

BB0_5:
	WORD $0xeb090108 // subs	x8, x8, x9
	BLE  BB0_8
	WORD $0xd37ff92a // lsl	x10, x9, #1
	WORD $0x8b0a0009 // add	x9, x0, x10
	WORD $0x8b0a002a // add	x10, x1, x10
	WORD $0x528fffeb // mov	w11, #32767                     ; =0x7fff

BB0_7:
	WORD $0x7840254c // ldrh	w12, [x10], #2
	WORD $0x1e230180 // ucvtf	s0, w12
	WORD $0x1e26000c // fmov	w12, s0
	WORD $0x5310418d // ubfx	w13, w12, #16, #1
	WORD $0x0b0d018c // add	w12, w12, w13
	WORD $0x0b0b018c // add	w12, w12, w11
	WORD $0x53107d8c // lsr	w12, w12, #16
	WORD $0x7800252c // strh	w12, [x9], #2
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_7

BB0_8:
	RET
