//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/vec/asm/basemax_c_s32_neon_arm64.c

TEXT ·max_c_s32_neon(SB), $0-24
	MOVD v+0(FP), R0
	MOVD plen_v+8(FP), R1
	MOVD pout_result+16(FP), R2
	WORD $0xf9400028            // ldr	x8, [x1]
	WORD $0xf1000d1f            // cmp	x8, #3
	BGT  BB0_4
	WORD $0xb9400009            // ldr	w9, [x0]
	WORD $0xf100091f            // cmp	x8, #2
	BLT  BB0_6
	WORD $0xb940040a            // ldr	w10, [x0, #4]
	WORD $0x6b09015f            // cmp	w10, w9
	WORD $0x1a89c149            // csel	w9, w10, w9, gt
	WORD $0xf100091f            // cmp	x8, #2
	BEQ  BB0_6
	WORD $0xb9400808            // ldr	w8, [x0, #8]
	WORD $0x6b09011f            // cmp	w8, w9
	WORD $0x1a89c109            // csel	w9, w8, w9, gt
	WORD $0x93407d28            // sxtw	x8, w9
	WORD $0xf9000048            // str	x8, [x2]
	RET

BB0_4:
	WORD $0x3dc00000 // ldr	q0, [x0]
	WORD $0xf100211f // cmp	x8, #8
	BHS  BB0_7
	WORD $0x5280008a // mov	w10, #4                         ; =0x4
	WORD $0x4eb0a800 // smaxv.4s	s0, v0
	WORD $0x1e260009 // fmov	w9, s0
	WORD $0xeb0a0108 // subs	x8, x8, x10
	BHI  BB0_10

BB0_6:
	WORD $0x93407d28 // sxtw	x8, w9
	WORD $0xf9000048 // str	x8, [x2]
	RET

BB0_7:
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0x5280010a // mov	w10, #8                         ; =0x8

BB0_8:
	WORD $0x3cc10521 // ldr	q1, [x9], #16
	WORD $0x4ea16400 // smax.4s	v0, v0, v1
	WORD $0x9100114a // add	x10, x10, #4
	WORD $0xeb08015f // cmp	x10, x8
	BLE  BB0_8
	WORD $0x927ef10a // and	x10, x8, #0x7ffffffffffffffc
	WORD $0x4eb0a800 // smaxv.4s	s0, v0
	WORD $0x1e260009 // fmov	w9, s0
	WORD $0xeb0a0108 // subs	x8, x8, x10
	BLS  BB0_6

BB0_10:
	WORD $0x8b0a080a // add	x10, x0, x10, lsl #2

BB0_11:
	WORD $0xb840454b // ldr	w11, [x10], #4
	WORD $0x6b09017f // cmp	w11, w9
	WORD $0x1a89c169 // csel	w9, w11, w9, gt
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_11
	B    BB0_6
