//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   22.1.8
// 	objdump 2.46.1 (llvm-objdump 22.1.8)
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/vec/asm/basemax_c_u64_neon_arm64.c

package asm

import "unsafe"

//go:noescape
func max_c_u64_neon(v, plen_v, pout_result unsafe.Pointer)
