//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/vec/asm/basediv_c_f64_neon_arm64.c

TEXT ·div_c_f64_neon(SB), $0-24
	MOVD dst+0(FP), R0
	MOVD s+8(FP), R1
	MOVD plen_dst+16(FP), R2
	WORD $0xf9400048         // ldr	x8, [x2]
	WORD $0xf100091f         // cmp	x8, #2
	BLT  BB0_3
	WORD $0x52800049         // mov	w9, #2                          ; =0x2

BB0_2:
	WORD $0x3cc10420 // ldr	q0, [x1], #16
	WORD $0x3dc00001 // ldr	q1, [x0]
	WORD $0x6e60fc20 // fdiv.2d	v0, v1, v0
	WORD $0x3c810400 // str	q0, [x0], #16
	WORD $0x91000929 // add	x9, x9, #2
	WORD $0xeb08013f // cmp	x9, x8
	BLE  BB0_2

BB0_3:
	RET
