//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8.6-a+bf16+simd -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/vec/asm/baseminmax_c_bf16_neon_arm64.c

TEXT ·minmax_c_bf16_neon(SB), $0-32
	MOVD v+0(FP), R0
	MOVD plen_v+8(FP), R1
	MOVD pout_minVal+16(FP), R2
	MOVD pout_maxVal+24(FP), R3
	WORD $0xf9400028            // ldr	x8, [x1]
	WORD $0xf1001d1f            // cmp	x8, #7
	BGT  BB0_5
	WORD $0x7d400000            // ldr	h0, [x0]
	WORD $0x7e21d800            // ucvtf	s0, s0
	WORD $0xf100091f            // cmp	x8, #2
	BLT  BB0_7
	WORD $0x7d400401            // ldr	h1, [x0, #2]
	WORD $0x7e21d821            // ucvtf	s1, s1
	WORD $0x1e212000            // fcmp	s0, s1
	WORD $0x1e20cc22            // fcsel	s2, s1, s0, gt
	WORD $0x1e204c21            // fcsel	s1, s1, s0, mi
	WORD $0xf100091f            // cmp	x8, #2
	BNE  BB0_14
	WORD $0x1e604040            // fmov	d0, d2

BB0_4:
	WORD $0x9e380008 // fcvtzs	x8, s0
	WORD $0xf9000048 // str	x8, [x2]
	WORD $0x9e380028 // fcvtzs	x8, s1
	WORD $0xf9000068 // str	x8, [x3]
	RET

BB0_5:
	WORD $0x3dc00000 // ldr	q0, [x0]
	WORD $0xf100411f // cmp	x8, #16
	BHS  BB0_8
	WORD $0x52800109 // mov	w9, #8                          ; =0x8
	WORD $0x4ea01c01 // mov.16b	v1, v0
	B    BB0_11

BB0_7:
	WORD $0x1e604001 // fmov	d1, d0
	WORD $0x9e380008 // fcvtzs	x8, s0
	WORD $0xf9000048 // str	x8, [x2]
	WORD $0x9e380028 // fcvtzs	x8, s1
	WORD $0xf9000068 // str	x8, [x3]
	RET

BB0_8:
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0x5280020a // mov	w10, #16                        ; =0x10
	WORD $0x4f000422 // movi.4s	v2, #1
	WORD $0x4f03c7e3 // movi.4s	v3, #127, msl #8
	WORD $0x4ea01c01 // mov.16b	v1, v0

BB0_9:
	WORD $0x3cc10524 // ldr	q4, [x9], #16
	WORD $0x2e613805 // shll.4s	v5, v0, #16
	WORD $0x6e613800 // shll2.4s	v0, v0, #16
	WORD $0x2e613886 // shll.4s	v6, v4, #16
	WORD $0x6e613884 // shll2.4s	v4, v4, #16
	WORD $0x4ea6f4a5 // fmin.4s	v5, v5, v6
	WORD $0x4ea4f400 // fmin.4s	v0, v0, v4
	WORD $0x6f300407 // ushr.4s	v7, v0, #16
	WORD $0x4e221ce7 // and.16b	v7, v7, v2
	WORD $0x4ea78407 // add.4s	v7, v0, v7
	WORD $0x6f3004a0 // ushr.4s	v0, v5, #16
	WORD $0x4e221c00 // and.16b	v0, v0, v2
	WORD $0x4ea084a0 // add.4s	v0, v5, v0
	WORD $0x0e634000 // addhn.4h	v0, v0, v3
	WORD $0x4e6340e0 // addhn2.8h	v0, v7, v3
	WORD $0x2e613825 // shll.4s	v5, v1, #16
	WORD $0x6e613821 // shll2.4s	v1, v1, #16
	WORD $0x4e26f4a5 // fmax.4s	v5, v5, v6
	WORD $0x4e24f421 // fmax.4s	v1, v1, v4
	WORD $0x6f300424 // ushr.4s	v4, v1, #16
	WORD $0x4e221c84 // and.16b	v4, v4, v2
	WORD $0x4ea48424 // add.4s	v4, v1, v4
	WORD $0x6f3004a1 // ushr.4s	v1, v5, #16
	WORD $0x4e221c21 // and.16b	v1, v1, v2
	WORD $0x4ea184a1 // add.4s	v1, v5, v1
	WORD $0x0e634021 // addhn.4h	v1, v1, v3
	WORD $0x4e634081 // addhn2.8h	v1, v4, v3
	WORD $0x9100214a // add	x10, x10, #8
	WORD $0xeb08015f // cmp	x10, x8
	BLE  BB0_9
	WORD $0x927ded09 // and	x9, x8, #0x7ffffffffffffff8

BB0_11:
	WORD $0x2e613802 // shll.4s	v2, v0, #16
	WORD $0x6e613800 // shll2.4s	v0, v0, #16
	WORD $0x4ea0f440 // fmin.4s	v0, v2, v0
	WORD $0x6eb0f800 // fminv.4s	s0, v0
	WORD $0x2e613822 // shll.4s	v2, v1, #16
	WORD $0x6e613821 // shll2.4s	v1, v1, #16
	WORD $0x4e21f441 // fmax.4s	v1, v2, v1
	WORD $0x6e30f821 // fmaxv.4s	s1, v1
	WORD $0xeb090108 // subs	x8, x8, x9
	BLS  BB0_4
	WORD $0x8b090409 // add	x9, x0, x9, lsl #1

BB0_13:
	WORD $0x7840252a // ldrh	w10, [x9], #2
	WORD $0x1e230142 // ucvtf	s2, w10
	WORD $0x1e222000 // fcmp	s0, s2
	WORD $0x1e20cc40 // fcsel	s0, s2, s0, gt
	WORD $0x1e222020 // fcmp	s1, s2
	WORD $0x1e214c41 // fcsel	s1, s2, s1, mi
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_13
	B    BB0_4

BB0_14:
	WORD $0x7d400800 // ldr	h0, [x0, #4]
	WORD $0x7e21d803 // ucvtf	s3, s0
	WORD $0x1e232040 // fcmp	s2, s3
	WORD $0x1e22cc60 // fcsel	s0, s3, s2, gt
	WORD $0x1e232020 // fcmp	s1, s3
	WORD $0x1e214c61 // fcsel	s1, s3, s1, mi
	WORD $0xf1000d1f // cmp	x8, #3
	BEQ  BB0_4
	WORD $0x7d400c02 // ldr	h2, [x0, #6]
	WORD $0x7e21d842 // ucvtf	s2, s2
	WORD $0x1e222000 // fcmp	s0, s2
	WORD $0x1e20cc40 // fcsel	s0, s2, s0, gt
	WORD $0x1e222020 // fcmp	s1, s2
	WORD $0x1e214c41 // fcsel	s1, s2, s1, mi
	WORD $0xf100111f // cmp	x8, #4
	BEQ  BB0_4
	WORD $0x7d401002 // ldr	h2, [x0, #8]
	WORD $0x7e21d842 // ucvtf	s2, s2
	WORD $0x1e222000 // fcmp	s0, s2
	WORD $0x1e20cc40 // fcsel	s0, s2, s0, gt
	WORD $0x1e222020 // fcmp	s1, s2
	WORD $0x1e214c41 // fcsel	s1, s2, s1, mi
	WORD $0xf100151f // cmp	x8, #5
	BEQ  BB0_4
	WORD $0x7d401402 // ldr	h2, [x0, #10]
	WORD $0x7e21d842 // ucvtf	s2, s2
	WORD $0x1e222000 // fcmp	s0, s2
	WORD $0x1e20cc40 // fcsel	s0, s2, s0, gt
	WORD $0x1e222020 // fcmp	s1, s2
	WORD $0x1e214c41 // fcsel	s1, s2, s1, mi
	WORD $0xf100191f // cmp	x8, #6
	BEQ  BB0_4
	WORD $0x7d401802 // ldr	h2, [x0, #12]
	WORD $0x7e21d842 // ucvtf	s2, s2
	WORD $0x1e222000 // fcmp	s0, s2
	WORD $0x1e20cc40 // fcsel	s0, s2, s0, gt
	WORD $0x1e222020 // fcmp	s1, s2
	WORD $0x1e214c41 // fcsel	s1, s2, s1, mi
	WORD $0x9e380008 // fcvtzs	x8, s0
	WORD $0xf9000048 // str	x8, [x2]
	WORD $0x9e380028 // fcvtzs	x8, s1
	WORD $0xf9000068 // str	x8, [x3]
	RET
