//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/vec/asm/basemax_c_s64_neon_arm64.c

TEXT ·max_c_s64_neon(SB), $0-24
	MOVD v+0(FP), R0
	MOVD plen_v+8(FP), R1
	MOVD pout_result+16(FP), R2
	WORD $0xf9400028            // ldr	x8, [x1]
	WORD $0xf100051f            // cmp	x8, #1
	BGT  BB0_2
	WORD $0xf9400009            // ldr	x9, [x0]
	WORD $0xf9000049            // str	x9, [x2]
	RET

BB0_2:
	WORD $0x3dc00000 // ldr	q0, [x0]
	WORD $0xf100111f // cmp	x8, #4
	BHS  BB0_5
	WORD $0x5280004a // mov	w10, #2                         ; =0x2
	WORD $0x9e660009 // fmov	x9, d0
	WORD $0x4e183c0b // mov.d	x11, v0[1]
	WORD $0xeb0b013f // cmp	x9, x11
	WORD $0x9a8bc129 // csel	x9, x9, x11, gt
	WORD $0xeb0a0108 // subs	x8, x8, x10
	BHI  BB0_8

BB0_4:
	WORD $0xf9000049 // str	x9, [x2]
	RET

BB0_5:
	WORD $0x91004009 // add	x9, x0, #16
	WORD $0x5280008a // mov	w10, #4                         ; =0x4

BB0_6:
	WORD $0x3cc10521 // ldr	q1, [x9], #16
	WORD $0x4ee13402 // cmgt.2d	v2, v0, v1
	WORD $0x6ee21c20 // bif.16b	v0, v1, v2
	WORD $0x9100094a // add	x10, x10, #2
	WORD $0xeb08015f // cmp	x10, x8
	BLE  BB0_6
	WORD $0x927ff50a // and	x10, x8, #0x7ffffffffffffffe
	WORD $0x9e660009 // fmov	x9, d0
	WORD $0x4e183c0b // mov.d	x11, v0[1]
	WORD $0xeb0b013f // cmp	x9, x11
	WORD $0x9a8bc129 // csel	x9, x9, x11, gt
	WORD $0xeb0a0108 // subs	x8, x8, x10
	BLS  BB0_4

BB0_8:
	WORD $0x8b0a0c0a // add	x10, x0, x10, lsl #3

BB0_9:
	WORD $0xf840854b // ldr	x11, [x10], #8
	WORD $0xeb09017f // cmp	x11, x9
	WORD $0x9a89c169 // csel	x9, x11, x9, gt
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_9
	B    BB0_4
