//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8.6-a+bf16+simd -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/vec/asm/basescale_c_bf16_neon_arm64.c

TEXT ·scale_c_bf16_neon(SB), $0-24
	MOVD pc+0(FP), R0
	MOVD dst+8(FP), R1
	MOVD plen_dst+16(FP), R2
	WORD $0xf9400049         // ldr	x9, [x2]
	WORD $0xb4000629         // cbz	x9, LBB0_8
	WORD $0x79400008         // ldrh	w8, [x0]
	WORD $0xf100213f         // cmp	x9, #8
	BGE  BB0_3
	WORD $0xd280000c         // mov	x12, #0                         ; =0x0
	B    BB0_5

BB0_3:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0x0e020d00 // dup.4h	v0, w8
	WORD $0x2e613800 // shll.4s	v0, v0, #16
	WORD $0x4f000421 // movi.4s	v1, #1
	WORD $0x4f03c7e2 // movi.4s	v2, #127, msl #8
	WORD $0xaa0103eb // mov	x11, x1

BB0_4:
	WORD $0x3dc00163 // ldr	q3, [x11]
	WORD $0x2e613864 // shll.4s	v4, v3, #16
	WORD $0x6e613863 // shll2.4s	v3, v3, #16
	WORD $0x6e24dc04 // fmul.4s	v4, v0, v4
	WORD $0x6e23dc03 // fmul.4s	v3, v0, v3
	WORD $0x6f300465 // ushr.4s	v5, v3, #16
	WORD $0x4e211ca5 // and.16b	v5, v5, v1
	WORD $0x4ea58463 // add.4s	v3, v3, v5
	WORD $0x6f300485 // ushr.4s	v5, v4, #16
	WORD $0x4e211ca5 // and.16b	v5, v5, v1
	WORD $0x4ea58484 // add.4s	v4, v4, v5
	WORD $0x0e624084 // addhn.4h	v4, v4, v2
	WORD $0x4e624064 // addhn2.8h	v4, v3, v2
	WORD $0x3c810564 // str	q4, [x11], #16
	WORD $0x9100214c // add	x12, x10, #8
	WORD $0x9100414d // add	x13, x10, #16
	WORD $0xaa0c03ea // mov	x10, x12
	WORD $0xeb0901bf // cmp	x13, x9
	BLE  BB0_4

BB0_5:
	WORD $0xeb0c0129 // subs	x9, x9, x12
	BLE  BB0_8
	WORD $0x53103d08 // lsl	w8, w8, #16
	WORD $0x1e270100 // fmov	s0, w8
	WORD $0x8b0c0428 // add	x8, x1, x12, lsl #1
	WORD $0x528fffea // mov	w10, #32767                     ; =0x7fff

BB0_7:
	WORD $0x7940010b // ldrh	w11, [x8]
	WORD $0x53103d6b // lsl	w11, w11, #16
	WORD $0x1e270161 // fmov	s1, w11
	WORD $0x1e210801 // fmul	s1, s0, s1
	WORD $0x1e26002b // fmov	w11, s1
	WORD $0x5310416c // ubfx	w12, w11, #16, #1
	WORD $0x0b0c016b // add	w11, w11, w12
	WORD $0x0b0a016b // add	w11, w11, w10
	WORD $0x53107d6b // lsr	w11, w11, #16
	WORD $0x7800250b // strh	w11, [x8], #2
	WORD $0xf1000529 // subs	x9, x9, #1
	BNE  BB0_7

BB0_8:
	RET
