//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.46.0.20260210
// flags: -march=armv8.6-a+bf16+simd -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/image/asm/basegamma_c_bf16_neon_arm64.c

TEXT ·gamma_c_bf16_neon(SB), $131152-24
	MOVD img+0(FP), R0
	MOVD out+8(FP), R1
	MOVD pgamma+16(FP), R2
	WORD $0xb4003740       // cbz	x0, LBB0_40
	WORD $0xb4003721       // cbz	x1, LBB0_40
	WORD $0xf9400008       // ldr	x8, [x0]
	WORD $0xb40036e8       // cbz	x8, LBB0_40
	WORD $0xf9400028       // ldr	x8, [x1]
	WORD $0xb40036a8       // cbz	x8, LBB0_40
	WORD $0xf9400408       // ldr	x8, [x0, #8]
	WORD $0xf100051f       // cmp	x8, #1
	BLT  BB0_40
	WORD $0x6d003bef       // stp	d15, d14, [sp, #-80]!           ; 16-byte Folded Spill [transformed]
	WORD $0x6d0133ed       // stp	d13, d12, [sp, #16]             ; 16-byte Folded Spill
	WORD $0x6d022beb       // stp	d11, d10, [sp, #32]             ; 16-byte Folded Spill
	WORD $0x6d0323e9       // stp	d9, d8, [sp, #48]               ; 16-byte Folded Spill
	WORD $0xa9047bfd       // stp	x29, x30, [sp, #64]             ; 16-byte Folded Spill
	WORD $0x910103fd       // add	x29, sp, #64
	WORD $0xd2800008       // mov	x8, #0                          ; =0x0
	WORD $0xd2800009       // mov	x9, #0                          ; =0x0
	WORD $0x7940004a       // ldrh	w10, [x2]
	WORD $0x0e020d56       // dup.4h	v22, w10
	WORD $0x529be70a       // mov	w10, #57144                     ; =0xdf38
	WORD $0x72b7ceaa       // movk	w10, #48757, lsl #16
	WORD $0x4e040d40       // dup.4s	v0, w10
	WORD $0x529c320a       // mov	w10, #57744                     ; =0xe190
	WORD $0x72a7d52a       // movk	w10, #16041, lsl #16
	WORD $0x4e040d41       // dup.4s	v1, w10
	WORD $0x529df00a       // mov	w10, #61312                     ; =0xef80
	WORD $0x72b7dfea       // movk	w10, #48895, lsl #16
	WORD $0x4e040d42       // dup.4s	v2, w10
	WORD $0x529ff88a       // mov	w10, #65476                     ; =0xffc4
	WORD $0x72a7efea       // movk	w10, #16255, lsl #16
	WORD $0x4e040d43       // dup.4s	v3, w10
	WORD $0x528e430a       // mov	w10, #29208                     ; =0x7218
	WORD $0x72a7e62a       // movk	w10, #16177, lsl #16
	WORD $0x4e040d44       // dup.4s	v4, w10
	WORD $0x528e430a       // mov	w10, #29208                     ; =0x7218
	WORD $0x72a8562a       // movk	w10, #17073, lsl #16
	WORD $0x4e040d45       // dup.4s	v5, w10
	WORD $0x5295476a       // mov	w10, #43579                     ; =0xaa3b
	WORD $0x72a7f70a       // movk	w10, #16312, lsl #16
	WORD $0x4e040d46       // dup.4s	v6, w10
	WORD $0x5290000a       // mov	w10, #32768                     ; =0x8000
	WORD $0x72a7e62a       // movk	w10, #16177, lsl #16
	WORD $0x4e040d47       // dup.4s	v7, w10
	WORD $0x5290106a       // mov	w10, #32899                     ; =0x8083
	WORD $0x72a72bca       // movk	w10, #14686, lsl #16
	WORD $0x4e040d50       // dup.4s	v16, w10
	WORD $0x52816c2a       // mov	w10, #2913                      ; =0xb61
	WORD $0x72a756ca       // movk	w10, #15030, lsl #16
	WORD $0x4e040d51       // dup.4s	v17, w10
	WORD $0x5291112a       // mov	w10, #34953                     ; =0x8889
	WORD $0x72a7810a       // movk	w10, #15368, lsl #16
	WORD $0x4e040d52       // dup.4s	v18, w10
	WORD $0x5295556a       // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7a54a       // movk	w10, #15658, lsl #16
	WORD $0x4e040d53       // dup.4s	v19, w10
	WORD $0x5295556a       // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7c54a       // movk	w10, #15914, lsl #16
	WORD $0x4e040d54       // dup.4s	v20, w10
	WORD $0x52958a0a       // mov	w10, #44112                     ; =0xac50
	WORD $0x72b855ca       // movk	w10, #49838, lsl #16
	WORD $0x4e040d55       // dup.4s	v21, w10
	WORD $0x2e613ad6       // shll.4s	v22, v22, #16
	WORD $0x6f0307d7       // mvni.4s	v23, #126
	WORD $0x4f0347f8       // movi.4s	v24, #127, lsl #16
	WORD $0x4f03f619       // fmov.4s	v25, #1.00000000
	WORD $0x4f07f61a       // fmov.4s	v26, #-1.00000000
	WORD $0x6f03d7fb       // mvni.4s	v27, #127, msl #16
	WORD $0x6ea0fb7b       // fneg.4s	v27, v27
	WORD $0x4f00043c       // movi.4s	v28, #1
	WORD $0x4f03c7fd       // movi.4s	v29, #127, msl #8
	B    BB0_8

BB0_6:
BB0_7:
	WORD $0x91000529 // add	x9, x9, #1
	WORD $0xf940040a // ldr	x10, [x0, #8]
	WORD $0x91000908 // add	x8, x8, #2
	WORD $0xeb0a013f // cmp	x9, x10
	BGE  BB0_39

BB0_8:
	WORD $0xf9400010 // ldr	x16, [x0]
	WORD $0xf940002a // ldr	x10, [x1]
	WORD $0xf940082b // ldr	x11, [x1, #16]
	WORD $0xa9413011 // ldp	x17, x12, [x0, #16]
	WORD $0xf100219f // cmp	x12, #8
	BGE  BB0_10
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	B    BB0_12

BB0_10:
	WORD $0xd2800002 // mov	x2, #0                          ; =0x0
	WORD $0x9b08422e // madd	x14, x17, x8, x16
	WORD $0x9b08296f // madd	x15, x11, x8, x10

BB0_11:
	WORD $0x3cc105c8 // ldr	q8, [x14], #16
	WORD $0x2f10a51e // ushll.4s	v30, v8, #0
	WORD $0x2e61391f // shll.4s	v31, v8, #16
	WORD $0x6f3907de // ushr.4s	v30, v30, #7
	WORD $0x6f00343e // bic.4s	v30, #1, lsl #8
	WORD $0x4eb787de // add.4s	v30, v30, v23
	WORD $0x4e381fff // and.16b	v31, v31, v24
	WORD $0x4eb91fff // orr.16b	v31, v31, v25
	WORD $0x4e3ad7ff // fadd.4s	v31, v31, v26
	WORD $0x4ea11c29 // mov.16b	v9, v1
	WORD $0x4e21dbde // scvtf.4s	v30, v30
	WORD $0x4e3fcc09 // fmla.4s	v9, v0, v31
	WORD $0x4ea21c4a // mov.16b	v10, v2
	WORD $0x4e29cfea // fmla.4s	v10, v31, v9
	WORD $0x4ea31c69 // mov.16b	v9, v3
	WORD $0x4e2acfe9 // fmla.4s	v9, v31, v10
	WORD $0x4e3ecc89 // fmla.4s	v9, v4, v30
	WORD $0x6e36dd3e // fmul.4s	v30, v9, v22
	WORD $0x6e26dfdf // fmul.4s	v31, v30, v6
	WORD $0x4e218bff // frintn.4s	v31, v31
	WORD $0x6e27dfe9 // fmul.4s	v9, v31, v7
	WORD $0x6e30dfea // fmul.4s	v10, v31, v16
	WORD $0x4ea9d7c9 // fsub.4s	v9, v30, v9
	WORD $0x4eb21e4b // mov.16b	v11, v18
	WORD $0x4eb31e6c // mov.16b	v12, v19
	WORD $0x4eb41e8d // mov.16b	v13, v20
	WORD $0x6e61390e // shll2.4s	v14, v8, #16
	WORD $0x4e381dce // and.16b	v14, v14, v24
	WORD $0x4e29d549 // fadd.4s	v9, v10, v9
	WORD $0x4eb91dca // orr.16b	v10, v14, v25
	WORD $0x4e3ad54a // fadd.4s	v10, v10, v26
	WORD $0x4ea11c2e // mov.16b	v14, v1
	WORD $0x4e2acc0e // fmla.4s	v14, v0, v10
	WORD $0x4ea21c4f // mov.16b	v15, v2
	WORD $0x4e29ce2b // fmla.4s	v11, v17, v9
	WORD $0x4e2ecd4f // fmla.4s	v15, v10, v14
	WORD $0x4ea31c6e // mov.16b	v14, v3
	WORD $0x4e2fcd4e // fmla.4s	v14, v10, v15
	WORD $0x4f0167ea // movi.4s	v10, #63, lsl #24
	WORD $0x4eb91f2f // mov.16b	v15, v25
	WORD $0x4e2bcd2c // fmla.4s	v12, v9, v11
	WORD $0x6f10a508 // ushll2.4s	v8, v8, #0
	WORD $0x6f390508 // ushr.4s	v8, v8, #7
	WORD $0x6f003428 // bic.4s	v8, #1, lsl #8
	WORD $0x4eb78508 // add.4s	v8, v8, v23
	WORD $0x4e21d908 // scvtf.4s	v8, v8
	WORD $0x4e2ccd2d // fmla.4s	v13, v9, v12
	WORD $0x4e28cc8e // fmla.4s	v14, v4, v8
	WORD $0x6e36ddc8 // fmul.4s	v8, v14, v22
	WORD $0x6e26dd0b // fmul.4s	v11, v8, v6
	WORD $0x4e21896b // frintn.4s	v11, v11
	WORD $0x6e27dd6c // fmul.4s	v12, v11, v7
	WORD $0x4e2dcd2a // fmla.4s	v10, v9, v13
	WORD $0x4eacd50c // fsub.4s	v12, v8, v12
	WORD $0x6e30dd6d // fmul.4s	v13, v11, v16
	WORD $0x4e2cd5ac // fadd.4s	v12, v13, v12
	WORD $0x4eb21e4d // mov.16b	v13, v18
	WORD $0x4e2cce2d // fmla.4s	v13, v17, v12
	WORD $0x4e2acd2f // fmla.4s	v15, v9, v10
	WORD $0x4eb31e6a // mov.16b	v10, v19
	WORD $0x4e2dcd8a // fmla.4s	v10, v12, v13
	WORD $0x4eb41e8d // mov.16b	v13, v20
	WORD $0x4e2acd8d // fmla.4s	v13, v12, v10
	WORD $0x4eb91f2a // mov.16b	v10, v25
	WORD $0x4e2fcd2a // fmla.4s	v10, v9, v15
	WORD $0x6ea5e7c9 // fcmgt.4s	v9, v30, v5
	WORD $0x4e21abff // fcvtns.4s	v31, v31
	WORD $0x4f3757ff // shl.4s	v31, v31, #23
	WORD $0x4eb987ff // add.4s	v31, v31, v25
	WORD $0x6ebee6be // fcmgt.4s	v30, v21, v30
	WORD $0x6e3fdd5f // fmul.4s	v31, v10, v31
	WORD $0x4f0167ea // movi.4s	v10, #63, lsl #24
	WORD $0x4e2dcd8a // fmla.4s	v10, v12, v13
	WORD $0x4eb91f2d // mov.16b	v13, v25
	WORD $0x4e2acd8d // fmla.4s	v13, v12, v10
	WORD $0x4eb91f2a // mov.16b	v10, v25
	WORD $0x6ea91f7f // bit.16b	v31, v27, v9
	WORD $0x4e2dcd8a // fmla.4s	v10, v12, v13
	WORD $0x6ea5e509 // fcmgt.4s	v9, v8, v5
	WORD $0x4e21a96b // fcvtns.4s	v11, v11
	WORD $0x4f37556b // shl.4s	v11, v11, #23
	WORD $0x4eb9856b // add.4s	v11, v11, v25
	WORD $0x4e7e1ffe // bic.16b	v30, v31, v30
	WORD $0x6e2bdd5f // fmul.4s	v31, v10, v11
	WORD $0x6ea8e6a8 // fcmgt.4s	v8, v21, v8
	WORD $0x6ea91f7f // bit.16b	v31, v27, v9
	WORD $0x4e681fff // bic.16b	v31, v31, v8
	WORD $0x6f3007e8 // ushr.4s	v8, v31, #16
	WORD $0x4e3c1d08 // and.16b	v8, v8, v28
	WORD $0x4ea887ff // add.4s	v31, v31, v8
	WORD $0x6f3007c8 // ushr.4s	v8, v30, #16
	WORD $0x4e3c1d08 // and.16b	v8, v8, v28
	WORD $0x4ea887de // add.4s	v30, v30, v8
	WORD $0x0e7d43de // addhn.4h	v30, v30, v29
	WORD $0x4e7d43fe // addhn2.8h	v30, v31, v29
	WORD $0x3c8105fe // str	q30, [x15], #16
	WORD $0x9100204d // add	x13, x2, #8
	WORD $0x91004043 // add	x3, x2, #16
	WORD $0xaa0d03e2 // mov	x2, x13
	WORD $0xeb0c007f // cmp	x3, x12
	BLE  BB0_11

BB0_12:
	WORD $0xcb0d018f // sub	x15, x12, x13
	WORD $0xf10005ff // cmp	x15, #1
	BLT  BB0_7
	WORD $0x914083e2 // mov	x2, sp [transformed]
	WORD $0xd10083ee // sub	x14, sp, #32
	WORD $0xf1000dff // cmp	x15, #3
	BHI  BB0_15
	WORD $0xd2800003 // mov	x3, #0                          ; =0x0
	B    BB0_24

BB0_15:
	WORD $0xf10081ff // cmp	x15, #32
	BHS  BB0_17
	WORD $0xd2800003 // mov	x3, #0                          ; =0x0
	B    BB0_21

BB0_17:
	WORD $0x927be5e3 // and	x3, x15, #0x7fffffffffffffe0
	WORD $0x9b087e24 // mul	x4, x17, x8
	WORD $0x8b0d0484 // add	x4, x4, x13, lsl #1
	WORD $0x8b040204 // add	x4, x16, x4
	WORD $0x91008084 // add	x4, x4, #32
	WORD $0x910101c5 // add	x5, x14, #64
	WORD $0xaa0303e6 // mov	x6, x3

BB0_18:
	WORD $0xad7f7c9e // ldp	q30, q31, [x4, #-32]
	WORD $0x2f10a7c8 // ushll.4s	v8, v30, #0
	WORD $0xacc22889 // ldp	q9, q10, [x4], #64
	WORD $0x6e21d908 // ucvtf.4s	v8, v8
	WORD $0x6f10a7de // ushll2.4s	v30, v30, #0
	WORD $0x6e21dbde // ucvtf.4s	v30, v30
	WORD $0x2f10a7eb // ushll.4s	v11, v31, #0
	WORD $0x6e21d96b // ucvtf.4s	v11, v11
	WORD $0x6f10a7ff // ushll2.4s	v31, v31, #0
	WORD $0x6e21dbff // ucvtf.4s	v31, v31
	WORD $0x2f10a52c // ushll.4s	v12, v9, #0
	WORD $0x6e21d98c // ucvtf.4s	v12, v12
	WORD $0x6f10a529 // ushll2.4s	v9, v9, #0
	WORD $0x6e21d929 // ucvtf.4s	v9, v9
	WORD $0x2f10a54d // ushll.4s	v13, v10, #0
	WORD $0x6e21d9ad // ucvtf.4s	v13, v13
	WORD $0xad3e78a8 // stp	q8, q30, [x5, #-64]
	WORD $0x6f10a55e // ushll2.4s	v30, v10, #0
	WORD $0xad3f7cab // stp	q11, q31, [x5, #-32]
	WORD $0xad0024ac // stp	q12, q9, [x5]
	WORD $0x6e21dbde // ucvtf.4s	v30, v30
	WORD $0xad0178ad // stp	q13, q30, [x5, #32]
	WORD $0x910200a5 // add	x5, x5, #128
	WORD $0xf10080c6 // subs	x6, x6, #32
	BNE  BB0_18
	WORD $0xeb0301ff // cmp	x15, x3
	BEQ  BB0_26
	WORD $0xf27e09ff // tst	x15, #0x1c
	BEQ  BB0_24

BB0_21:
	WORD $0xaa0303e6 // mov	x6, x3
	WORD $0x92400584 // and	x4, x12, #0x3
	WORD $0x8b0309c5 // add	x5, x14, x3, lsl #2
	WORD $0x9b087e23 // mul	x3, x17, x8
	WORD $0x8b0d0463 // add	x3, x3, x13, lsl #1
	WORD $0x8b060467 // add	x7, x3, x6, lsl #1
	WORD $0xcb0401e3 // sub	x3, x15, x4
	WORD $0x8b0d00c6 // add	x6, x6, x13
	WORD $0x8b0400c6 // add	x6, x6, x4
	WORD $0xcb0c00c6 // sub	x6, x6, x12
	WORD $0x8b070207 // add	x7, x16, x7

BB0_22:
	WORD $0xfc4084fe // ldr	d30, [x7], #8
	WORD $0x2f10a7de // ushll.4s	v30, v30, #0
	WORD $0x6e21dbde // ucvtf.4s	v30, v30
	WORD $0x3c8104be // str	q30, [x5], #16
	WORD $0xb10010c6 // adds	x6, x6, #4
	BNE  BB0_22
	WORD $0xb40001a4 // cbz	x4, LBB0_26

BB0_24:
	WORD $0x8b0d0064 // add	x4, x3, x13
	WORD $0xcb0c0084 // sub	x4, x4, x12
	WORD $0x8b0309c5 // add	x5, x14, x3, lsl #2
	WORD $0x9b087e31 // mul	x17, x17, x8
	WORD $0x8b030631 // add	x17, x17, x3, lsl #1
	WORD $0x8b0d0631 // add	x17, x17, x13, lsl #1
	WORD $0x8b110210 // add	x16, x16, x17

BB0_25:
	WORD $0x78402611 // ldrh	w17, [x16], #2
	WORD $0x1e23023e // ucvtf	s30, w17
	WORD $0xbc0044be // str	s30, [x5], #4
	WORD $0xb1000484 // adds	x4, x4, #1
	BLO  BB0_25

BB0_26:
	WORD $0x3dc001de // ldr	q30, [x14]
	WORD $0x2f10a7df // ushll.4s	v31, v30, #0
	WORD $0x2e613bc8 // shll.4s	v8, v30, #16
	WORD $0x6f3907ff // ushr.4s	v31, v31, #7
	WORD $0x6f00343f // bic.4s	v31, #1, lsl #8
	WORD $0x4eb787ff // add.4s	v31, v31, v23
	WORD $0x4e21dbff // scvtf.4s	v31, v31
	WORD $0x4e381d08 // and.16b	v8, v8, v24
	WORD $0x4eb91d08 // orr.16b	v8, v8, v25
	WORD $0x4e3ad508 // fadd.4s	v8, v8, v26
	WORD $0x4ea11c29 // mov.16b	v9, v1
	WORD $0x4e28cc09 // fmla.4s	v9, v0, v8
	WORD $0x4ea21c4a // mov.16b	v10, v2
	WORD $0x4e29cd0a // fmla.4s	v10, v8, v9
	WORD $0x4ea31c69 // mov.16b	v9, v3
	WORD $0x4e2acd09 // fmla.4s	v9, v8, v10
	WORD $0x4e3fcc89 // fmla.4s	v9, v4, v31
	WORD $0x6e36dd3f // fmul.4s	v31, v9, v22
	WORD $0x6ea5e7e8 // fcmgt.4s	v8, v31, v5
	WORD $0x6e26dfe9 // fmul.4s	v9, v31, v6
	WORD $0x4e218929 // frintn.4s	v9, v9
	WORD $0x6e27dd2a // fmul.4s	v10, v9, v7
	WORD $0x4eaad7ea // fsub.4s	v10, v31, v10
	WORD $0x6e30dd2b // fmul.4s	v11, v9, v16
	WORD $0x4e2ad56a // fadd.4s	v10, v11, v10
	WORD $0x4eb21e4b // mov.16b	v11, v18
	WORD $0x4e2ace2b // fmla.4s	v11, v17, v10
	WORD $0x4eb31e6c // mov.16b	v12, v19
	WORD $0x4e2bcd4c // fmla.4s	v12, v10, v11
	WORD $0x4eb41e8b // mov.16b	v11, v20
	WORD $0x4e2ccd4b // fmla.4s	v11, v10, v12
	WORD $0x4f0167ec // movi.4s	v12, #63, lsl #24
	WORD $0x4e2bcd4c // fmla.4s	v12, v10, v11
	WORD $0x4eb91f2b // mov.16b	v11, v25
	WORD $0x4e2ccd4b // fmla.4s	v11, v10, v12
	WORD $0x4eb91f2c // mov.16b	v12, v25
	WORD $0x4e2bcd4c // fmla.4s	v12, v10, v11
	WORD $0x4e21a929 // fcvtns.4s	v9, v9
	WORD $0x4f375529 // shl.4s	v9, v9, #23
	WORD $0x4eb98529 // add.4s	v9, v9, v25
	WORD $0x6e29dd89 // fmul.4s	v9, v12, v9
	WORD $0x6ebfe6bf // fcmgt.4s	v31, v21, v31
	WORD $0x6e691f68 // bsl.16b	v8, v27, v9
	WORD $0x4e7f1d1f // bic.16b	v31, v8, v31
	WORD $0x6f10a7c8 // ushll2.4s	v8, v30, #0
	WORD $0x6e613bde // shll2.4s	v30, v30, #16
	WORD $0x6f390508 // ushr.4s	v8, v8, #7
	WORD $0x6f003428 // bic.4s	v8, #1, lsl #8
	WORD $0x4eb78508 // add.4s	v8, v8, v23
	WORD $0x4e21d908 // scvtf.4s	v8, v8
	WORD $0x4e381fde // and.16b	v30, v30, v24
	WORD $0x4eb91fde // orr.16b	v30, v30, v25
	WORD $0x4e3ad7de // fadd.4s	v30, v30, v26
	WORD $0x4ea11c29 // mov.16b	v9, v1
	WORD $0x4e3ecc09 // fmla.4s	v9, v0, v30
	WORD $0x4ea21c4a // mov.16b	v10, v2
	WORD $0x4e29cfca // fmla.4s	v10, v30, v9
	WORD $0x4ea31c69 // mov.16b	v9, v3
	WORD $0x4e2acfc9 // fmla.4s	v9, v30, v10
	WORD $0x4e28cc89 // fmla.4s	v9, v4, v8
	WORD $0x6e36dd3e // fmul.4s	v30, v9, v22
	WORD $0x6ea5e7c8 // fcmgt.4s	v8, v30, v5
	WORD $0x6e26dfc9 // fmul.4s	v9, v30, v6
	WORD $0x4e218929 // frintn.4s	v9, v9
	WORD $0x6e27dd2a // fmul.4s	v10, v9, v7
	WORD $0x4eaad7ca // fsub.4s	v10, v30, v10
	WORD $0x6e30dd2b // fmul.4s	v11, v9, v16
	WORD $0x4e2ad56a // fadd.4s	v10, v11, v10
	WORD $0x4eb21e4b // mov.16b	v11, v18
	WORD $0x4e2ace2b // fmla.4s	v11, v17, v10
	WORD $0x4eb31e6c // mov.16b	v12, v19
	WORD $0x4e2bcd4c // fmla.4s	v12, v10, v11
	WORD $0x4eb41e8b // mov.16b	v11, v20
	WORD $0x4e2ccd4b // fmla.4s	v11, v10, v12
	WORD $0x4f0167ec // movi.4s	v12, #63, lsl #24
	WORD $0x4e2bcd4c // fmla.4s	v12, v10, v11
	WORD $0x4eb91f2b // mov.16b	v11, v25
	WORD $0x4e2ccd4b // fmla.4s	v11, v10, v12
	WORD $0x4eb91f2c // mov.16b	v12, v25
	WORD $0x4e2bcd4c // fmla.4s	v12, v10, v11
	WORD $0x4e21a929 // fcvtns.4s	v9, v9
	WORD $0x4f375529 // shl.4s	v9, v9, #23
	WORD $0x4eb98529 // add.4s	v9, v9, v25
	WORD $0x6e29dd89 // fmul.4s	v9, v12, v9
	WORD $0x6ebee6be // fcmgt.4s	v30, v21, v30
	WORD $0x6e691f68 // bsl.16b	v8, v27, v9
	WORD $0x4e7e1d1e // bic.16b	v30, v8, v30
	WORD $0x6f3007c8 // ushr.4s	v8, v30, #16
	WORD $0x4e3c1d08 // and.16b	v8, v8, v28
	WORD $0x4ea887de // add.4s	v30, v30, v8
	WORD $0x6f3007e8 // ushr.4s	v8, v31, #16
	WORD $0x4e3c1d08 // and.16b	v8, v8, v28
	WORD $0x4ea887ff // add.4s	v31, v31, v8
	WORD $0x0e7d43ff // addhn.4h	v31, v31, v29
	WORD $0x4e7d43df // addhn2.8h	v31, v30, v29
	WORD $0x3d8001df // str	q31, [x14]
	WORD $0xf1000dff // cmp	x15, #3
	BHI  BB0_28
	WORD $0xd2800010 // mov	x16, #0                         ; =0x0
	B    BB0_37

BB0_28:
	WORD $0xf10081ff // cmp	x15, #32
	BHS  BB0_30
	WORD $0xd2800010 // mov	x16, #0                         ; =0x0
	B    BB0_34

BB0_30:
	WORD $0x927be5f0 // and	x16, x15, #0x7fffffffffffffe0
	WORD $0x910101d1 // add	x17, x14, #64
	WORD $0x9b087d63 // mul	x3, x11, x8
	WORD $0x8b0d0463 // add	x3, x3, x13, lsl #1
	WORD $0x8b030143 // add	x3, x10, x3
	WORD $0x91008063 // add	x3, x3, #32
	WORD $0xaa1003e4 // mov	x4, x16

BB0_31:
	WORD $0xad7e7e3e // ldp	q30, q31, [x17, #-64]
	WORD $0xad7f2628 // ldp	q8, q9, [x17, #-32]
	WORD $0xad402e2a // ldp	q10, q11, [x17]
	WORD $0xad41362c // ldp	q12, q13, [x17, #32]
	WORD $0x6ea1bbff // fcvtzu.4s	v31, v31
	WORD $0x6ea1bbde // fcvtzu.4s	v30, v30
	WORD $0x4e5f1bde // uzp1.8h	v30, v30, v31
	WORD $0x6ea1b93f // fcvtzu.4s	v31, v9
	WORD $0x6ea1b908 // fcvtzu.4s	v8, v8
	WORD $0x4e5f191f // uzp1.8h	v31, v8, v31
	WORD $0x6ea1b968 // fcvtzu.4s	v8, v11
	WORD $0x6ea1b949 // fcvtzu.4s	v9, v10
	WORD $0x4e481928 // uzp1.8h	v8, v9, v8
	WORD $0x6ea1b9a9 // fcvtzu.4s	v9, v13
	WORD $0x6ea1b98a // fcvtzu.4s	v10, v12
	WORD $0x4e491949 // uzp1.8h	v9, v10, v9
	WORD $0xad3f7c7e // stp	q30, q31, [x3, #-32]
	WORD $0xac822468 // stp	q8, q9, [x3], #64
	WORD $0x91020231 // add	x17, x17, #128
	WORD $0xf1008084 // subs	x4, x4, #32
	BNE  BB0_31
	WORD $0xeb1001ff // cmp	x15, x16
	BEQ  BB0_6
	WORD $0xf27e09ff // tst	x15, #0x1c
	BEQ  BB0_37

BB0_34:
	WORD $0xaa1003e4 // mov	x4, x16
	WORD $0x92400591 // and	x17, x12, #0x3
	WORD $0x9b087d70 // mul	x16, x11, x8
	WORD $0x8b0d0610 // add	x16, x16, x13, lsl #1
	WORD $0x8b040605 // add	x5, x16, x4, lsl #1
	WORD $0x8b0409c3 // add	x3, x14, x4, lsl #2
	WORD $0xcb1101f0 // sub	x16, x15, x17
	WORD $0x8b0d008f // add	x15, x4, x13
	WORD $0x8b1101ef // add	x15, x15, x17
	WORD $0xcb0c01ef // sub	x15, x15, x12
	WORD $0x8b050144 // add	x4, x10, x5

BB0_35:
	WORD $0x3cc1047e // ldr	q30, [x3], #16
	WORD $0x6ea1bbde // fcvtzu.4s	v30, v30
	WORD $0x0e612bde // xtn.4h	v30, v30
	WORD $0xfc00849e // str	d30, [x4], #8
	WORD $0xb10011ef // adds	x15, x15, #4
	BNE  BB0_35
	WORD $0xb4ffd431 // cbz	x17, LBB0_6

BB0_37:
	WORD $0x8b0d020f // add	x15, x16, x13
	WORD $0xcb0c01ec // sub	x12, x15, x12
	WORD $0x9b087d6b // mul	x11, x11, x8
	WORD $0x8b10056b // add	x11, x11, x16, lsl #1
	WORD $0x8b0d056b // add	x11, x11, x13, lsl #1
	WORD $0x8b0b014a // add	x10, x10, x11
	WORD $0x8b1009cb // add	x11, x14, x16, lsl #2

BB0_38:
	WORD $0xbc40457e // ldr	s30, [x11], #4
	WORD $0x1e3803cd // fcvtzs	w13, s30
	WORD $0x7800254d // strh	w13, [x10], #2
	WORD $0xb100058c // adds	x12, x12, #1
	BLO  BB0_38
	B    BB0_6

BB0_39:
	WORD $0xd10103bf // sub	sp, x29, #64
	WORD $0xa9447bfd // ldp	x29, x30, [sp, #64]             ; 16-byte Folded Reload
	WORD $0x6d4323e9 // ldp	d9, d8, [sp, #48]               ; 16-byte Folded Reload
	WORD $0x6d422beb // ldp	d11, d10, [sp, #32]             ; 16-byte Folded Reload
	WORD $0x6d4133ed // ldp	d13, d12, [sp, #16]             ; 16-byte Folded Reload
	WORD $0x6d403bef // ldp	d15, d14, [sp], #80             ; 16-byte Folded Reload [transformed]

BB0_40:
	RET
