// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

//go:build amd64 && goexperiment.simd

package specialize

import (
	"simd/archsimd"

	"github.com/ajroetker/go-highway/hwy"
)

var MulAddFloat32 func(x []float32, y []float32, out []float32)
var MulAddFloat64 func(x []float64, y []float64, out []float64)
var MulAddFloat16 func(x []hwy.Float16, y []hwy.Float16, out []hwy.Float16)
var MulAddBFloat16 func(x []hwy.BFloat16, y []hwy.BFloat16, out []hwy.BFloat16)

// MulAdd computes element-wise fused multiply-add: out[i] += x[i] * y[i].
//
// Uses SIMD FMA instructions for vectorized throughput across all targets.
// This primary generates for float32 and float64 only. Float16/BFloat16
// are added by the specialization in muladd_half_base.go (NEON:asm only).
//
// This function dispatches to the appropriate SIMD implementation at runtime.
//
//hwy:gen T={float32, float64}
func MulAdd[T hwy.Floats](x []T, y []T, out []T) {
	switch any(x).(type) {
	case []float32:
		MulAddFloat32(any(x).([]float32), any(y).([]float32), any(out).([]float32))
	case []float64:
		MulAddFloat64(any(x).([]float64), any(y).([]float64), any(out).([]float64))
	case []hwy.Float16:
		MulAddFloat16(any(x).([]hwy.Float16), any(y).([]hwy.Float16), any(out).([]hwy.Float16))
	case []hwy.BFloat16:
		MulAddBFloat16(any(x).([]hwy.BFloat16), any(y).([]hwy.BFloat16), any(out).([]hwy.BFloat16))
	}
}

func init() {
	initSpecializeAll()
}

func initSpecializeAll() {
	if hwy.NoSimdEnv() {
		initSpecializeFallback()
		return
	}
	if archsimd.X86.AVX512() {
		initSpecializeAVX512()
		return
	}
	if archsimd.X86.AVX2() {
		initSpecializeAVX2()
		return
	}
	initSpecializeFallback()
}

func initSpecializeAVX2() {
	MulAddFloat32 = BaseMulAdd_avx2
	MulAddFloat64 = BaseMulAdd_avx2_Float64
}

func initSpecializeAVX512() {
	MulAddFloat32 = BaseMulAdd_avx512
	MulAddFloat64 = BaseMulAdd_avx512_Float64
}

func initSpecializeFallback() {
	MulAddFloat32 = BaseMulAdd_fallback
	MulAddFloat64 = BaseMulAdd_fallback_Float64
}
