//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   22.1.0
// 	objdump 2.46.0.20260210
// flags: -march=armv8.2-a+fp16+simd -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/matvec/asm/basetrsvlt_c_f16_neon_arm64.c

TEXT ·trsvlt_c_f16_neon(SB), $0-40
	MOVD l+0(FP), R0
	MOVD b+8(FP), R1
	MOVD pn+16(FP), R2
	MOVD plen_l+24(FP), R3
	MOVD plen_b+32(FP), R4
	WORD $0xf9400048       // ldr	x8, [x2]
	WORD $0xf1000509       // subs	x9, x8, #1
	BLT  BB0_9
	WORD $0x9b097d09       // mul	x9, x8, x9
	WORD $0x8b090409       // add	x9, x0, x9, lsl #1
	WORD $0xcb0807ea       // neg	x10, x8, lsl #1
	WORD $0xaa0803eb       // mov	x11, x8
	B    BB0_3

BB0_2:
	WORD $0x8b0a0129 // add	x9, x9, x10
	WORD $0xf100097f // cmp	x11, #2
	WORD $0xaa0c03eb // mov	x11, x12
	BLO  BB0_9

BB0_3:
	WORD $0xd100056c // sub	x12, x11, #1
	WORD $0x7c6c7820 // ldr	h0, [x1, x12, lsl #1]
	WORD $0x1ee2c000 // fcvt	d0, h0
	WORD $0x9b087d8d // mul	x13, x12, x8
	WORD $0x8b0d040d // add	x13, x0, x13, lsl #1
	WORD $0x7c6c79a1 // ldr	h1, [x13, x12, lsl #1]
	WORD $0x1ee2c021 // fcvt	d1, h1
	WORD $0x1e611800 // fdiv	d0, d0, d1
	WORD $0x1e78000d // fcvtzs	w13, d0
	WORD $0x1ee301a0 // ucvtf	h0, w13
	WORD $0x7c2c7820 // str	h0, [x1, x12, lsl #1]
	WORD $0x1ee24000 // fcvt	s0, h0
	WORD $0xf100257f // cmp	x11, #9
	BLO  BB0_7
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0x1e214001 // fneg	s1, s0
	WORD $0x1e23c021 // fcvt	h1, s1
	WORD $0xaa0903ee // mov	x14, x9
	WORD $0xaa0103ef // mov	x15, x1

BB0_5:
	WORD $0x3dc001e2 // ldr	q2, [x15]
	WORD $0x3cc105c3 // ldr	q3, [x14], #16
	WORD $0x4f011062 // fmla.8h	v2, v3, v1[0]
	WORD $0x3c8105e2 // str	q2, [x15], #16
	WORD $0x910041b0 // add	x16, x13, #16
	WORD $0x910021ad // add	x13, x13, #8
	WORD $0xeb0b021f // cmp	x16, x11
	BLO  BB0_5
	WORD $0xeb0c01bf // cmp	x13, x12
	BLT  BB0_8
	B    BB0_2

BB0_7:
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0xeb0c01bf // cmp	x13, x12
	BGE  BB0_2

BB0_8:
	WORD $0x7c6d7921 // ldr	h1, [x9, x13, lsl #1]
	WORD $0x1ee24021 // fcvt	s1, h1
	WORD $0x7c6d7822 // ldr	h2, [x1, x13, lsl #1]
	WORD $0x1ee24042 // fcvt	s2, h2
	WORD $0x1f018801 // fmsub	s1, s0, s1, s2
	WORD $0x1e23c021 // fcvt	h1, s1
	WORD $0x7c2d7821 // str	h1, [x1, x13, lsl #1]
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0xeb0d019f // cmp	x12, x13
	BNE  BB0_8
	B    BB0_2

BB0_9:
	RET
