//go:build !noasm && amd64

// Assembly function declarations for AVX2 matvec.
// Implementation in matvec_avx2_amd64.s (generated by GoAT from ../c/matvec_avx2_amd64.c)
package asm

import "unsafe"

//go:noescape
func matvec_avx2_f16(m, v, result, prows, pcols unsafe.Pointer)

//go:noescape
func matvec_avx2_bf16(m, v, result, prows, pcols unsafe.Pointer)

//go:noescape
func matvec_avx2_f32(m, v, result, prows, pcols unsafe.Pointer)

//go:noescape
func matvec_avx2_f64(m, v, result, prows, pcols unsafe.Pointer)
