//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   22.1.1
// 	objdump 2.46.0.20260210
// flags: -march=armv8-a+simd+fp -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/activation/asm/baseelu_c_f32_neon_arm64.c

TEXT ·elu_c_f32_neon(SB), $0-32
	MOVD input+0(FP), R0
	MOVD output+8(FP), R1
	MOVD palpha+16(FP), R2
	MOVD plen_input+24(FP), R3
	WORD $0xf9400068           // ldr	x8, [x3]
	CBZ  R8, BB0_12
	WORD $0xbd400040           // ldr	s0, [x2]
	WORD $0xf100111f           // cmp	x8, #4
	BGE  BB0_3
	WORD $0xd2800009           // mov	x9, #0                          ; =0x0
	B    BB0_5

BB0_3:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0x528e430a // mov	w10, #29208                     ; =0x7218
	WORD $0x72a8562a // movk	w10, #17073, lsl #16
	WORD $0x4e040d41 // dup.4s	v1, w10
	WORD $0x5295476a // mov	w10, #43579                     ; =0xaa3b
	WORD $0x72a7f70a // movk	w10, #16312, lsl #16
	WORD $0x4e040d42 // dup.4s	v2, w10
	WORD $0x5290000a // mov	w10, #32768                     ; =0x8000
	WORD $0x72b7e62a // movk	w10, #48945, lsl #16
	WORD $0x4e040d43 // dup.4s	v3, w10
	WORD $0x5290106a // mov	w10, #32899                     ; =0x8083
	WORD $0x72a72bca // movk	w10, #14686, lsl #16
	WORD $0x4e040d44 // dup.4s	v4, w10
	WORD $0x52816c2a // mov	w10, #2913                      ; =0xb61
	WORD $0x72a756ca // movk	w10, #15030, lsl #16
	WORD $0x4e040d45 // dup.4s	v5, w10
	WORD $0x5291112a // mov	w10, #34953                     ; =0x8889
	WORD $0x72a7810a // movk	w10, #15368, lsl #16
	WORD $0x4e040d46 // dup.4s	v6, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7a54a // movk	w10, #15658, lsl #16
	WORD $0x4e040d47 // dup.4s	v7, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7c54a // movk	w10, #15914, lsl #16
	WORD $0x4e040d50 // dup.4s	v16, w10
	WORD $0x52958a0a // mov	w10, #44112                     ; =0xac50
	WORD $0x72b855ca // movk	w10, #49838, lsl #16
	WORD $0x4e040d51 // dup.4s	v17, w10
	WORD $0x4f03f612 // fmov.4s	v18, #1.00000000
	WORD $0x4f07f613 // fmov.4s	v19, #-1.00000000
	WORD $0x6f03d7f4 // mvni.4s	v20, #127, msl #16
	WORD $0x6ea0fa94 // fneg.4s	v20, v20
	WORD $0xaa0103ea // mov	x10, x1
	WORD $0xaa0003eb // mov	x11, x0

BB0_4:
	WORD $0x3cc10575 // ldr	q21, [x11], #16
	WORD $0x6e22deb6 // fmul.4s	v22, v21, v2
	WORD $0x4e218ad6 // frintn.4s	v22, v22
	WORD $0x6e23ded7 // fmul.4s	v23, v22, v3
	WORD $0x4e37d6b7 // fadd.4s	v23, v21, v23
	WORD $0x6e24ded8 // fmul.4s	v24, v22, v4
	WORD $0x4e37d717 // fadd.4s	v23, v24, v23
	WORD $0x4ea61cd8 // mov.16b	v24, v6
	WORD $0x4e37ccb8 // fmla.4s	v24, v5, v23
	WORD $0x4ea71cf9 // mov.16b	v25, v7
	WORD $0x4e38cef9 // fmla.4s	v25, v23, v24
	WORD $0x4eb01e18 // mov.16b	v24, v16
	WORD $0x4e39cef8 // fmla.4s	v24, v23, v25
	WORD $0x4f0167f9 // movi.4s	v25, #63, lsl #24
	WORD $0x4e38cef9 // fmla.4s	v25, v23, v24
	WORD $0x4f03f618 // fmov.4s	v24, #1.00000000
	WORD $0x4e39cef8 // fmla.4s	v24, v23, v25
	WORD $0x4f03f619 // fmov.4s	v25, #1.00000000
	WORD $0x6ea1e6ba // fcmgt.4s	v26, v21, v1
	WORD $0x4e38cef9 // fmla.4s	v25, v23, v24
	WORD $0x4e21aad6 // fcvtns.4s	v22, v22
	WORD $0x4f3756d6 // shl.4s	v22, v22, #23
	WORD $0x4eb286d6 // add.4s	v22, v22, v18
	WORD $0x6e36df36 // fmul.4s	v22, v25, v22
	WORD $0x6eb5e637 // fcmgt.4s	v23, v17, v21
	WORD $0x4e33d6d6 // fadd.4s	v22, v22, v19
	WORD $0x6eba1e96 // bit.16b	v22, v20, v26
	WORD $0x6eb71e76 // bit.16b	v22, v19, v23
	WORD $0x4f8092d6 // fmul.4s	v22, v22, v0[0]
	WORD $0x4ea0cab7 // fcmgt.4s	v23, v21, #0.0
	WORD $0x6ef71ed5 // bif.16b	v21, v22, v23
	WORD $0x3c810555 // str	q21, [x10], #16
	WORD $0x9100212c // add	x12, x9, #8
	WORD $0x91001129 // add	x9, x9, #4
	WORD $0xeb08019f // cmp	x12, x8
	BLE  BB0_4

BB0_5:
	WORD $0xeb090108 // subs	x8, x8, x9
	BLE  BB0_12
	WORD $0xd37ef52a // lsl	x10, x9, #2
	WORD $0x8b0a0029 // add	x9, x1, x10
	WORD $0x1e22c000 // fcvt	d0, s0
	WORD $0x8b0a000a // add	x10, x0, x10
	WORD $0x5288000b // mov	w11, #16384                     ; =0x4000
	WORD $0x72b8862b // movk	w11, #50225, lsl #16
	WORD $0x1e270161 // fmov	s1, w11
	WORD $0xd2905fcb // mov	x11, #33534                     ; =0x82fe
	WORD $0xf2aca56b // movk	x11, #25899, lsl #16
	WORD $0xf2c2a8eb // movk	x11, #5447, lsl #32
	WORD $0xf2e7feeb // movk	x11, #16375, lsl #48
	WORD $0x9e670162 // fmov	d2, x11
	WORD $0xd2bfdc0b // mov	x11, #4276092928                ; =0xfee00000
	WORD $0xf2c5c84b // movk	x11, #11842, lsl #32
	WORD $0xf2f7fccb // movk	x11, #49126, lsl #48
	WORD $0x9e670163 // fmov	d3, x11
	WORD $0xd2878d8b // mov	x11, #15468                     ; =0x3c6c
	WORD $0xf2a6af2b // movk	x11, #13689, lsl #16
	WORD $0xf2c73deb // movk	x11, #14831, lsl #32
	WORD $0xf2f7bd4b // movk	x11, #48618, lsl #48
	WORD $0x9e670164 // fmov	d4, x11
	WORD $0xd2889c8b // mov	x11, #17636                     ; =0x44e4
	WORD $0xf2acfeab // movk	x11, #26613, lsl #16
	WORD $0xf2dcc8ab // movk	x11, #58949, lsl #32
	WORD $0xf2e7cb4b // movk	x11, #15962, lsl #48
	WORD $0x9e670165 // fmov	d5, x11
	WORD $0xd29b130b // mov	x11, #55448                     ; =0xd898
	WORD $0xf2bdff0b // movk	x11, #61432, lsl #16
	WORD $0xf2dddb0b // movk	x11, #61144, lsl #32
	WORD $0xf2e7c42b // movk	x11, #15905, lsl #48
	WORD $0x9e670166 // fmov	d6, x11
	WORD $0xd293eb8b // mov	x11, #40796                     ; =0x9f5c
	WORD $0xf2b6ef0b // movk	x11, #46968, lsl #16
	WORD $0xf2cfc9eb // movk	x11, #32335, lsl #32
	WORD $0xf2e7d24b // movk	x11, #16018, lsl #48
	WORD $0x9e670167 // fmov	d7, x11
	WORD $0xd298e68b // mov	x11, #50996                     ; =0xc734
	WORD $0xf2b4aacb // movk	x11, #42326, lsl #16
	WORD $0xf2c3bc6b // movk	x11, #7651, lsl #32
	WORD $0xf2e7d8eb // movk	x11, #16071, lsl #48
	WORD $0x9e670170 // fmov	d16, x11
	WORD $0xd294034b // mov	x11, #40986                     ; =0xa01a
	WORD $0xf2a3402b // movk	x11, #6657, lsl #16
	WORD $0xf2c0340b // movk	x11, #416, lsl #32
	WORD $0xf2e7df4b // movk	x11, #16122, lsl #48
	WORD $0x9e670171 // fmov	d17, x11
	WORD $0xd294034b // mov	x11, #40986                     ; =0xa01a
	WORD $0xf2a3402b // movk	x11, #6657, lsl #16
	WORD $0xf2c0340b // movk	x11, #416, lsl #32
	WORD $0xf2e7e54b // movk	x11, #16170, lsl #48
	WORD $0x9e670172 // fmov	d18, x11
	WORD $0xd28d82eb // mov	x11, #27671                     ; =0x6c17
	WORD $0xf2a2d82b // movk	x11, #5825, lsl #16
	WORD $0xf2d82d8b // movk	x11, #49516, lsl #32
	WORD $0xf2e7eacb // movk	x11, #16214, lsl #48
	WORD $0x9e670173 // fmov	d19, x11
	WORD $0xb200e3eb // mov	x11, #1229782938247303441       ; =0x1111111111111111
	WORD $0xf2e7f02b // movk	x11, #16257, lsl #48
	WORD $0x9e670174 // fmov	d20, x11
	WORD $0xb200f3eb // mov	x11, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f4ab // movk	x11, #16293, lsl #48
	WORD $0x9e670175 // fmov	d21, x11
	WORD $0x1e6c1016 // fmov	d22, #0.50000000
	WORD $0xb200f3eb // mov	x11, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f8ab // movk	x11, #16325, lsl #48
	WORD $0x1e6e1017 // fmov	d23, #1.00000000
	WORD $0x9e670178 // fmov	d24, x11
	WORD $0x1e7e1019 // fmov	d25, #-1.00000000
	WORD $0xd2e7fe0b // mov	x11, #4607182418800017408       ; =0x3ff0000000000000
	B    BB0_9

BB0_7:
	WORD $0x1e600b7a // fmul	d26, d27, d0
	WORD $0x1e62435a // fcvt	s26, d26

BB0_8:
	WORD $0xbc00453a // str	s26, [x9], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	BEQ  BB0_12

BB0_9:
	WORD $0xbc40455a // ldr	s26, [x10], #4
	WORD $0x1e202348 // fcmp	s26, #0.0
	BGT  BB0_8
	WORD $0x1e7e101b // fmov	d27, #-1.00000000
	WORD $0x1e212340 // fcmp	s26, s1
	BMI  BB0_7
	WORD $0x1e22c35a // fcvt	d26, s26
	WORD $0x1e620b5b // fmul	d27, d26, d2
	WORD $0x1e66437c // frinta	d28, d27
	WORD $0x1f436b9a // fmadd	d26, d28, d3, d26
	WORD $0x1f446b9a // fmadd	d26, d28, d4, d26
	WORD $0x1f46175c // fmadd	d28, d26, d6, d5
	WORD $0x1f5a1f9c // fmadd	d28, d28, d26, d7
	WORD $0x1f5a439c // fmadd	d28, d28, d26, d16
	WORD $0x1f5a479c // fmadd	d28, d28, d26, d17
	WORD $0x1f5a4b9c // fmadd	d28, d28, d26, d18
	WORD $0x1f5a4f9c // fmadd	d28, d28, d26, d19
	WORD $0x1f5a539c // fmadd	d28, d28, d26, d20
	WORD $0x1f5a579c // fmadd	d28, d28, d26, d21
	WORD $0x1f5a639c // fmadd	d28, d28, d26, d24
	WORD $0x1f5a5b9c // fmadd	d28, d28, d26, d22
	WORD $0x1f5a5f9c // fmadd	d28, d28, d26, d23
	WORD $0x1f5a5f9a // fmadd	d26, d28, d26, d23
	WORD $0x9e64036c // fcvtas	x12, d27
	WORD $0x8b0cd16c // add	x12, x11, x12, lsl #52
	WORD $0x9e67019b // fmov	d27, x12
	WORD $0x1e7b0b5a // fmul	d26, d26, d27
	WORD $0x1e792b5b // fadd	d27, d26, d25
	B    BB0_7

BB0_12:
	RET
