//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   22.1.0
// 	objdump 2.46.0.20260210
// flags: -march=armv8.6-a+bf16+simd -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/activation/asm/basesoftplus_c_bf16_neon_arm64.c

TEXT ·softplus_c_bf16_neon(SB), $64-24
	MOVD input+0(FP), R0
	MOVD output+8(FP), R1
	MOVD plen_input+16(FP), R2
	WORD $0xf9400048           // ldr	x8, [x2]
	CBZ  R8, BB0_14
	WORD $0x6d003bef           // stp	d15, d14, [sp, #-64]!           ; 16-byte Folded Spill [transformed]
	WORD $0x6d0133ed           // stp	d13, d12, [sp, #16]             ; 16-byte Folded Spill
	WORD $0x6d022beb           // stp	d11, d10, [sp, #32]             ; 16-byte Folded Spill
	WORD $0x6d0323e9           // stp	d9, d8, [sp, #48]               ; 16-byte Folded Spill
	WORD $0xf100211f           // cmp	x8, #8
	BGE  BB0_3
	WORD $0xd2800009           // mov	x9, #0                          ; =0x0
	B    BB0_5

BB0_3:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0x528e430a // mov	w10, #29208                     ; =0x7218
	WORD $0x72a8562a // movk	w10, #17073, lsl #16
	WORD $0x4e040d40 // dup.4s	v0, w10
	WORD $0x5295476a // mov	w10, #43579                     ; =0xaa3b
	WORD $0x72a7f70a // movk	w10, #16312, lsl #16
	WORD $0x4e040d41 // dup.4s	v1, w10
	WORD $0x5290000a // mov	w10, #32768                     ; =0x8000
	WORD $0x72a7e62a // movk	w10, #16177, lsl #16
	WORD $0x4e040d42 // dup.4s	v2, w10
	WORD $0x5290106a // mov	w10, #32899                     ; =0x8083
	WORD $0x72a72bca // movk	w10, #14686, lsl #16
	WORD $0x4e040d43 // dup.4s	v3, w10
	WORD $0x52816c2a // mov	w10, #2913                      ; =0xb61
	WORD $0x72a756ca // movk	w10, #15030, lsl #16
	WORD $0x4e040d44 // dup.4s	v4, w10
	WORD $0x5291112a // mov	w10, #34953                     ; =0x8889
	WORD $0x72a7810a // movk	w10, #15368, lsl #16
	WORD $0x4e040d45 // dup.4s	v5, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7a54a // movk	w10, #15658, lsl #16
	WORD $0x4e040d58 // dup.4s	v24, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7c54a // movk	w10, #15914, lsl #16
	WORD $0x4e040d47 // dup.4s	v7, w10
	WORD $0x4f03f611 // fmov.4s	v17, #1.00000000
	WORD $0x52958a0a // mov	w10, #44112                     ; =0xac50
	WORD $0x72b855ca // movk	w10, #49838, lsl #16
	WORD $0x4e040d52 // dup.4s	v18, w10
	WORD $0x6f03d7f3 // mvni.4s	v19, #127, msl #16
	WORD $0x6ea0fa73 // fneg.4s	v19, v19
	WORD $0x4f000435 // movi.4s	v21, #1
	WORD $0x4f03c7f6 // movi.4s	v22, #127, msl #8
	WORD $0x529fbe8a // mov	w10, #65012                     ; =0xfdf4
	WORD $0x72a7f68a // movk	w10, #16308, lsl #16
	WORD $0x4e040d5b // dup.4s	v27, w10
	WORD $0x5291c52a // mov	w10, #36393                     ; =0x8e29
	WORD $0x72a7bc6a // movk	w10, #15843, lsl #16
	WORD $0x4e040d5d // dup.4s	v29, w10
	WORD $0x528924aa // mov	w10, #18725                     ; =0x4925
	WORD $0x72a7c24a // movk	w10, #15890, lsl #16
	WORD $0x4e040d5e // dup.4s	v30, w10
	WORD $0x529999aa // mov	w10, #52429                     ; =0xcccd
	WORD $0x72a7c98a // movk	w10, #15948, lsl #16
	WORD $0x4e040d5f // dup.4s	v31, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7d54a // movk	w10, #16042, lsl #16
	WORD $0x4e040d48 // dup.4s	v8, w10
	WORD $0xaa0103ea // mov	x10, x1
	WORD $0xaa0003eb // mov	x11, x0
	WORD $0x4f0347fc // movi.4s	v28, #127, lsl #16
	WORD $0x4f0167fa // movi.4s	v26, #63, lsl #24
	WORD $0x4f07f609 // fmov.4s	v9, #-1.00000000

BB0_4:
	WORD $0x3cc1056a // ldr	q10, [x11], #16
	WORD $0x2e61394b // shll.4s	v11, v10, #16
	WORD $0x6ea0e56c // fcmgt.4s	v12, v11, v0
	WORD $0x6e21dd6d // fmul.4s	v13, v11, v1
	WORD $0x4e2189ad // frintn.4s	v13, v13
	WORD $0x6e22ddae // fmul.4s	v14, v13, v2
	WORD $0x4eaed56e // fsub.4s	v14, v11, v14
	WORD $0x6e23ddaf // fmul.4s	v15, v13, v3
	WORD $0x4e2ed5ee // fadd.4s	v14, v15, v14
	WORD $0x4ea51caf // mov.16b	v15, v5
	WORD $0x4e2ecc8f // fmla.4s	v15, v4, v14
	WORD $0x4eb81f06 // mov.16b	v6, v24
	WORD $0x4e2fcdc6 // fmla.4s	v6, v14, v15
	WORD $0x4ea71cef // mov.16b	v15, v7
	WORD $0x4e26cdcf // fmla.4s	v15, v14, v6
	WORD $0x4f0167e6 // movi.4s	v6, #63, lsl #24
	WORD $0x4e2fcdc6 // fmla.4s	v6, v14, v15
	WORD $0x4f03f60f // fmov.4s	v15, #1.00000000
	WORD $0x4e26cdcf // fmla.4s	v15, v14, v6
	WORD $0x4f03f606 // fmov.4s	v6, #1.00000000
	WORD $0x4e21a9ad // fcvtns.4s	v13, v13
	WORD $0x4f3755ad // shl.4s	v13, v13, #23
	WORD $0x4e2fcdc6 // fmla.4s	v6, v14, v15
	WORD $0x4eb185ad // add.4s	v13, v13, v17
	WORD $0x6e2ddcc6 // fmul.4s	v6, v6, v13
	WORD $0x6eabe64d // fcmgt.4s	v13, v18, v11
	WORD $0x6eac1e66 // bit.16b	v6, v19, v12
	WORD $0x6e61394c // shll2.4s	v12, v10, #16
	WORD $0x4e6d1cc6 // bic.16b	v6, v6, v13
	WORD $0x6ea0e58d // fcmgt.4s	v13, v12, v0
	WORD $0x6e21dd8e // fmul.4s	v14, v12, v1
	WORD $0x4e2189ce // frintn.4s	v14, v14
	WORD $0x6e22ddcf // fmul.4s	v15, v14, v2
	WORD $0x4eafd58f // fsub.4s	v15, v12, v15
	WORD $0x6f3004d4 // ushr.4s	v20, v6, #16
	WORD $0x6e23ddd7 // fmul.4s	v23, v14, v3
	WORD $0x4e2fd6f7 // fadd.4s	v23, v23, v15
	WORD $0x4ea51caf // mov.16b	v15, v5
	WORD $0x4e37cc8f // fmla.4s	v15, v4, v23
	WORD $0x4eb81f10 // mov.16b	v16, v24
	WORD $0x4eb684c6 // add.4s	v6, v6, v22
	WORD $0x4e2fcef0 // fmla.4s	v16, v23, v15
	WORD $0x4ea71cef // mov.16b	v15, v7
	WORD $0x4e30ceef // fmla.4s	v15, v23, v16
	WORD $0x4f0167f0 // movi.4s	v16, #63, lsl #24
	WORD $0x4e2fcef0 // fmla.4s	v16, v23, v15
	WORD $0x4e351e94 // and.16b	v20, v20, v21
	WORD $0x4f03f60f // fmov.4s	v15, #1.00000000
	WORD $0x4e30ceef // fmla.4s	v15, v23, v16
	WORD $0x4f03f610 // fmov.4s	v16, #1.00000000
	WORD $0x4e2fcef0 // fmla.4s	v16, v23, v15
	WORD $0x4e21a9d7 // fcvtns.4s	v23, v14
	WORD $0x4eb484c6 // add.4s	v6, v6, v20
	WORD $0x4f3756f4 // shl.4s	v20, v23, #23
	WORD $0x4eb18694 // add.4s	v20, v20, v17
	WORD $0x6e34de10 // fmul.4s	v16, v16, v20
	WORD $0x6eace654 // fcmgt.4s	v20, v18, v12
	WORD $0x6ead1e70 // bit.16b	v16, v19, v13
	WORD $0x6f06e597 // movi.2d	v23, #0xffff0000ffff0000
	WORD $0x4e371cc6 // and.16b	v6, v6, v23
	WORD $0x4e741e10 // bic.16b	v16, v16, v20
	WORD $0x6f300614 // ushr.4s	v20, v16, #16
	WORD $0x4e351e94 // and.16b	v20, v20, v21
	WORD $0x4eb68610 // add.4s	v16, v16, v22
	WORD $0x4eb48610 // add.4s	v16, v16, v20
	WORD $0x4e371e10 // and.16b	v16, v16, v23
	WORD $0x4f004437 // movi.4s	v23, #1, lsl #16
	WORD $0x4e37d4c6 // fadd.4s	v6, v6, v23
	WORD $0x6f3004d4 // ushr.4s	v20, v6, #16
	WORD $0x4e351e94 // and.16b	v20, v20, v21
	WORD $0x4eb684c6 // add.4s	v6, v6, v22
	WORD $0x4e37d610 // fadd.4s	v16, v16, v23
	WORD $0x4eb484c6 // add.4s	v6, v6, v20
	WORD $0x6f300614 // ushr.4s	v20, v16, #16
	WORD $0x4e351e94 // and.16b	v20, v20, v21
	WORD $0x4eb68610 // add.4s	v16, v16, v22
	WORD $0x4eb48610 // add.4s	v16, v16, v20
	WORD $0x6f2904d4 // ushr.4s	v20, v6, #23
	WORD $0x6f003434 // bic.4s	v20, #1, lsl #8
	WORD $0x6f0307d9 // mvni.4s	v25, #126
	WORD $0x4eb98694 // add.4s	v20, v20, v25
	WORD $0x4e3c1cc6 // and.16b	v6, v6, v28
	WORD $0x4eb11cc6 // orr.16b	v6, v6, v17
	WORD $0x6ebbe4d7 // fcmgt.4s	v23, v6, v27
	WORD $0x6e3adccd // fmul.4s	v13, v6, v26
	WORD $0x4e21da94 // scvtf.4s	v20, v20
	WORD $0x6eb71da6 // bit.16b	v6, v13, v23
	WORD $0x4e31d68d // fadd.4s	v13, v20, v17
	WORD $0x6eb71db4 // bit.16b	v20, v13, v23
	WORD $0x4e29d4d7 // fadd.4s	v23, v6, v9
	WORD $0x4e31d4c6 // fadd.4s	v6, v6, v17
	WORD $0x6e26fee6 // fdiv.4s	v6, v23, v6
	WORD $0x6e26dcd7 // fmul.4s	v23, v6, v6
	WORD $0x4ebe1fcd // mov.16b	v13, v30
	WORD $0x4ebf1fee // mov.16b	v14, v31
	WORD $0x6f29060f // ushr.4s	v15, v16, #23
	WORD $0x6f00342f // bic.4s	v15, #1, lsl #8
	WORD $0x4e37cfad // fmla.4s	v13, v29, v23
	WORD $0x4eb985ef // add.4s	v15, v15, v25
	WORD $0x4e21d9ef // scvtf.4s	v15, v15
	WORD $0x4e3c1e10 // and.16b	v16, v16, v28
	WORD $0x4eb11e10 // orr.16b	v16, v16, v17
	WORD $0x6ebbe619 // fcmgt.4s	v25, v16, v27
	WORD $0x4e2dceee // fmla.4s	v14, v23, v13
	WORD $0x6e3ade0d // fmul.4s	v13, v16, v26
	WORD $0x6eb91db0 // bit.16b	v16, v13, v25
	WORD $0x4e31d5ed // fadd.4s	v13, v15, v17
	WORD $0x6e6f1db9 // bsl.16b	v25, v13, v15
	WORD $0x4ea81d0d // mov.16b	v13, v8
	WORD $0x4e2eceed // fmla.4s	v13, v23, v14
	WORD $0x4f03f60e // fmov.4s	v14, #1.00000000
	WORD $0x4e29d60f // fadd.4s	v15, v16, v9
	WORD $0x4e31d610 // fadd.4s	v16, v16, v17
	WORD $0x6e30fdf0 // fdiv.4s	v16, v15, v16
	WORD $0x6e30de0f // fmul.4s	v15, v16, v16
	WORD $0x4e2dceee // fmla.4s	v14, v23, v13
	WORD $0x4ebe1fd7 // mov.16b	v23, v30
	WORD $0x4e2fcfb7 // fmla.4s	v23, v29, v15
	WORD $0x4ebf1fed // mov.16b	v13, v31
	WORD $0x4e37cded // fmla.4s	v13, v15, v23
	WORD $0x4ea81d17 // mov.16b	v23, v8
	WORD $0x4e2dcdf7 // fmla.4s	v23, v15, v13
	WORD $0x4f03f60d // fmov.4s	v13, #1.00000000
	WORD $0x4e37cded // fmla.4s	v13, v15, v23
	WORD $0x4e26d4c6 // fadd.4s	v6, v6, v6
	WORD $0x6e2edcc6 // fmul.4s	v6, v6, v14
	WORD $0x4e34cc46 // fmla.4s	v6, v2, v20
	WORD $0x6e23de94 // fmul.4s	v20, v20, v3
	WORD $0x4eb4d4c6 // fsub.4s	v6, v6, v20
	WORD $0x4e30d610 // fadd.4s	v16, v16, v16
	WORD $0x6e2dde10 // fmul.4s	v16, v16, v13
	WORD $0x4e39cc50 // fmla.4s	v16, v2, v25
	WORD $0x6e23df34 // fmul.4s	v20, v25, v3
	WORD $0x4eb4d610 // fsub.4s	v16, v16, v20
	WORD $0x6f3004d4 // ushr.4s	v20, v6, #16
	WORD $0x4e351e94 // and.16b	v20, v20, v21
	WORD $0x4eb484c6 // add.4s	v6, v6, v20
	WORD $0x6f300614 // ushr.4s	v20, v16, #16
	WORD $0x4e351e94 // and.16b	v20, v20, v21
	WORD $0x4eb48610 // add.4s	v16, v16, v20
	WORD $0x0e7640c6 // addhn.4h	v6, v6, v22
	WORD $0x4e764206 // addhn2.8h	v6, v16, v22
	WORD $0x4f004694 // movi.4s	v20, #20, lsl #16
	WORD $0x6eb4e590 // fcmgt.4s	v16, v12, v20
	WORD $0x6eb4e574 // fcmgt.4s	v20, v11, v20
	WORD $0x4e501a90 // uzp1.8h	v16, v20, v16
	WORD $0x6eb01d46 // bit.16b	v6, v10, v16
	WORD $0x2e6138d0 // shll.4s	v16, v6, #16
	WORD $0x6e6138c6 // shll2.4s	v6, v6, #16
	WORD $0x6f00e414 // movi.2d	v20, #0000000000000000
	WORD $0x4e34f610 // fmax.4s	v16, v16, v20
	WORD $0x4e34f4c6 // fmax.4s	v6, v6, v20
	WORD $0x6f3004d4 // ushr.4s	v20, v6, #16
	WORD $0x4e351e94 // and.16b	v20, v20, v21
	WORD $0x4eb484c6 // add.4s	v6, v6, v20
	WORD $0x6f300614 // ushr.4s	v20, v16, #16
	WORD $0x4e351e94 // and.16b	v20, v20, v21
	WORD $0x4eb48610 // add.4s	v16, v16, v20
	WORD $0x0e764210 // addhn.4h	v16, v16, v22
	WORD $0x4e7640d0 // addhn2.8h	v16, v6, v22
	WORD $0x3c810550 // str	q16, [x10], #16
	WORD $0x9100412c // add	x12, x9, #16
	WORD $0x91002129 // add	x9, x9, #8
	WORD $0xeb08019f // cmp	x12, x8
	BLE  BB0_4

BB0_5:
	WORD $0xeb090108 // subs	x8, x8, x9
	BLE  BB0_13
	WORD $0xd37ff92a // lsl	x10, x9, #1
	WORD $0x8b0a0029 // add	x9, x1, x10
	WORD $0x8b0a000a // add	x10, x0, x10
	WORD $0x528fffeb // mov	w11, #32767                     ; =0x7fff
	WORD $0x52a8560c // mov	w12, #1118830592                ; =0x42b00000
	WORD $0x1e270180 // fmov	s0, w12
	WORD $0x52a7f00c // mov	w12, #1065353216                ; =0x3f800000
	WORD $0x1e2c1001 // fmov	s1, #0.50000000
	WORD $0x529fbe8d // mov	w13, #65012                     ; =0xfdf4
	WORD $0x72a7f68d // movk	w13, #16308, lsl #16
	WORD $0x1e2701a2 // fmov	s2, w13
	WORD $0x12800fcd // mov	w13, #-127                      ; =0xffffff81
	WORD $0x12800fae // mov	w14, #-126                      ; =0xffffff82
	WORD $0x1e3e1003 // fmov	s3, #-1.00000000
	WORD $0x1e2e1004 // fmov	s4, #1.00000000
	WORD $0x528924af // mov	w15, #18725                     ; =0x4925
	WORD $0x72a7c24f // movk	w15, #15890, lsl #16
	WORD $0x1e2701e5 // fmov	s5, w15
	WORD $0x5291c52f // mov	w15, #36393                     ; =0x8e29
	WORD $0x72a7bc6f // movk	w15, #15843, lsl #16
	WORD $0x1e2701e6 // fmov	s6, w15
	WORD $0x529999af // mov	w15, #52429                     ; =0xcccd
	WORD $0x72a7c98f // movk	w15, #15948, lsl #16
	WORD $0x1e2701e7 // fmov	s7, w15
	WORD $0x5295556f // mov	w15, #43691                     ; =0xaaab
	WORD $0x72a7d54f // movk	w15, #16042, lsl #16
	WORD $0x1e2701f0 // fmov	s16, w15
	WORD $0x5290000f // mov	w15, #32768                     ; =0x8000
	WORD $0x72a7e62f // movk	w15, #16177, lsl #16
	WORD $0x1e2701f1 // fmov	s17, w15
	WORD $0x5290106f // mov	w15, #32899                     ; =0x8083
	WORD $0x72b72bcf // movk	w15, #47454, lsl #16
	WORD $0x1e2701f2 // fmov	s18, w15
	WORD $0x5295476f // mov	w15, #43579                     ; =0xaa3b
	WORD $0x72a7f70f // movk	w15, #16312, lsl #16
	WORD $0x1e2701f3 // fmov	s19, w15
	WORD $0x5290000f // mov	w15, #32768                     ; =0x8000
	WORD $0x72b7e62f // movk	w15, #48945, lsl #16
	WORD $0x1e2701f4 // fmov	s20, w15
	WORD $0x5290106f // mov	w15, #32899                     ; =0x8083
	WORD $0x72a72bcf // movk	w15, #14686, lsl #16
	WORD $0x1e2701f5 // fmov	s21, w15
	WORD $0x5291112f // mov	w15, #34953                     ; =0x8889
	WORD $0x72a7810f // movk	w15, #15368, lsl #16
	WORD $0x1e2701f6 // fmov	s22, w15
	WORD $0x52816c2f // mov	w15, #2913                      ; =0xb61
	WORD $0x72a756cf // movk	w15, #15030, lsl #16
	WORD $0x1e2701f7 // fmov	s23, w15
	WORD $0x5295556f // mov	w15, #43691                     ; =0xaaab
	WORD $0x72a7a54f // movk	w15, #15658, lsl #16
	WORD $0x1e2701f8 // fmov	s24, w15
	WORD $0x5295556f // mov	w15, #43691                     ; =0xaaab
	WORD $0x72a7c54f // movk	w15, #15914, lsl #16
	WORD $0x1e2701f9 // fmov	s25, w15
	B    BB0_10

BB0_7:
	WORD $0x52aff00f // mov	w15, #2139095040                ; =0x7f800000

BB0_8:
	WORD $0x531041f0 // ubfx	w16, w15, #16, #1
	WORD $0x0b0b01ef // add	w15, w15, w11
	WORD $0x0b1001ef // add	w15, w15, w16
	WORD $0x53107def // lsr	w15, w15, #16
	WORD $0x110005ef // add	w15, w15, #1
	WORD $0x53077df0 // lsr	w16, w15, #7
	WORD $0x52a7f011 // mov	w17, #1065353216                ; =0x3f800000
	WORD $0x331019f1 // bfi	w17, w15, #16, #7
	WORD $0x1e27023a // fmov	s26, w17
	WORD $0x1e210b5b // fmul	s27, s26, s1
	WORD $0x1e222340 // fcmp	s26, s2
	WORD $0x1a8dc1cf // csel	w15, w14, w13, gt
	WORD $0x0b3001ef // add	w15, w15, w16, uxtb
	WORD $0x1e2201fc // scvtf	s28, w15
	WORD $0x1e3acf7a // fcsel	s26, s27, s26, gt
	WORD $0x1e232b5b // fadd	s27, s26, s3
	WORD $0x1e242b5a // fadd	s26, s26, s4
	WORD $0x1e3a1b7a // fdiv	s26, s27, s26
	WORD $0x1e3a0b5b // fmul	s27, s26, s26
	WORD $0x1f06177d // fmadd	s29, s27, s6, s5
	WORD $0x1f1b1fbd // fmadd	s29, s29, s27, s7
	WORD $0x1f1b43bd // fmadd	s29, s29, s27, s16
	WORD $0x1f1b13bb // fmadd	s27, s29, s27, s4
	WORD $0x1e3a2b5a // fadd	s26, s26, s26
	WORD $0x1e3b0b5a // fmul	s26, s26, s27
	WORD $0x1f116b9a // fmadd	s26, s28, s17, s26
	WORD $0x1f126b9a // fmadd	s26, s28, s18, s26
	WORD $0x1e26034f // fmov	w15, s26
	WORD $0x531041f0 // ubfx	w16, w15, #16, #1
	WORD $0x0b1001ef // add	w15, w15, w16
	WORD $0x0b0b01ef // add	w15, w15, w11
	WORD $0x53107def // lsr	w15, w15, #16

BB0_9:
	WORD $0x1e2301fa // ucvtf	s26, w15
	WORD $0x1e26034f // fmov	w15, s26
	WORD $0x531041f0 // ubfx	w16, w15, #16, #1
	WORD $0x0b1001ef // add	w15, w15, w16
	WORD $0x0b0b01ef // add	w15, w15, w11
	WORD $0x53107def // lsr	w15, w15, #16
	WORD $0x7800252f // strh	w15, [x9], #2
	WORD $0xf1000508 // subs	x8, x8, #1
	BEQ  BB0_13

BB0_10:
	WORD $0x7840254f // ldrh	w15, [x10], #2
	WORD $0x710051ff // cmp	w15, #20
	BHI  BB0_9
	WORD $0x53103def // lsl	w15, w15, #16
	WORD $0x1e2701fa // fmov	s26, w15
	WORD $0x1e202340 // fcmp	s26, s0
	BGT  BB0_7
	WORD $0x1e330b5b // fmul	s27, s26, s19
	WORD $0x1e26437c // frinta	s28, s27
	WORD $0x1f146b9a // fmadd	s26, s28, s20, s26
	WORD $0x1f156b9a // fmadd	s26, s28, s21, s26
	WORD $0x1f175b5c // fmadd	s28, s26, s23, s22
	WORD $0x1f1a639c // fmadd	s28, s28, s26, s24
	WORD $0x1f1a679c // fmadd	s28, s28, s26, s25
	WORD $0x1f1a079c // fmadd	s28, s28, s26, s1
	WORD $0x1f1a139c // fmadd	s28, s28, s26, s4
	WORD $0x1f1a139a // fmadd	s26, s28, s26, s4
	WORD $0x1e24036f // fcvtas	w15, s27
	WORD $0x0b0f5d8f // add	w15, w12, w15, lsl #23
	WORD $0x1e2701fb // fmov	s27, w15
	WORD $0x1e3b0b5a // fmul	s26, s26, s27
	WORD $0x1e26034f // fmov	w15, s26
	B    BB0_8

BB0_13:
	WORD $0x6d4323e9 // ldp	d9, d8, [sp, #48]               ; 16-byte Folded Reload
	WORD $0x6d422beb // ldp	d11, d10, [sp, #32]             ; 16-byte Folded Reload
	WORD $0x6d4133ed // ldp	d13, d12, [sp, #16]             ; 16-byte Folded Reload
	WORD $0x6d403bef // ldp	d15, d14, [sp], #64             ; 16-byte Folded Reload [transformed]

BB0_14:
	RET
