//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   22.1.0
// 	objdump 2.46.0.20260210
// flags: -march=armv8.2-a+fp16+simd -fno-builtin-memset -O3
// source: /Users/ajroetker/go/src/github.com/ajroetker/go-highway/hwy/contrib/activation/asm/basegeluapprox_c_f16_neon_arm64.c

TEXT ·geluapprox_c_f16_neon(SB), $0-24
	MOVD input+0(FP), R0
	MOVD output+8(FP), R1
	MOVD plen_input+16(FP), R2
	WORD $0xf9400048           // ldr	x8, [x2]
	CBZ  R8, BB0_12
	WORD $0xf100211f           // cmp	x8, #8
	BGE  BB0_3
	WORD $0xd2800009           // mov	x9, #0                          ; =0x0
	B    BB0_5

BB0_3:
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	WORD $0x5287d9ea // mov	w10, #16079                     ; =0x3ecf
	WORD $0x4e020d40 // dup.8h	v0, w10
	WORD $0x528e430a // mov	w10, #29208                     ; =0x7218
	WORD $0x72b8562a // movk	w10, #49841, lsl #16
	WORD $0x4e040d41 // dup.4s	v1, w10
	WORD $0x5295476a // mov	w10, #43579                     ; =0xaa3b
	WORD $0x72b7f70a // movk	w10, #49080, lsl #16
	WORD $0x4e040d42 // dup.4s	v2, w10
	WORD $0x5290000a // mov	w10, #32768                     ; =0x8000
	WORD $0x72a7e62a // movk	w10, #16177, lsl #16
	WORD $0x4e040d43 // dup.4s	v3, w10
	WORD $0x5290106a // mov	w10, #32899                     ; =0x8083
	WORD $0x72a72bca // movk	w10, #14686, lsl #16
	WORD $0x4e040d44 // dup.4s	v4, w10
	WORD $0x52816c2a // mov	w10, #2913                      ; =0xb61
	WORD $0x72a756ca // movk	w10, #15030, lsl #16
	WORD $0x4e040d45 // dup.4s	v5, w10
	WORD $0x5291112a // mov	w10, #34953                     ; =0x8889
	WORD $0x72a7810a // movk	w10, #15368, lsl #16
	WORD $0x4e040d46 // dup.4s	v6, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7a54a // movk	w10, #15658, lsl #16
	WORD $0x4e040d47 // dup.4s	v7, w10
	WORD $0x5295556a // mov	w10, #43691                     ; =0xaaab
	WORD $0x72a7c54a // movk	w10, #15914, lsl #16
	WORD $0x4e040d50 // dup.4s	v16, w10
	WORD $0x4f03f611 // fmov.4s	v17, #1.00000000
	WORD $0x52958a0a // mov	w10, #44112                     ; =0xac50
	WORD $0x72a855ca // movk	w10, #17070, lsl #16
	WORD $0x4e040d52 // dup.4s	v18, w10
	WORD $0xaa0103ea // mov	x10, x1
	WORD $0xaa0003eb // mov	x11, x0

BB0_4:
	WORD $0x3cc10573 // ldr	q19, [x11], #16
	WORD $0x6e401e74 // fmul.8h	v20, v19, v0
	WORD $0x0e217a95 // fcvtl	v21.4s, v20.4h
	WORD $0x6ea0fab6 // fneg.4s	v22, v21
	WORD $0x6e22deb7 // fmul.4s	v23, v21, v2
	WORD $0x4e218af7 // frintn.4s	v23, v23
	WORD $0x6e23def8 // fmul.4s	v24, v23, v3
	WORD $0x4eb8d6d6 // fsub.4s	v22, v22, v24
	WORD $0x6e24def8 // fmul.4s	v24, v23, v4
	WORD $0x4e36d716 // fadd.4s	v22, v24, v22
	WORD $0x4ea61cd8 // mov.16b	v24, v6
	WORD $0x4e36ccb8 // fmla.4s	v24, v5, v22
	WORD $0x4ea71cf9 // mov.16b	v25, v7
	WORD $0x4e38ced9 // fmla.4s	v25, v22, v24
	WORD $0x4eb01e18 // mov.16b	v24, v16
	WORD $0x4f0167fa // movi.4s	v26, #63, lsl #24
	WORD $0x4f03f61b // fmov.4s	v27, #1.00000000
	WORD $0x4e39ced8 // fmla.4s	v24, v22, v25
	WORD $0x4f03f619 // fmov.4s	v25, #1.00000000
	WORD $0x4e21aaf7 // fcvtns.4s	v23, v23
	WORD $0x4f3756f7 // shl.4s	v23, v23, #23
	WORD $0x4eb186f7 // add.4s	v23, v23, v17
	WORD $0x6e144294 // ext.16b	v20, v20, v20, #8
	WORD $0x4e38ceda // fmla.4s	v26, v22, v24
	WORD $0x0e217a94 // fcvtl	v20.4s, v20.4h
	WORD $0x6ea0fa98 // fneg.4s	v24, v20
	WORD $0x6e22de9c // fmul.4s	v28, v20, v2
	WORD $0x4e218b9c // frintn.4s	v28, v28
	WORD $0x6e23df9d // fmul.4s	v29, v28, v3
	WORD $0x4e3acedb // fmla.4s	v27, v22, v26
	WORD $0x4ebdd718 // fsub.4s	v24, v24, v29
	WORD $0x6e24df9a // fmul.4s	v26, v28, v4
	WORD $0x4e38d758 // fadd.4s	v24, v26, v24
	WORD $0x4ea61cda // mov.16b	v26, v6
	WORD $0x4e38ccba // fmla.4s	v26, v5, v24
	WORD $0x4e3bced9 // fmla.4s	v25, v22, v27
	WORD $0x4ea71cf6 // mov.16b	v22, v7
	WORD $0x4e3acf16 // fmla.4s	v22, v24, v26
	WORD $0x4eb01e1a // mov.16b	v26, v16
	WORD $0x4e36cf1a // fmla.4s	v26, v24, v22
	WORD $0x4f0167f6 // movi.4s	v22, #63, lsl #24
	WORD $0x6e37df37 // fmul.4s	v23, v25, v23
	WORD $0x4e3acf16 // fmla.4s	v22, v24, v26
	WORD $0x6eb5e439 // fcmgt.4s	v25, v1, v21
	WORD $0x6eb2e6b5 // fcmgt.4s	v21, v21, v18
	WORD $0x4e31d6f7 // fadd.4s	v23, v23, v17
	WORD $0x6e37fe37 // fdiv.4s	v23, v17, v23
	WORD $0x4e791ef7 // bic.16b	v23, v23, v25
	WORD $0x4f03f619 // fmov.4s	v25, #1.00000000
	WORD $0x4e36cf19 // fmla.4s	v25, v24, v22
	WORD $0x4f03f616 // fmov.4s	v22, #1.00000000
	WORD $0x4e39cf16 // fmla.4s	v22, v24, v25
	WORD $0x6eb4e438 // fcmgt.4s	v24, v1, v20
	WORD $0x6e771e35 // bsl.16b	v21, v17, v23
	WORD $0x4e21ab97 // fcvtns.4s	v23, v28
	WORD $0x4f3756f7 // shl.4s	v23, v23, #23
	WORD $0x4eb186f7 // add.4s	v23, v23, v17
	WORD $0x6e37ded6 // fmul.4s	v22, v22, v23
	WORD $0x6eb2e694 // fcmgt.4s	v20, v20, v18
	WORD $0x0e216ab5 // fcvtn	v21.4h, v21.4s
	WORD $0x4e31d6d6 // fadd.4s	v22, v22, v17
	WORD $0x6e36fe36 // fdiv.4s	v22, v17, v22
	WORD $0x4e781ed6 // bic.16b	v22, v22, v24
	WORD $0x6e761e34 // bsl.16b	v20, v17, v22
	WORD $0x4e216a95 // fcvtn2	v21.8h, v20.4s
	WORD $0x6e551e73 // fmul.8h	v19, v19, v21
	WORD $0x3c810553 // str	q19, [x10], #16
	WORD $0x9100412c // add	x12, x9, #16
	WORD $0x91002129 // add	x9, x9, #8
	WORD $0xeb08019f // cmp	x12, x8
	BLE  BB0_4

BB0_5:
	WORD $0xeb090108 // subs	x8, x8, x9
	BLE  BB0_12
	WORD $0xd37ff92a // lsl	x10, x9, #1
	WORD $0x8b0a0029 // add	x9, x1, x10
	WORD $0x8b0a000a // add	x10, x0, x10
	WORD $0xd295810b // mov	x11, #44040                     ; =0xac08
	WORD $0xf2ab438b // movk	x11, #23068, lsl #16
	WORD $0xf2c76c8b // movk	x11, #15204, lsl #32
	WORD $0xf2f7ff6b // movk	x11, #49147, lsl #48
	WORD $0x9e670160 // fmov	d0, x11
	WORD $0xd2c5000b // mov	x11, #43980465111040            ; =0x280000000000
	WORD $0xf2e810cb // movk	x11, #16518, lsl #48
	WORD $0x9e670161 // fmov	d1, x11
	WORD $0x1e6e1002 // fmov	d2, #1.00000000
	WORD $0xd2c5000b // mov	x11, #43980465111040            ; =0x280000000000
	WORD $0xf2f810cb // movk	x11, #49286, lsl #48
	WORD $0x9e670163 // fmov	d3, x11
	WORD $0xd2905fcb // mov	x11, #33534                     ; =0x82fe
	WORD $0xf2aca56b // movk	x11, #25899, lsl #16
	WORD $0xf2c2a8eb // movk	x11, #5447, lsl #32
	WORD $0xf2e7feeb // movk	x11, #16375, lsl #48
	WORD $0x9e670164 // fmov	d4, x11
	WORD $0xd2bfdc0b // mov	x11, #4276092928                ; =0xfee00000
	WORD $0xf2c5c84b // movk	x11, #11842, lsl #32
	WORD $0xf2f7fccb // movk	x11, #49126, lsl #48
	WORD $0x9e670165 // fmov	d5, x11
	WORD $0xd2878d8b // mov	x11, #15468                     ; =0x3c6c
	WORD $0xf2a6af2b // movk	x11, #13689, lsl #16
	WORD $0xf2c73deb // movk	x11, #14831, lsl #32
	WORD $0xf2f7bd4b // movk	x11, #48618, lsl #48
	WORD $0x9e670166 // fmov	d6, x11
	WORD $0xd2889c8b // mov	x11, #17636                     ; =0x44e4
	WORD $0xf2acfeab // movk	x11, #26613, lsl #16
	WORD $0xf2dcc8ab // movk	x11, #58949, lsl #32
	WORD $0xf2e7cb4b // movk	x11, #15962, lsl #48
	WORD $0x9e670167 // fmov	d7, x11
	WORD $0xd29b130b // mov	x11, #55448                     ; =0xd898
	WORD $0xf2bdff0b // movk	x11, #61432, lsl #16
	WORD $0xf2dddb0b // movk	x11, #61144, lsl #32
	WORD $0xf2e7c42b // movk	x11, #15905, lsl #48
	WORD $0x9e670170 // fmov	d16, x11
	WORD $0xd293eb8b // mov	x11, #40796                     ; =0x9f5c
	WORD $0xf2b6ef0b // movk	x11, #46968, lsl #16
	WORD $0xf2cfc9eb // movk	x11, #32335, lsl #32
	WORD $0xf2e7d24b // movk	x11, #16018, lsl #48
	WORD $0x9e670171 // fmov	d17, x11
	WORD $0xd298e68b // mov	x11, #50996                     ; =0xc734
	WORD $0xf2b4aacb // movk	x11, #42326, lsl #16
	WORD $0xf2c3bc6b // movk	x11, #7651, lsl #32
	WORD $0xf2e7d8eb // movk	x11, #16071, lsl #48
	WORD $0x9e670172 // fmov	d18, x11
	WORD $0xd294034b // mov	x11, #40986                     ; =0xa01a
	WORD $0xf2a3402b // movk	x11, #6657, lsl #16
	WORD $0xf2c0340b // movk	x11, #416, lsl #32
	WORD $0xf2e7df4b // movk	x11, #16122, lsl #48
	WORD $0x9e670173 // fmov	d19, x11
	WORD $0xd294034b // mov	x11, #40986                     ; =0xa01a
	WORD $0xf2a3402b // movk	x11, #6657, lsl #16
	WORD $0xf2c0340b // movk	x11, #416, lsl #32
	WORD $0xf2e7e54b // movk	x11, #16170, lsl #48
	WORD $0x9e670174 // fmov	d20, x11
	WORD $0xd28d82eb // mov	x11, #27671                     ; =0x6c17
	WORD $0xf2a2d82b // movk	x11, #5825, lsl #16
	WORD $0xf2d82d8b // movk	x11, #49516, lsl #32
	WORD $0xf2e7eacb // movk	x11, #16214, lsl #48
	WORD $0x9e670175 // fmov	d21, x11
	WORD $0xb200e3eb // mov	x11, #1229782938247303441       ; =0x1111111111111111
	WORD $0xf2e7f02b // movk	x11, #16257, lsl #48
	WORD $0x9e670176 // fmov	d22, x11
	WORD $0xb200f3eb // mov	x11, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f4ab // movk	x11, #16293, lsl #48
	WORD $0x9e670177 // fmov	d23, x11
	WORD $0xb200f3eb // mov	x11, #6148914691236517205       ; =0x5555555555555555
	WORD $0xf2e7f8ab // movk	x11, #16325, lsl #48
	WORD $0x9e670178 // fmov	d24, x11
	WORD $0x1e6c1019 // fmov	d25, #0.50000000
	WORD $0xd2e7fe0b // mov	x11, #4607182418800017408       ; =0x3ff0000000000000
	B    BB0_9

BB0_7:
	WORD $0xd2effe0c // mov	x12, #9218868437227405312       ; =0x7ff0000000000000
	WORD $0x9e67019b // fmov	d27, x12

BB0_8:
	WORD $0x1e7b185b // fdiv	d27, d2, d27
	WORD $0x1e78036c // fcvtzs	w12, d27
	WORD $0x1e63019b // ucvtf	d27, w12
	WORD $0x1e7b0b5a // fmul	d26, d26, d27
	WORD $0x1e78034c // fcvtzs	w12, d26
	WORD $0x1ee3019a // ucvtf	h26, w12
	WORD $0x7c00253a // str	h26, [x9], #2
	WORD $0xf1000508 // subs	x8, x8, #1
	BEQ  BB0_12

BB0_9:
	WORD $0x7c40255a // ldr	h26, [x10], #2
	WORD $0x1ee2c35a // fcvt	d26, h26
	WORD $0x1e600b5c // fmul	d28, d26, d0
	WORD $0x1e612380 // fcmp	d28, d1
	BGT  BB0_7
	WORD $0x1e6e101b // fmov	d27, #1.00000000
	WORD $0x1e632380 // fcmp	d28, d3
	BMI  BB0_8
	WORD $0x1e640b9b // fmul	d27, d28, d4
	WORD $0x1e66437d // frinta	d29, d27
	WORD $0x1f4573bc // fmadd	d28, d29, d5, d28
	WORD $0x1f4673bc // fmadd	d28, d29, d6, d28
	WORD $0x1f501f9d // fmadd	d29, d28, d16, d7
	WORD $0x1f5c47bd // fmadd	d29, d29, d28, d17
	WORD $0x1f5c4bbd // fmadd	d29, d29, d28, d18
	WORD $0x1f5c4fbd // fmadd	d29, d29, d28, d19
	WORD $0x1f5c53bd // fmadd	d29, d29, d28, d20
	WORD $0x1f5c57bd // fmadd	d29, d29, d28, d21
	WORD $0x1f5c5bbd // fmadd	d29, d29, d28, d22
	WORD $0x1f5c5fbd // fmadd	d29, d29, d28, d23
	WORD $0x1f5c63bd // fmadd	d29, d29, d28, d24
	WORD $0x1f5c67bd // fmadd	d29, d29, d28, d25
	WORD $0x1f5c0bbd // fmadd	d29, d29, d28, d2
	WORD $0x1f5c0bbc // fmadd	d28, d29, d28, d2
	WORD $0x9e64036c // fcvtas	x12, d27
	WORD $0x8b0cd16c // add	x12, x11, x12, lsl #52
	WORD $0x9e67019b // fmov	d27, x12
	WORD $0x1e7b0b9b // fmul	d27, d28, d27
	WORD $0x1e622b7b // fadd	d27, d27, d2
	B    BB0_8

BB0_12:
	RET
