//go:build !noasm && arm64
// Code generated by hwygen -c. DO NOT EDIT.

package varint

import (
	"unsafe"

	"github.com/ajroetker/go-highway/hwy"
	"github.com/ajroetker/go-highway/hwy/contrib/varint/asm"
)

func init() {
	initMaskedvbyteNeonCAsm()
}

func initMaskedvbyteNeonCAsm() {
	if hwy.NoSimdEnv() || hwy.HasSME() {
		return
	}
	MaskedVByteDecodeGroup = maskedVByteDecodeGroupAsmU8
}

func maskedVByteDecodeGroupAsmU8(src []byte, dst []uint32) (int, int) {
	var p_src unsafe.Pointer
	if len(src) > 0 {
		p_src = unsafe.Pointer(&src[0])
	}
	var p_dst unsafe.Pointer
	if len(dst) > 0 {
		p_dst = unsafe.Pointer(&dst[0])
	}
	lenVal := int64(len(src))
	var out_decoded int64
	var out_consumed int64
	asm.MaskedVByteDecodeGroup_U8(
		p_src,
		p_dst,
		unsafe.Pointer(&lenVal),
		unsafe.Pointer(&out_decoded),
		unsafe.Pointer(&out_consumed),
	)
	return int(out_decoded), int(out_consumed)
}

