//go:build !noasm && arm64
// Code generated by hwygen -c. DO NOT EDIT.

package varint

import (
	"unsafe"

	"github.com/ajroetker/go-highway/hwy"
	"github.com/ajroetker/go-highway/hwy/contrib/varint/asm"
)

func init() {
	initGroupvarintNeonCAsm()
}

func initGroupvarintNeonCAsm() {
	if hwy.NoSimdEnv() {
		return
	}
	DecodeGroupVarint32 = decodeGroupVarint32AsmU8
}

func decodeGroupVarint32AsmU8(src []byte) ([4]uint32, int) {
	var p_src unsafe.Pointer
	if len(src) > 0 {
		p_src = unsafe.Pointer(&src[0])
	}
	lenVal := int64(len(src))
	var out_values [4]uint32
	var out_consumed int64
	asm.DecodeGroupVarint32_U8(
		p_src,
		unsafe.Pointer(&lenVal),
		unsafe.Pointer(&out_values),
		unsafe.Pointer(&out_consumed),
	)
	return out_values, int(out_consumed)
}

