// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

//go:build arm64

package matmul

import (
	"unsafe"

	"github.com/ajroetker/go-highway/hwy/asm"
)

func BaseFusedNF4MatMul_neon(input []float32, packed []uint8, scales []float32, bias []float32, output []float32, M int, K int, N int, groupSize int) {
	if M == 0 || K == 0 || N == 0 {
		return
	}
	numGroups := (N + groupSize - 1) / groupSize
	lanes := 4
	dequantBuf := [4]float32{}
	accBuf := make([]float32, N)
	for m := range M {
		inputRow := input[m*K : (m+1)*K]
		outputRow := output[m*N : (m+1)*N]
		for i := 0; i < N; i++ {
			accBuf[i] = 0
		}
		for k := range K {
			inputVal := asm.BroadcastFloat32x4(inputRow[k])
			baseIdx := k * N
			scaleBase := k * numGroups
			var n int
			for n = 0; n+lanes <= N; n += lanes {
				for lane := range lanes {
					colIdx := n + lane
					weightIdx := baseIdx + colIdx
					packedIdx := weightIdx / 2
					var quantIdx int
					if weightIdx%2 == 0 {
						quantIdx = int(packed[packedIdx] & 0x0F)
					} else {
						quantIdx = int((packed[packedIdx] >> 4) & 0x0F)
					}
					groupIdx := colIdx / groupSize
					scale := scales[scaleBase+groupIdx]
					dequantBuf[lane] = nf4LookupTable[quantIdx] * scale
				}
				weights := asm.LoadFloat32x4((*[4]float32)(unsafe.Pointer(&dequantBuf[0])))
				acc := asm.LoadFloat32x4((*[4]float32)(unsafe.Pointer(&accBuf[n])))
				inputVal.MulAddAcc(weights, &acc)
				acc.Store((*[4]float32)(unsafe.Pointer(&accBuf[n])))
			}
			for ; n < N; n++ {
				weightIdx := baseIdx + n
				packedIdx := weightIdx / 2
				var quantIdx int
				if weightIdx%2 == 0 {
					quantIdx = int(packed[packedIdx] & 0x0F)
				} else {
					quantIdx = int((packed[packedIdx] >> 4) & 0x0F)
				}
				groupIdx := n / groupSize
				scale := scales[scaleBase+groupIdx]
				weight := nf4LookupTable[quantIdx] * scale
				accBuf[n] += inputRow[k] * weight
			}
		}
		var n int
		for n = 0; n+lanes <= N; n += lanes {
			acc := asm.LoadFloat32x4((*[4]float32)(unsafe.Pointer(&accBuf[n])))
			if bias != nil {
				biasVec := asm.LoadFloat32x4((*[4]float32)(unsafe.Pointer(&bias[n])))
				acc = acc.Add(biasVec)
			}
			acc.Store((*[4]float32)(unsafe.Pointer(&outputRow[n])))
		}
		for ; n < N; n++ {
			val := accBuf[n]
			if bias != nil {
				val += bias[n]
			}
			outputRow[n] = val
		}
	}
}

func BaseFusedInt4MatMul_neon(input []float32, packed []uint8, scales []float32, bias []float32, output []float32, M int, K int, N int, groupSize int) {
	if M == 0 || K == 0 || N == 0 {
		return
	}
	numGroups := (N + groupSize - 1) / groupSize
	lanes := 4
	dequantBuf := [4]float32{}
	accBuf := make([]float32, N)
	for m := range M {
		inputRow := input[m*K : (m+1)*K]
		outputRow := output[m*N : (m+1)*N]
		for i := 0; i < N; i++ {
			accBuf[i] = 0
		}
		for k := range K {
			inputVal := asm.BroadcastFloat32x4(inputRow[k])
			baseIdx := k * N
			scaleBase := k * numGroups
			var n int
			for n = 0; n+lanes <= N; n += lanes {
				for lane := range lanes {
					colIdx := n + lane
					weightIdx := baseIdx + colIdx
					packedIdx := weightIdx / 2
					var unsignedVal int
					if weightIdx%2 == 0 {
						unsignedVal = int(packed[packedIdx] & 0x0F)
					} else {
						unsignedVal = int((packed[packedIdx] >> 4) & 0x0F)
					}
					groupIdx := colIdx / groupSize
					scale := scales[scaleBase+groupIdx]
					dequantBuf[lane] = float32(unsignedVal-8) * scale
				}
				weights := asm.LoadFloat32x4((*[4]float32)(unsafe.Pointer(&dequantBuf[0])))
				acc := asm.LoadFloat32x4((*[4]float32)(unsafe.Pointer(&accBuf[n])))
				inputVal.MulAddAcc(weights, &acc)
				acc.Store((*[4]float32)(unsafe.Pointer(&accBuf[n])))
			}
			for ; n < N; n++ {
				weightIdx := baseIdx + n
				packedIdx := weightIdx / 2
				var unsignedVal int
				if weightIdx%2 == 0 {
					unsignedVal = int(packed[packedIdx] & 0x0F)
				} else {
					unsignedVal = int((packed[packedIdx] >> 4) & 0x0F)
				}
				groupIdx := n / groupSize
				scale := scales[scaleBase+groupIdx]
				weight := float32(unsignedVal-8) * scale
				accBuf[n] += inputRow[k] * weight
			}
		}
		var n int
		for n = 0; n+lanes <= N; n += lanes {
			acc := asm.LoadFloat32x4((*[4]float32)(unsafe.Pointer(&accBuf[n])))
			if bias != nil {
				biasVec := asm.LoadFloat32x4((*[4]float32)(unsafe.Pointer(&bias[n])))
				acc = acc.Add(biasVec)
			}
			acc.Store((*[4]float32)(unsafe.Pointer(&outputRow[n])))
		}
		for ; n < N; n++ {
			val := accBuf[n]
			if bias != nil {
				val += bias[n]
			}
			outputRow[n] = val
		}
	}
}
