// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

package matmul

func BaseFusedNF4MatMul_fallback(input []float32, packed []uint8, scales []float32, bias []float32, output []float32, M int, K int, N int, groupSize int) {
	if M == 0 || K == 0 || N == 0 {
		return
	}
	numGroups := (N + groupSize - 1) / groupSize
	dequantBuf := make([]float32, 1)
	accBuf := make([]float32, N)
	for m := range M {
		inputRow := input[m*K : (m+1)*K]
		outputRow := output[m*N : (m+1)*N]
		for i := 0; i < N; i++ {
			accBuf[i] = 0
		}
		for k := range K {
			inputVal := float32(inputRow[k])
			baseIdx := k * N
			scaleBase := k * numGroups
			var n int
			for n = 0; n < N; n++ {
				for lane := range 1 {
					colIdx := n + lane
					weightIdx := baseIdx + colIdx
					packedIdx := weightIdx / 2
					var quantIdx int
					if weightIdx%2 == 0 {
						quantIdx = int(packed[packedIdx] & 0x0F)
					} else {
						quantIdx = int((packed[packedIdx] >> 4) & 0x0F)
					}
					groupIdx := colIdx / groupSize
					scale := scales[scaleBase+groupIdx]
					dequantBuf[lane] = nf4LookupTable[quantIdx] * scale
				}
				weights := dequantBuf[0]
				acc := accBuf[n]
				acc = inputVal*weights + acc
				accBuf[n] = acc
			}
			for ; n < N; n++ {
				weightIdx := baseIdx + n
				packedIdx := weightIdx / 2
				var quantIdx int
				if weightIdx%2 == 0 {
					quantIdx = int(packed[packedIdx] & 0x0F)
				} else {
					quantIdx = int((packed[packedIdx] >> 4) & 0x0F)
				}
				groupIdx := n / groupSize
				scale := scales[scaleBase+groupIdx]
				weight := nf4LookupTable[quantIdx] * scale
				accBuf[n] += inputRow[k] * weight
			}
		}
		var n int
		for n = 0; n < N; n++ {
			acc := accBuf[n]
			if bias != nil {
				biasVec := bias[n]
				acc = acc + biasVec
			}
			outputRow[n] = acc
		}
		for ; n < N; n++ {
			val := accBuf[n]
			if bias != nil {
				val += bias[n]
			}
			outputRow[n] = val
		}
	}
}

func BaseFusedInt4MatMul_fallback(input []float32, packed []uint8, scales []float32, bias []float32, output []float32, M int, K int, N int, groupSize int) {
	if M == 0 || K == 0 || N == 0 {
		return
	}
	numGroups := (N + groupSize - 1) / groupSize
	dequantBuf := make([]float32, 1)
	accBuf := make([]float32, N)
	for m := range M {
		inputRow := input[m*K : (m+1)*K]
		outputRow := output[m*N : (m+1)*N]
		for i := 0; i < N; i++ {
			accBuf[i] = 0
		}
		for k := range K {
			inputVal := float32(inputRow[k])
			baseIdx := k * N
			scaleBase := k * numGroups
			var n int
			for n = 0; n < N; n++ {
				for lane := range 1 {
					colIdx := n + lane
					weightIdx := baseIdx + colIdx
					packedIdx := weightIdx / 2
					var unsignedVal int
					if weightIdx%2 == 0 {
						unsignedVal = int(packed[packedIdx] & 0x0F)
					} else {
						unsignedVal = int((packed[packedIdx] >> 4) & 0x0F)
					}
					groupIdx := colIdx / groupSize
					scale := scales[scaleBase+groupIdx]
					dequantBuf[lane] = float32(unsignedVal-8) * scale
				}
				weights := dequantBuf[0]
				acc := accBuf[n]
				acc = inputVal*weights + acc
				accBuf[n] = acc
			}
			for ; n < N; n++ {
				weightIdx := baseIdx + n
				packedIdx := weightIdx / 2
				var unsignedVal int
				if weightIdx%2 == 0 {
					unsignedVal = int(packed[packedIdx] & 0x0F)
				} else {
					unsignedVal = int((packed[packedIdx] >> 4) & 0x0F)
				}
				groupIdx := n / groupSize
				scale := scales[scaleBase+groupIdx]
				weight := float32(unsignedVal-8) * scale
				accBuf[n] += inputRow[k] * weight
			}
		}
		var n int
		for n = 0; n < N; n++ {
			acc := accBuf[n]
			if bias != nil {
				biasVec := bias[n]
				acc = acc + biasVec
			}
			outputRow[n] = acc
		}
		for ; n < N; n++ {
			val := accBuf[n]
			if bias != nil {
				val += bias[n]
			}
			outputRow[n] = val
		}
	}
}
