//go:build !noasm && arm64
// Code generated by hwygen -c. DO NOT EDIT.

package matmul

import (
	"unsafe"

	"github.com/ajroetker/go-highway/hwy"
	"github.com/ajroetker/go-highway/hwy/contrib/matmul/asm"
)

func init() {
	initTrsmNeonCAsm()
}

func initTrsmNeonCAsm() {
	if hwy.NoSimdEnv() {
		return
	}
	TrsmLNFloat32 = trsmLNAsmF32
	TrsmLNFloat64 = trsmLNAsmF64
	TrsmLTFloat32 = trsmLTAsmF32
	TrsmLTFloat64 = trsmLTAsmF64
	if hwy.HasARMFP16() {
		TrsmLNFloat16 = trsmLNAsmF16
		TrsmLTFloat16 = trsmLTAsmF16
	}
	if hwy.HasARMBF16() {
		TrsmLNBFloat16 = trsmLNAsmBF16
		TrsmLTBFloat16 = trsmLTAsmBF16
	}
}

func trsmLNAsmF16(l, b []hwy.Float16, n, nrhs int) {
	if len(l) < n*n {
		panic("trsm: L slice too short")
	}
	if len(b) < n*nrhs {
		panic("trsm: B slice too short")
	}
	var p_l unsafe.Pointer
	if len(l) > 0 {
		p_l = unsafe.Pointer(&l[0])
	}
	var p_b unsafe.Pointer
	if len(b) > 0 {
		p_b = unsafe.Pointer(&b[0])
	}
	nVal := int64(n)
	nrhsVal := int64(nrhs)
	len_lVal := int64(len(l))
	len_bVal := int64(len(b))
	asm.TrsmLN_F16(
		p_l,
		p_b,
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&nrhsVal),
		unsafe.Pointer(&len_lVal),
		unsafe.Pointer(&len_bVal),
	)
}

func trsmLNAsmBF16(l, b []hwy.BFloat16, n, nrhs int) {
	if len(l) < n*n {
		panic("trsm: L slice too short")
	}
	if len(b) < n*nrhs {
		panic("trsm: B slice too short")
	}
	var p_l unsafe.Pointer
	if len(l) > 0 {
		p_l = unsafe.Pointer(&l[0])
	}
	var p_b unsafe.Pointer
	if len(b) > 0 {
		p_b = unsafe.Pointer(&b[0])
	}
	nVal := int64(n)
	nrhsVal := int64(nrhs)
	len_lVal := int64(len(l))
	len_bVal := int64(len(b))
	asm.TrsmLN_BF16(
		p_l,
		p_b,
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&nrhsVal),
		unsafe.Pointer(&len_lVal),
		unsafe.Pointer(&len_bVal),
	)
}

func trsmLNAsmF32(l, b []float32, n, nrhs int) {
	if len(l) < n*n {
		panic("trsm: L slice too short")
	}
	if len(b) < n*nrhs {
		panic("trsm: B slice too short")
	}
	var p_l unsafe.Pointer
	if len(l) > 0 {
		p_l = unsafe.Pointer(&l[0])
	}
	var p_b unsafe.Pointer
	if len(b) > 0 {
		p_b = unsafe.Pointer(&b[0])
	}
	nVal := int64(n)
	nrhsVal := int64(nrhs)
	len_lVal := int64(len(l))
	len_bVal := int64(len(b))
	asm.TrsmLN_F32(
		p_l,
		p_b,
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&nrhsVal),
		unsafe.Pointer(&len_lVal),
		unsafe.Pointer(&len_bVal),
	)
}

func trsmLNAsmF64(l, b []float64, n, nrhs int) {
	if len(l) < n*n {
		panic("trsm: L slice too short")
	}
	if len(b) < n*nrhs {
		panic("trsm: B slice too short")
	}
	var p_l unsafe.Pointer
	if len(l) > 0 {
		p_l = unsafe.Pointer(&l[0])
	}
	var p_b unsafe.Pointer
	if len(b) > 0 {
		p_b = unsafe.Pointer(&b[0])
	}
	nVal := int64(n)
	nrhsVal := int64(nrhs)
	len_lVal := int64(len(l))
	len_bVal := int64(len(b))
	asm.TrsmLN_F64(
		p_l,
		p_b,
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&nrhsVal),
		unsafe.Pointer(&len_lVal),
		unsafe.Pointer(&len_bVal),
	)
}

func trsmLTAsmF16(l, b []hwy.Float16, n, nrhs int) {
	if len(l) < n*n {
		panic("trsm: L slice too short")
	}
	if len(b) < n*nrhs {
		panic("trsm: B slice too short")
	}
	var p_l unsafe.Pointer
	if len(l) > 0 {
		p_l = unsafe.Pointer(&l[0])
	}
	var p_b unsafe.Pointer
	if len(b) > 0 {
		p_b = unsafe.Pointer(&b[0])
	}
	nVal := int64(n)
	nrhsVal := int64(nrhs)
	len_lVal := int64(len(l))
	len_bVal := int64(len(b))
	asm.TrsmLT_F16(
		p_l,
		p_b,
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&nrhsVal),
		unsafe.Pointer(&len_lVal),
		unsafe.Pointer(&len_bVal),
	)
}

func trsmLTAsmBF16(l, b []hwy.BFloat16, n, nrhs int) {
	if len(l) < n*n {
		panic("trsm: L slice too short")
	}
	if len(b) < n*nrhs {
		panic("trsm: B slice too short")
	}
	var p_l unsafe.Pointer
	if len(l) > 0 {
		p_l = unsafe.Pointer(&l[0])
	}
	var p_b unsafe.Pointer
	if len(b) > 0 {
		p_b = unsafe.Pointer(&b[0])
	}
	nVal := int64(n)
	nrhsVal := int64(nrhs)
	len_lVal := int64(len(l))
	len_bVal := int64(len(b))
	asm.TrsmLT_BF16(
		p_l,
		p_b,
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&nrhsVal),
		unsafe.Pointer(&len_lVal),
		unsafe.Pointer(&len_bVal),
	)
}

func trsmLTAsmF32(l, b []float32, n, nrhs int) {
	if len(l) < n*n {
		panic("trsm: L slice too short")
	}
	if len(b) < n*nrhs {
		panic("trsm: B slice too short")
	}
	var p_l unsafe.Pointer
	if len(l) > 0 {
		p_l = unsafe.Pointer(&l[0])
	}
	var p_b unsafe.Pointer
	if len(b) > 0 {
		p_b = unsafe.Pointer(&b[0])
	}
	nVal := int64(n)
	nrhsVal := int64(nrhs)
	len_lVal := int64(len(l))
	len_bVal := int64(len(b))
	asm.TrsmLT_F32(
		p_l,
		p_b,
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&nrhsVal),
		unsafe.Pointer(&len_lVal),
		unsafe.Pointer(&len_bVal),
	)
}

func trsmLTAsmF64(l, b []float64, n, nrhs int) {
	if len(l) < n*n {
		panic("trsm: L slice too short")
	}
	if len(b) < n*nrhs {
		panic("trsm: B slice too short")
	}
	var p_l unsafe.Pointer
	if len(l) > 0 {
		p_l = unsafe.Pointer(&l[0])
	}
	var p_b unsafe.Pointer
	if len(b) > 0 {
		p_b = unsafe.Pointer(&b[0])
	}
	nVal := int64(n)
	nrhsVal := int64(nrhs)
	len_lVal := int64(len(l))
	len_bVal := int64(len(b))
	asm.TrsmLT_F64(
		p_l,
		p_b,
		unsafe.Pointer(&nVal),
		unsafe.Pointer(&nrhsVal),
		unsafe.Pointer(&len_lVal),
		unsafe.Pointer(&len_bVal),
	)
}

